--insert
use ESERVICE
go

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'ONLINECHANGE_POPUP_MSG', N'線上申請提示',
		N'配合壽險公會系統維護作業，預計4/22起至5/3進行系統例行性更新，理賠醫起通將停止服務',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='SYSTEM_MSG_PARAMETER'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'ONLINECHANGE_POPUP_TIME_FORMAT', N'線上申請提示訊息之時間範圍',
		N'20220422 00:00:00-20220503 23:59:59',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='SYSTEM_MSG_PARAMETER'), NULL, '格式yyyyMMdd HH:mm:ss-yyyyMMdd HH:mm:ss', 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go


--文件上傳最大值_start
--這段SCRIPT若production已有，請勿再執行
INSERT ESERVICE_ADM.dbo.PARAMETER_CATEGORY (PARAMETER_CATEGORY_ID, SYSTEM_ID, CATEGORY_CODE, CATEGORY_NAME, REMARK, STATUS, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(PARAMETER_CATEGORY_ID)+1 from ESERVICE_ADM.dbo.PARAMETER_CATEGORY), N'eservice', N'UPLOAD_MAX_NUMBER', N'文件上傳最大值', N'', 1, getdate(), N'admin', getdate(), N'admin')
GO
INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'UPLOAD_MAX_NUMBER', N'保戶人員',10240, (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='UPLOAD_MAX_NUMBER'), NULL, NULL, 1, N'N', NULL, getdate(), N'admin', getdate(), N'admin')
go
--文件上傳最大值_end