USE ESERVICE;

ALTER TABLE ESERVICE.DBO.TRANS_INSURANCE_CLAIM ADD SIGN_AGREE NVARCHAR(5);
ALTER TABLE ESERVICE.DBO.TRANS_MEDICAL_TREATMENT_CLAIM ADD SIGN_AGREE NVARCHAR(5);

ALTER TABLE ESERVICE.DBO.BXCZ_API_LOG ADD ACTION_ID NVARCHAR(32);

CREATE UNIQUE INDEX UNIQUE_BXCZ_ACTION_ID ON ESERVICE.DBO.BXCZ_API_LOG(ACTION_ID);