USE ESERVICE;

CREATE TABLE BXCZ_API_LOG(
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[TYPE] [nvarchar](50) NOT NULL,
	[API_CODE] [nvarchar](20) NULL,
	[API_PARAM] [nvarchar](2000) NULL,
	[API_RESPONSE] [nvarchar](4000) NULL,
 CONSTRAINT [PK_BXCZ_API_LOG] PRIMARY KEY CLUSTERED
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO