INSERT ESERVICE_ADM.DBO.PARAMETER_CATEGORY(
	PARAMETER_CATEGORY_ID,
	SYSTEM_ID,
	CATEGORY_CODE,
	CATEGORY_NAME,
	REMARK,
	STATUS,
	CREATE_DATE,
	CREATE_USER,
	UPDATE_DATE,
	UPDATE_USER)
VALUES (
   (select max(PARAMETER_CATEGORY_ID)+1 from ESERVICE_ADM.DBO.PARAMETER_CATEGORY),
   'eservice_api',
   'SYS_MEDICAL_API_URL',
   N'醫療資源定位地址-系統屬性',
   NULL,
   '1.0000',
   GETDATE(),
   'admin',
   NULL,
   NULL
)
INSERT ESERVICE_ADM.DBO.PARAMETER_CATEGORY(
	PARAMETER_CATEGORY_ID,
	SYSTEM_ID,
	CATEGORY_CODE,
	CATEGORY_NAME,
	REMARK,
	STATUS,
	CREATE_DATE,
	CREATE_USER,
	UPDATE_DATE,
	UPDATE_USER)
VALUES (
   (select max(PARAMETER_CATEGORY_ID)+1 from ESERVICE_ADM.DBO.PARAMETER_CATEGORY),
   'eservice_api',
   'SYS_MEDICAL_SCH',
   N'醫療日程安排-系統屬性',
   NULL,
   '1.0000',
   GETDATE(),
   'admin',
   NULL,
   NULL
)
-----Insert PARAMETER for medicalAlliance  Schedule
INSERT ESERVICE_ADM.DBO.PARAMETER (
     PARAMETER_ID, SYSTEM_ID,
     PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE,
     PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS,
     ENCRYPT_TYPE, PARENT_PARAMETER_ID,
     CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES (
     (select max(PARAMETER_ID)+1 from ESERVICE_ADM.DBO.PARAMETER), N'eservice_api',
     N'cron.api.medical.disable', N'cron.api.medical.disable', N'N',
     (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.DBO.PARAMETER_CATEGORY where CATEGORY_CODE='SYS_MEDICAL_SCH'), 0, NULL, 1,
     NULL, NULL,
     GETDATE(), N'admin', NULL, NULL)
go

INSERT ESERVICE_ADM.DBO.PARAMETER (
     PARAMETER_ID, SYSTEM_ID,
     PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE,
     PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS,
     ENCRYPT_TYPE, PARENT_PARAMETER_ID,
     CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES (
     (select max(PARAMETER_ID)+1 from ESERVICE_ADM.DBO.PARAMETER), N'eservice_api',
     N'cron.saveToMedicalTrans.expression', N'cron.saveToMedicalTrans.expression',  N'0 */5 * * * ?',
     (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.DBO.PARAMETER_CATEGORY where CATEGORY_CODE='SYS_MEDICAL_SCH'), 0, NULL, 1,
     NULL, NULL,
     GETDATE(), N'admin', NULL, NULL)
go


INSERT ESERVICE_ADM.DBO.PARAMETER (
     PARAMETER_ID, SYSTEM_ID,
     PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE,
     PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS,
     ENCRYPT_TYPE, PARENT_PARAMETER_ID,
     CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES (
     (select max(PARAMETER_ID)+1 from ESERVICE_ADM.DBO.PARAMETER), N'eservice_api',
     N'cron.saveTransToMedical.expression', N'cron.saveTransToMedical.expression',  N'0 */5 * * * ?',
     (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.DBO.PARAMETER_CATEGORY where CATEGORY_CODE='SYS_MEDICAL_SCH'), 0, NULL, 1,
     NULL, NULL,
     GETDATE(), N'admin', NULL, NULL)
go







INSERT ESERVICE_ADM.DBO.PARAMETER (
     PARAMETER_ID, SYSTEM_ID,
     PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE,
     PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS,
     ENCRYPT_TYPE, PARENT_PARAMETER_ID,
     CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES (
     (select max(PARAMETER_ID)+1 from ESERVICE_ADM.DBO.PARAMETER), N'eservice_api',
     N'cron.medical401.expression', N'cron.medical401.expression',  N'0 */5 * * * ?',
     (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.DBO.PARAMETER_CATEGORY where CATEGORY_CODE='SYS_MEDICAL_SCH'), 0, NULL, 1,
     NULL, NULL,
     GETDATE(), N'admin', NULL, NULL)
go
INSERT ESERVICE_ADM.DBO.PARAMETER (
     PARAMETER_ID, SYSTEM_ID,
     PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE,
     PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS,
     ENCRYPT_TYPE, PARENT_PARAMETER_ID,
     CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES (
     (select max(PARAMETER_ID)+1 from ESERVICE_ADM.DBO.PARAMETER), N'eservice_api',
     N'cron.medical402.expression', N'cron.medical402.expression',  N'0 */5 * * * ?',
     (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.DBO.PARAMETER_CATEGORY where CATEGORY_CODE='SYS_MEDICAL_SCH'), 0, NULL, 1,
     NULL, NULL,
     GETDATE(), N'admin', NULL, NULL)
go
INSERT ESERVICE_ADM.DBO.PARAMETER (
     PARAMETER_ID, SYSTEM_ID,
     PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE,
     PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS,
     ENCRYPT_TYPE, PARENT_PARAMETER_ID,
     CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES (
     (select max(PARAMETER_ID)+1 from ESERVICE_ADM.DBO.PARAMETER), N'eservice_api',
     N'cron.medical403.expression', N'cron.medical403.expression',  N'0 */5 * * * ?',
     (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.DBO.PARAMETER_CATEGORY where CATEGORY_CODE='SYS_MEDICAL_SCH'), 0, NULL, 1,
     NULL, NULL,
     GETDATE(), N'admin', NULL, NULL)
go
INSERT ESERVICE_ADM.DBO.PARAMETER (
     PARAMETER_ID, SYSTEM_ID,
     PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE,
     PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS,
     ENCRYPT_TYPE, PARENT_PARAMETER_ID,
     CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES (
     (select max(PARAMETER_ID)+1 from ESERVICE_ADM.DBO.PARAMETER), N'eservice_api',
     N'cron.medical404.expression', N'cron.medical404.expression',  N'0 */5 * * * ?',
     (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.DBO.PARAMETER_CATEGORY where CATEGORY_CODE='SYS_MEDICAL_SCH'), 0, NULL, 1,
     NULL, NULL,
     GETDATE(), N'admin', NULL, NULL)
go
INSERT ESERVICE_ADM.DBO.PARAMETER (
     PARAMETER_ID, SYSTEM_ID,
     PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE,
     PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS,
     ENCRYPT_TYPE, PARENT_PARAMETER_ID,
     CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES (
     (select max(PARAMETER_ID)+1 from ESERVICE_ADM.DBO.PARAMETER), N'eservice_api',
     N'cron.medical405.expression', N'cron.medical405.expression',  N'0 */5 * * * ?',
     (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.DBO.PARAMETER_CATEGORY where CATEGORY_CODE='SYS_MEDICAL_SCH'), 0, NULL, 1,
     NULL, NULL,
     GETDATE(), N'admin', NULL, NULL)
go
INSERT ESERVICE_ADM.DBO.PARAMETER (
     PARAMETER_ID, SYSTEM_ID,
     PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE,
     PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS,
     ENCRYPT_TYPE, PARENT_PARAMETER_ID,
     CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES (
     (select max(PARAMETER_ID)+1 from ESERVICE_ADM.DBO.PARAMETER), N'eservice_api',
     N'cron.medical406.expression', N'cron.medical406.expression',  N'0 */5 * * * ?',
     (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.DBO.PARAMETER_CATEGORY where CATEGORY_CODE='SYS_MEDICAL_SCH'), 0, NULL, 1,
     NULL, NULL,
     GETDATE(), N'admin', NULL, NULL)
go
INSERT ESERVICE_ADM.DBO.PARAMETER (
     PARAMETER_ID, SYSTEM_ID,
     PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE,
     PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS,
     ENCRYPT_TYPE, PARENT_PARAMETER_ID,
     CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES (
     (select max(PARAMETER_ID)+1 from ESERVICE_ADM.DBO.PARAMETER), N'eservice_api',
     N'cron.medical407.expression', N'cron.medical407.expression',  N'0 * */8 * * ?',
     (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.DBO.PARAMETER_CATEGORY where CATEGORY_CODE='SYS_MEDICAL_SCH'), 0, NULL, 1,
     NULL, NULL,
     GETDATE(), N'admin', NULL, NULL)
go
INSERT ESERVICE_ADM.DBO.PARAMETER (
     PARAMETER_ID, SYSTEM_ID,
     PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE,
     PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS,
     ENCRYPT_TYPE, PARENT_PARAMETER_ID,
     CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES (
     (select max(PARAMETER_ID)+1 from ESERVICE_ADM.DBO.PARAMETER), N'eservice_api',
     N'cron.medical408.expression', N'cron.medical408.expression',  N'0 * */8 * * ?',
     (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.DBO.PARAMETER_CATEGORY where CATEGORY_CODE='SYS_MEDICAL_SCH'), 0, NULL, 1,
     NULL, NULL,
     GETDATE(), N'admin', NULL, NULL)
go

INSERT ESERVICE_ADM.DBO.PARAMETER (
     PARAMETER_ID, SYSTEM_ID,
     PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE,
     PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS,
     ENCRYPT_TYPE, PARENT_PARAMETER_ID,
     CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES (
     (select max(PARAMETER_ID)+1 from ESERVICE_ADM.DBO.PARAMETER), N'eservice_api',
     N'medicalAlliance.api401.url', N'medicalAlliance.api401.url', N'http://10.210.1.181/lia-api/api/ext/ihs401i',
     (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.DBO.PARAMETER_CATEGORY where CATEGORY_CODE='SYS_MEDICAL_API_URL'), 0, NULL, 1,
     NULL, NULL,
     GETDATE(), N'admin', NULL, NULL)
go


INSERT ESERVICE_ADM.DBO.PARAMETER (
     PARAMETER_ID, SYSTEM_ID,
     PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE,
     PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS,
     ENCRYPT_TYPE, PARENT_PARAMETER_ID,
     CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES (
     (select max(PARAMETER_ID)+1 from ESERVICE_ADM.DBO.PARAMETER), N'eservice_api',
     N'medicalAlliance.api402.url', N'medicalAlliance.api402.url', N'http://10.210.1.181/lia-api/api/ext/ihs402i',
     (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.DBO.PARAMETER_CATEGORY where CATEGORY_CODE='SYS_MEDICAL_API_URL'), 0, NULL, 1,
     NULL, NULL,
     GETDATE(), N'admin', NULL, NULL)
go

INSERT ESERVICE_ADM.DBO.PARAMETER (
     PARAMETER_ID, SYSTEM_ID,
     PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE,
     PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS,
     ENCRYPT_TYPE, PARENT_PARAMETER_ID,
     CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES (
     (select max(PARAMETER_ID)+1 from ESERVICE_ADM.DBO.PARAMETER), N'eservice_api',
     N'medicalAlliance.api403.url', N'medicalAlliance.api403.url', N'http://10.210.1.181/lia-api/api/ext/ihs403i',
     (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.DBO.PARAMETER_CATEGORY where CATEGORY_CODE='SYS_MEDICAL_API_URL'), 0, NULL, 1,
     NULL, NULL,
     GETDATE(), N'admin', NULL, NULL)
go

INSERT ESERVICE_ADM.DBO.PARAMETER (
     PARAMETER_ID, SYSTEM_ID,
     PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE,
     PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS,
     ENCRYPT_TYPE, PARENT_PARAMETER_ID,
     CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES (
     (select max(PARAMETER_ID)+1 from ESERVICE_ADM.DBO.PARAMETER), N'eservice_api',
     N'medicalAlliance.api404.url', N'medicalAlliance.api404.url', N'http://10.210.1.181/lia-api/api/ext/ihs404i',
     (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.DBO.PARAMETER_CATEGORY where CATEGORY_CODE='SYS_MEDICAL_API_URL'), 0, NULL, 1,
     NULL, NULL,
     GETDATE(), N'admin', NULL, NULL)
go

INSERT ESERVICE_ADM.DBO.PARAMETER (
     PARAMETER_ID, SYSTEM_ID,
     PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE,
     PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS,
     ENCRYPT_TYPE, PARENT_PARAMETER_ID,
     CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES (
     (select max(PARAMETER_ID)+1 from ESERVICE_ADM.DBO.PARAMETER), N'eservice_api',
     N'medicalAlliance.api405.url', N'medicalAlliance.api405.url', N'http://10.210.1.181/lia-api/api/ext/ihs405i',
     (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.DBO.PARAMETER_CATEGORY where CATEGORY_CODE='SYS_MEDICAL_API_URL'), 0, NULL, 1,
     NULL, NULL,
     GETDATE(), N'admin', NULL, NULL)
go

INSERT ESERVICE_ADM.DBO.PARAMETER (
     PARAMETER_ID, SYSTEM_ID,
     PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE,
     PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS,
     ENCRYPT_TYPE, PARENT_PARAMETER_ID,
     CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES (
     (select max(PARAMETER_ID)+1 from ESERVICE_ADM.DBO.PARAMETER), N'eservice_api',
     N'medicalAlliance.api406.url', N'medicalAlliance.api406.url', N'http://10.210.1.181/lia-api/api/ext/ihs406i',
     (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.DBO.PARAMETER_CATEGORY where CATEGORY_CODE='SYS_MEDICAL_API_URL'), 0, NULL, 1,
     NULL, NULL,
     GETDATE(), N'admin', NULL, NULL)
go

INSERT ESERVICE_ADM.DBO.PARAMETER (
     PARAMETER_ID, SYSTEM_ID,
     PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE,
     PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS,
     ENCRYPT_TYPE, PARENT_PARAMETER_ID,
     CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES (
     (select max(PARAMETER_ID)+1 from ESERVICE_ADM.DBO.PARAMETER), N'eservice_api',
     N'medicalAlliance.api407.url', N'medicalAlliance.api407.url', N'http://10.210.1.181/lia-api/api/ext/ihs407i',
     (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.DBO.PARAMETER_CATEGORY where CATEGORY_CODE='SYS_MEDICAL_API_URL'), 0, NULL, 1,
     NULL, NULL,
     GETDATE(), N'admin', NULL, NULL)
go

INSERT ESERVICE_ADM.DBO.PARAMETER (
     PARAMETER_ID, SYSTEM_ID,
     PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE,
     PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS,
     ENCRYPT_TYPE, PARENT_PARAMETER_ID,
     CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES (
     (select max(PARAMETER_ID)+1 from ESERVICE_ADM.DBO.PARAMETER), N'eservice_api',
     N'medicalAlliance.api408.url', N'medicalAlliance.api408.url', N'http://10.210.1.181/lia-api/api/ext/ihs408i',
     (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.DBO.PARAMETER_CATEGORY where CATEGORY_CODE='SYS_MEDICAL_API_URL'), 0, NULL, 1,
     NULL, NULL,
     GETDATE(), N'admin', NULL, NULL)
go


--- API联盟查詢案件資訊郵件模板 进行发送邮件参数
INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice_api', N'MSG_PARAM_PROGRAM_STATUS', N'通信模板參數-案件狀態代碼'
, N'STATUS',
(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='MessagingParameter'), NULL, NULL, 1, N'N', NULL, getdate(), N'admin', getdate(), N'admin')
go
INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice_api', N'MSG_PARAM_PROGRAM_STATUS_MESSAGE', N'通信模板參數-案件狀態代碼描述'
, N'STATUS_MESSAGE',
(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='MessagingParameter'), NULL, NULL, 1, N'N', NULL, getdate(), N'admin', getdate(), N'admin')
go
INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice_api', N'MSG_PARAM_PROGRAM_HOSPITAL_CODE', N'通信模板參數-醫院代號'
, N'HOSPITAL_CODE',
(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='MessagingParameter'), NULL, NULL, 1, N'N', NULL, getdate(), N'admin', getdate(), N'admin')
go
INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice_api', N'MSG_PARAM_PROGRAM_INSURED_ID', N'通信模板參數-被保人身分證字號'
, N'INSURED_ID',
(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='MessagingParameter'), NULL, NULL, 1, N'N', NULL, getdate(), N'admin', getdate(), N'admin')
go


-- API联盟API-403查詢案件資訊郵件模板
INSERT INTO ESERVICE_ADM.[dbo].[MESSAGING_TEMPLATE]([MESSAGING_TEMPLATE_ID],[SYSTEM_ID],[MESSAGING_TEMPLATE_CODE],[MESSAGING_TEMPLATE_NAME],[STATUS],[TRIGGER_TYPE],[EVENT_TYPE],[SEND_TYPE],[SEND_TIME],[CIRCLE_TYPE],[CIRCLE_VALUE],[RECEIVER_MODE],[MESSAGING_SUBJECT],[MESSAGING_CONTENT],[CREATE_DATE],[CREATE_USER],[UPDATE_DATE],[UPDATE_USER])
VALUES((select max([MESSAGING_TEMPLATE_ID])+1 from ESERVICE_ADM.dbo.MESSAGING_TEMPLATE),N'eservice_api',N'MEDICAL_MAIL_034',N'醫療保單查詢案件資訊取得案件通知MAIL模版'
,3,N'api ',NULL,N'email',NULL,NULL,NULL,N'dynamic',N'醫療保單查詢案件資訊取得案件通知'
,N'代碼:API-${CODE}</br>訊息:已從醫院端取得授權資料，請與保險公司的核心系統確認，是否是保戶</br>案件狀態代碼及中文:${STATUS}-${STATUS_MESSAGE}</br>與醫院對接序號:${HOSPITAL_CODE}</br>被保人身分證字號:${INSURED_ID}', getdate(),N'admin',getdate(),N'admin')
GO

---MAIL模版参数[MESSAGING_PARAMETER]
INSERT INTO  ESERVICE_ADM.[dbo].[MESSAGING_PARAMETER]
           ([MESSAGING_TEMPLATE_ID]
           ,[PARAMETER_ID])
     VALUES
           ((select MESSAGING_TEMPLATE_ID  FROM   ESERVICE_ADM.dbo.[MESSAGING_TEMPLATE]  WHERE SYSTEM_ID='eservice_api' and [MESSAGING_TEMPLATE_CODE]='MEDICAL_MAIL_034')
           ,(select PARAMETER_ID  FROM   ESERVICE_ADM.dbo.PARAMETER  WHERE SYSTEM_ID='eservice_api' and PARAMETER_CODE='MSG_PARAM_CODE')
		   )
GO

---MAIL模版参数[MESSAGING_PARAMETER]
INSERT INTO  ESERVICE_ADM.[dbo].[MESSAGING_PARAMETER]
           ([MESSAGING_TEMPLATE_ID]
           ,[PARAMETER_ID])
     VALUES
           ((select MESSAGING_TEMPLATE_ID  FROM   ESERVICE_ADM.dbo.[MESSAGING_TEMPLATE]  WHERE SYSTEM_ID='eservice_api' and [MESSAGING_TEMPLATE_CODE]='MEDICAL_MAIL_034')
           ,(select PARAMETER_ID  FROM   ESERVICE_ADM.dbo.PARAMETER  WHERE SYSTEM_ID='eservice_api' and PARAMETER_CODE='MSG_PARAM_PROGRAM_STATUS')
		   )
GO
INSERT INTO  ESERVICE_ADM.[dbo].[MESSAGING_PARAMETER]
           ([MESSAGING_TEMPLATE_ID]
           ,[PARAMETER_ID])
     VALUES
           ((select MESSAGING_TEMPLATE_ID  FROM   ESERVICE_ADM.dbo.[MESSAGING_TEMPLATE]  WHERE SYSTEM_ID='eservice_api' and [MESSAGING_TEMPLATE_CODE]='MEDICAL_MAIL_034')
           ,(select PARAMETER_ID  FROM   ESERVICE_ADM.dbo.PARAMETER  WHERE SYSTEM_ID='eservice_api' and PARAMETER_CODE='MSG_PARAM_PROGRAM_STATUS_MESSAGE')
		   )
GO
INSERT INTO  ESERVICE_ADM.[dbo].[MESSAGING_PARAMETER]
           ([MESSAGING_TEMPLATE_ID]
           ,[PARAMETER_ID])
     VALUES
           ((select MESSAGING_TEMPLATE_ID  FROM   ESERVICE_ADM.dbo.[MESSAGING_TEMPLATE]  WHERE SYSTEM_ID='eservice_api' and [MESSAGING_TEMPLATE_CODE]='MEDICAL_MAIL_034')
           ,(select PARAMETER_ID  FROM   ESERVICE_ADM.dbo.PARAMETER  WHERE SYSTEM_ID='eservice_api' and PARAMETER_CODE='MSG_PARAM_PROGRAM_HOSPITAL_CODE')
		   )
GO
INSERT INTO  ESERVICE_ADM.[dbo].[MESSAGING_PARAMETER]
           ([MESSAGING_TEMPLATE_ID]
           ,[PARAMETER_ID])
     VALUES
           ((select MESSAGING_TEMPLATE_ID  FROM   ESERVICE_ADM.dbo.[MESSAGING_TEMPLATE]  WHERE SYSTEM_ID='eservice_api' and [MESSAGING_TEMPLATE_CODE]='MEDICAL_MAIL_034')
           ,(select PARAMETER_ID  FROM   ESERVICE_ADM.dbo.PARAMETER  WHERE SYSTEM_ID='eservice_api' and PARAMETER_CODE='MSG_PARAM_PROGRAM_INSURED_ID')
		   )
GO
--PARAMETER_CATEGORY
insert into ESERVICE_ADM.dbo.PARAMETER_CATEGORY
	(PARAMETER_CATEGORY_ID,SYSTEM_ID,CATEGORY_CODE,CATEGORY_NAME,REMARK,STATUS,CREATE_DATE,CREATE_USER,UPDATE_DATE,UPDATE_USER)
values
	(
		(select max(PARAMETER_CATEGORY_ID)+1 from ESERVICE_ADM.dbo.PARAMETER_CATEGORY),
		'eservice_adm',
		'MEDICAL_ALLIANCE_MAIL',
		'醫療首家轉收件',
		'醫療授權資料需通知作業人員',
		'1',
		getdate(),
		'admin',
		getdate(),
		'admin'
	);
go

insert into ESERVICE_ADM.dbo.PARAMETER
	(PARAMETER_ID,SYSTEM_ID,PARAMETER_CODE,PARAMETER_NAME,PARAMETER_VALUE,PARAMETER_CATEGORY_ID,STATUS,ENCRYPT_TYPE,CREATE_DATE,CREATE_USER,UPDATE_DATE,UPDATE_USER)
values
	(
		(select max(PARAMETER_ID)+1 from ESERVICE_ADM.dbo.PARAMETER),
		'eservice_adm',
		'MEDICAL_ALLIANCE_MAIL_TWFHCLIFE_ADM',
		'醫療作業通知人員',
		'203216@twfhclife.com.tw;190064@twfhclife.com.tw;203352@twfhclife.com.tw;203990@twfhclife.com.tw;202712@twfhclife.com.tw;202859@twfhclife.com.tw;831227@twfhclife.com.tw',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='MEDICAL_ALLIANCE_MAIL'),
		'1',
		'N',
		getdate(),
		'admin',
		getdate(),
		'admin'
	);
go