--TRANS
insert into ESERVICE.dbo.TRANS(
	TRANS_NUM
	,TRANS_DATE
	,TRANS_TYPE
	,USER_ID
	,STATUS
	,CREATE_USER
	,CREATE_DATE
	,UPDATE_USER
	,UPDATE_DATE
)
values(
	'209901010001',
	getdate(),
	'INSURANCE_CLAIM',
	'twfhclife',
	'-1',
	'twfhclife',
	getdate(),
	null,
	null
);

--TRANS_POLICY
insert into ESERVICE.dbo.TRANS_POLICY
(TRANS_NUM,POLICY_NO)
values
('209901010001','1234567890');

--
select * from ESERVICE.dbo.TRANS_INSURANCE_CLAIM;

--TRANS_INSURANCE_CLAIM
insert into ESERVICE.dbo.TRANS_INSURANCE_CLAIM(
	CLAIMS_SEQ_ID,
	CASE_ID,TRANS_NUM
	,FILE_RECEIVED
	,APPLYITEM
	,POLICYNO
	,CUSTOMERNAME
	,NAME,RELATION,ID_NO,BIRDATE
	,TEL,PHONE
	,ZIP_CODE,ADDRESS
	,MAIL
	,DISEASENAME
	,DIAGNOSISDATE
	,HOSPITAL
	,OTHERCOMPANYINSURED,OTHERINSUCOMMPANY,OTHERINSUTYPE,OTHERINSUAMOUNT,OTHERINSUCLAIM
	,PAYMENT_METHOD
	,BANK_CODE,BRANCH_CODE,BANK_ACCOUNT,ACCOUNTNAME
	,APPLICATION_DATE,APPLICATION_TIME,APPLICATION_ITEM
	,JOB,JOB_DESCR
	,ACCIDENT_DATE,ACCIDENT_TIME,ACCIDENT_CAUSE,ACCIDENT_LOCATION,ACCIDENT_DESCR
	,POLICE_STATION,POLICE_NAME,POLICE_PHONE,POLICE_DATE,POLICE_TIME
	,CALLPOLICE
	,FROM_COMPANY_ID
	,TO_COMPANY_ID
	,SEND_ALLIANCE
	,CREATE_DATE
)
values(
	(next value for TRANS_INSURANCE_CLAIM_SEQ),
	null,'209901010001',
	null,
	null,
	'1234567890',
	'twfhclife',
	'namevalue','1','A123456789','19900101',
	'022222222','0900000000',
	'123','address',
	'a@hotmail.com',
	'DISEASENAME',
	'20200101',
	'HOSPITAL',
	'N','OTHERINSUCOMMPANY','OTHERINSUTYPE','OTHERINSUAMOUNT','OTHERINSUCLAIM',
	'1',
	'000','0000','ACCOUNT','ACCOUNTNAME',
	'20210101','1200','1',
	'job','job-descr',
	'20200101','1200','1','location','decri',
	'policystation','policyname','0900000000','20200101','1200',
	'Y',
	'L01',
	'L02,L03,L04',
	'N',
	getdate()
)