--BANK_INFO
update ESERVICE.DBO.BANK_INFO
set BRANCH_ID='0021'
where BANK_ID='700' AND BRANCH_ID='0010';

--drop TRANS_EZ cONSTRAIONT
alter table ESERVICE.dbo.TRANS_EZ
drop CONSTRAINT SYS_C0030886
go



