@startuml

class ChangePasswordController {
    updatePassword()
}
interface IRegisterUserService {
    updatePassword()
}
class RegisterUserServiceImpl {
    updatePassword()
}
class UsersVo {
   userId
   newPassword
}

ChangePasswordController -|> UsersVo
ChangePasswordController -|> IRegisterUserService
IRegisterUserService <|-- RegisterUserServiceImpl

@enduml