@startuml

autonumber

使用者 -> ChangePasswordController: updatePassword()
ChangePasswordController --> RegisterUserServiceImpl: updatePassword(account, newPassword)
RegisterUserServiceImpl --> API: resetPwd()
API --> RegisterUserServiceImpl: return JSON
RegisterUserServiceImpl --> ChangePasswordController: String
ChangePasswordController --> 使用者: ResponseObj
@enduml