@startuml

class ForgetPasswordController {
    updatePassword(newPassword)
}
interface IRegisterUserService {
    updatePassword(account, newPassword)
}
class RegisterUserServiceImpl {
    updatePassword(account, newPassword)
}


ForgetPasswordController -|> IRegisterUserService
IRegisterUserService <|-- RegisterUserServiceImpl

@enduml