@startuml

autonumber

使用者 -> ForgetPasswordController: updatePassword(newPassword)
ForgetPasswordController --> RegisterUserServiceImpl: updatePassword(account, newPassword)
RegisterUserServiceImpl --> API: resetPwd()
API --> RegisterUserServiceImpl: return JSON
RegisterUserServiceImpl --> ForgetPasswordController: String
ForgetPasswordController --> 使用者: ResponseObj
@enduml