@startuml

autonumber

使用者 -> MessageController: message()
MessageController --> MessageServiceImpl: getMessages()
MessageServiceImpl --> API: getMessages()
API --> MessageServiceImpl: return JSON
MessageServiceImpl --> MessageController: String
MessageController --> 使用者: ResponseObj
@enduml