use ESERVICE_ADM
GO

create sequence JD_PARAMETER_CATEGORY_SEQ
minvalue 1
maxvalue 9223372036854775807
start with 1
increment by 1
no cache;

INSERT INTO PARAMETER_CATEGORY(PARAMETER_CATEGORY_ID,
SYSTEM_ID,
CATEGORY_CODE,
CATEGORY_NAME,
REMARK,
STATUS,
CREATE_DATE,
CREATE_USER,
UPDATE_DATE,
UPDATE_USER) SELECT NEXT VALUE for JD_PARAMETER_CATEGORY_SEQ + (select max(PARAMETER_CATEGORY_ID)+1 from ESERVICE_ADM.dbo.PARAMETER_CATEGORY),
'eservice_jd',
CATEGORY_CODE,
CATEGORY_NAME,
REMARK,
STATUS,
SYSDATETIME(),
CREATE_USER,
SYSDATETIME(),
UPDATE_USER FROM PARAMETER_CATEGORY WHERE SYSTEM_ID in ('eservice', 'eservice_adm')

create sequence JD_PARAMETER_SEQ
minvalue 1
maxvalue 9223372036854775807
start with 1
increment by 1
no cache;

INSERT ESERVICE_ADM.DBO.PARAMETER (
     PARAMETER_ID,
SYSTEM_ID,
PARAMETER_CODE,
PARAMETER_NAME,
PARAMETER_VALUE,
PARAMETER_CATEGORY_ID,
STATUS,
ENCRYPT_TYPE,
CREATE_DATE,
CREATE_USER,
UPDATE_DATE,
UPDATE_USER)
SELECT NEXT VALUE for JD_PARAMETER_SEQ + (select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER) PARAMETER_ID, 'eservice_jd' SYSTEM_ID,
     A.PARAMETER_CODE, A.PARAMETER_NAME, A.PARAMETER_VALUE,
     (SELECT TOP 1 PARAMETER_CATEGORY_ID FROM PARAMETER_CATEGORY B WHERE B.CATEGORY_CODE = (
        SELECT TOP 1 CATEGORY_CODE FROM PARAMETER_CATEGORY C WHERE C.PARAMETER_CATEGORY_ID = A.PARAMETER_CATEGORY_ID
     ) AND SYSTEM_ID = 'eservice_jd') CATEGORY_ID, '1' STATUS,
        'N' ENCRYPT_TYPE,
        getdate() CREATE_DATE,
        'admin' CREATE_USER,
        getdate() UPDATE_DATE,
        'admin' UPDATE_USER
        FROM ESERVICE_ADM.DBO.PARAMETER A WHERE SYSTEM_ID in ('eservice', 'eservice_adm')
        AND (SELECT TOP 1 PARAMETER_CATEGORY_ID FROM PARAMETER_CATEGORY B WHERE B.CATEGORY_CODE = (
        SELECT TOP 1 CATEGORY_CODE FROM PARAMETER_CATEGORY C WHERE C.PARAMETER_CATEGORY_ID = A.PARAMETER_CATEGORY_ID
     ) AND SYSTEM_ID = 'eservice_jd') IS NOT NULL


DROP SEQUENCE JD_PARAMETER_CATEGORY_SEQ
DROP SEQUENCE JD_PARAMETER_SEQ

INSERT INTO ESERVICE_ADM.[dbo].[MESSAGING_TEMPLATE]([MESSAGING_TEMPLATE_ID],[SYSTEM_ID],[MESSAGING_TEMPLATE_CODE],[MESSAGING_TEMPLATE_NAME],[STATUS],[TRIGGER_TYPE],[EVENT_TYPE],[SEND_TYPE],[SEND_TIME],[CIRCLE_TYPE],[CIRCLE_VALUE],[RECEIVER_MODE],[MESSAGING_SUBJECT],[MESSAGING_CONTENT],[CREATE_DATE],[CREATE_USER],[UPDATE_DATE],[UPDATE_USER])
VALUES((select max([MESSAGING_TEMPLATE_ID])+1 from ESERVICE_ADM.dbo.MESSAGING_TEMPLATE),N'eservice_jd',N'ELIFE_JD_MAIL-001',N'照會之截止日通知'
,3,N'api',NULL,N'email',NULL,NULL,NULL,N'dynamic',N'照會截止日通知'
,N'要保人${AppName}/被保險人${InsName}-保單號碼${POLICY_No}案件的照會回覆截止日期為${DueDate}，再請確認是否已回覆。', getdate(),N'admin',getdate(),N'admin')
GO

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice_jd', N'MSG_PARAM_APP_NAME', N'通信模板參數-要保險人'
, N'AppName',
(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='MessagingParameter' AND SYSTEM_ID = 'eservice_jd'), NULL, NULL, 1, N'N', NULL, getdate(), N'admin', getdate(), N'admin')
go

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice_jd', N'MSG_PARAM_INS_NAME', N'通信模板參數-被保險人'
, N'InsName',
(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='MessagingParameter' AND SYSTEM_ID = 'eservice_jd'), NULL, NULL, 1, N'N', NULL, getdate(), N'admin', getdate(), N'admin')
go

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice_jd', N'MSG_PARAM_DUE_DATE', N'通信模板參數-回覆截止日'
, N'DueDate',
(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='MessagingParameter' AND SYSTEM_ID = 'eservice_jd'), NULL, NULL, 1, N'N', NULL, getdate(), N'admin', getdate(), N'admin')
go

INSERT INTO  ESERVICE_ADM.[dbo].[MESSAGING_PARAMETER]
           ([MESSAGING_TEMPLATE_ID]
           ,[PARAMETER_ID])
     VALUES
           ((select MESSAGING_TEMPLATE_ID  FROM   ESERVICE_ADM.dbo.[MESSAGING_TEMPLATE]  WHERE SYSTEM_ID='eservice_jd' and [MESSAGING_TEMPLATE_CODE]='ELIFE_JD_MAIL-001')
           ,(select PARAMETER_ID  FROM   ESERVICE_ADM.dbo.PARAMETER  WHERE SYSTEM_ID='eservice_jd' and PARAMETER_CODE='MSG_PARAM_POLICY_NO')
           )
GO

INSERT INTO  ESERVICE_ADM.[dbo].[MESSAGING_PARAMETER]
           ([MESSAGING_TEMPLATE_ID]
           ,[PARAMETER_ID])
     VALUES
           ((select MESSAGING_TEMPLATE_ID  FROM   ESERVICE_ADM.dbo.[MESSAGING_TEMPLATE]  WHERE SYSTEM_ID='eservice_jd' and [MESSAGING_TEMPLATE_CODE]='ELIFE_JD_MAIL-001')
           ,(select PARAMETER_ID  FROM   ESERVICE_ADM.dbo.PARAMETER  WHERE SYSTEM_ID='eservice_jd' and PARAMETER_CODE='MSG_PARAM_APP_NAME')
           )
GO

INSERT INTO  ESERVICE_ADM.[dbo].[MESSAGING_PARAMETER]
           ([MESSAGING_TEMPLATE_ID]
           ,[PARAMETER_ID])
     VALUES
           ((select MESSAGING_TEMPLATE_ID  FROM   ESERVICE_ADM.dbo.[MESSAGING_TEMPLATE]  WHERE SYSTEM_ID='eservice_jd' and [MESSAGING_TEMPLATE_CODE]='ELIFE_JD_MAIL-001')
           ,(select PARAMETER_ID  FROM   ESERVICE_ADM.dbo.PARAMETER  WHERE SYSTEM_ID='eservice_jd' and PARAMETER_CODE='MSG_PARAM_INS_NAME')
           )
GO

INSERT INTO  ESERVICE_ADM.[dbo].[MESSAGING_PARAMETER]
           ([MESSAGING_TEMPLATE_ID]
           ,[PARAMETER_ID])
     VALUES
           ((select MESSAGING_TEMPLATE_ID  FROM   ESERVICE_ADM.dbo.[MESSAGING_TEMPLATE]  WHERE SYSTEM_ID='eservice_jd' and [MESSAGING_TEMPLATE_CODE]='ELIFE_JD_MAIL-001')
           ,(select PARAMETER_ID  FROM   ESERVICE_ADM.dbo.PARAMETER  WHERE SYSTEM_ID='eservice_jd' and PARAMETER_CODE='MSG_PARAM_DUE_DATE')
           )
GO

delete from parameter where parameter_code = 'AUTH_CODE_CONT' and system_id = 'eservice_jd'
delete from parameter where parameter_code = 'AUTH_CODE_SUB' and system_id = 'eservice_jd'

--- 事件參數管理
DELETE FROM PARAMETER WHERE PARAMETER_CATEGORY_ID = (SELECT PARAMETER_CATEGORY_ID FROM PARAMETER_CATEGORY WHERE CATEGORY_CODE = 'EVENT_TYPE' AND SYSTEM_ID = 'eservice_jd')

insert into ESERVICE_ADM.dbo.PARAMETER
	(PARAMETER_ID,SYSTEM_ID,PARAMETER_CODE,PARAMETER_NAME,PARAMETER_VALUE,PARAMETER_CATEGORY_ID,STATUS,CREATE_DATE,CREATE_USER)
values
	((select max(PARAMETER_ID)+1 PARAMETER_ID from ESERVICE_ADM.dbo.PARAMETER),'eservice_jd','AA-019',N'經代登入','AA-019',
	 (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='EVENT_TYPE' and SYSTEM_ID='eservice_jd'),'1',getdate(),'admin');
GO

insert into ESERVICE_ADM.dbo.PARAMETER
	(PARAMETER_ID,SYSTEM_ID,PARAMETER_CODE,PARAMETER_NAME,PARAMETER_VALUE,PARAMETER_CATEGORY_ID,STATUS,CREATE_DATE,CREATE_USER)
values
	((select max(PARAMETER_ID)+1 PARAMETER_ID from ESERVICE_ADM.dbo.PARAMETER),'eservice_jd','AA-022',N'經代登出','AA-022',
	 (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='EVENT_TYPE' and SYSTEM_ID='eservice_jd'),'1',getdate(),'admin');
GO

insert into ESERVICE_ADM.dbo.PARAMETER
	(PARAMETER_ID,SYSTEM_ID,PARAMETER_CODE,PARAMETER_NAME,PARAMETER_VALUE,PARAMETER_CATEGORY_ID,STATUS,CREATE_DATE,CREATE_USER)
values
	((select max(PARAMETER_ID)+1 PARAMETER_ID from ESERVICE_ADM.dbo.PARAMETER),'eservice_jd','JD-001',N'經代案件列表查詢','JD-001',
	 (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='EVENT_TYPE' and SYSTEM_ID='eservice_jd'),'1',getdate(),'admin');
GO

insert into ESERVICE_ADM.dbo.PARAMETER
	(PARAMETER_ID,SYSTEM_ID,PARAMETER_CODE,PARAMETER_NAME,PARAMETER_VALUE,PARAMETER_CATEGORY_ID,STATUS,CREATE_DATE,CREATE_USER)
values
	((select max(PARAMETER_ID)+1 PARAMETER_ID from ESERVICE_ADM.dbo.PARAMETER),'eservice_jd','JD-002',N'經代案件進度查詢','JD-002',
	 (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='EVENT_TYPE' and SYSTEM_ID='eservice_jd'),'1',getdate(),'admin');
GO

insert into ESERVICE_ADM.dbo.PARAMETER
	(PARAMETER_ID,SYSTEM_ID,PARAMETER_CODE,PARAMETER_NAME,PARAMETER_VALUE,PARAMETER_CATEGORY_ID,STATUS,CREATE_DATE,CREATE_USER)
values
	((select max(PARAMETER_ID)+1 PARAMETER_ID from ESERVICE_ADM.dbo.PARAMETER),'eservice_jd','JD-003','經代保單資訊查詢','JD-003',
	 (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='EVENT_TYPE' and SYSTEM_ID='eservice_jd'),'1',getdate(),'admin');
GO

insert into ESERVICE_ADM.dbo.PARAMETER
	(PARAMETER_ID,SYSTEM_ID,PARAMETER_CODE,PARAMETER_NAME,PARAMETER_VALUE,PARAMETER_CATEGORY_ID,STATUS,CREATE_DATE,CREATE_USER)
values
	((select max(PARAMETER_ID)+1 PARAMETER_ID from ESERVICE_ADM.dbo.PARAMETER),'eservice_jd','JD-004',N'經代照會查詢','JD-004',
	 (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='EVENT_TYPE' and SYSTEM_ID='eservice_jd'),'1',getdate(),'admin');
GO

insert into ESERVICE_ADM.dbo.PARAMETER
	(PARAMETER_ID,SYSTEM_ID,PARAMETER_CODE,PARAMETER_NAME,PARAMETER_VALUE,PARAMETER_CATEGORY_ID,STATUS,CREATE_DATE,CREATE_USER)
values
	((select max(PARAMETER_ID)+1 PARAMETER_ID from ESERVICE_ADM.dbo.PARAMETER),'eservice_jd','JD-005',N'經代照會單','JD-005',
	 (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='EVENT_TYPE' and SYSTEM_ID='eservice_jd'),'1',getdate(),'admin');
GO

insert into ESERVICE_ADM.dbo.PARAMETER
	(PARAMETER_ID,SYSTEM_ID,PARAMETER_CODE,PARAMETER_NAME,PARAMETER_VALUE,PARAMETER_CATEGORY_ID,STATUS,CREATE_DATE,CREATE_USER)
values
	((select max(PARAMETER_ID)+1 PARAMETER_ID from ESERVICE_ADM.dbo.PARAMETER),'eservice_jd','JD-006',N'經代保單查詢','JD-006',
	 (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='EVENT_TYPE' and SYSTEM_ID='eservice_jd'),'1',getdate(),'admin');
GO

insert into ESERVICE_ADM.dbo.PARAMETER
	(PARAMETER_ID,SYSTEM_ID,PARAMETER_CODE,PARAMETER_NAME,PARAMETER_VALUE,PARAMETER_CATEGORY_ID,STATUS,CREATE_DATE,CREATE_USER)
values
	((select max(PARAMETER_ID)+1 PARAMETER_ID from ESERVICE_ADM.dbo.PARAMETER),'eservice_jd','JD-007',N'保單基本資料','JD-007',
	 (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='EVENT_TYPE' and SYSTEM_ID='eservice_jd'),'1',getdate(),'admin');
GO

insert into ESERVICE_ADM.dbo.PARAMETER
	(PARAMETER_ID,SYSTEM_ID,PARAMETER_CODE,PARAMETER_NAME,PARAMETER_VALUE,PARAMETER_CATEGORY_ID,STATUS,CREATE_DATE,CREATE_USER)
values
	((select max(PARAMETER_ID)+1 PARAMETER_ID from ESERVICE_ADM.dbo.PARAMETER),'eservice_jd','JD-008',N'經代保障內容與金額','JD-008',
	 (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='EVENT_TYPE' and SYSTEM_ID='eservice_jd'),'1',getdate(),'admin');
GO

insert into ESERVICE_ADM.dbo.PARAMETER
	(PARAMETER_ID,SYSTEM_ID,PARAMETER_CODE,PARAMETER_NAME,PARAMETER_VALUE,PARAMETER_CATEGORY_ID,STATUS,CREATE_DATE,CREATE_USER)
values
	((select max(PARAMETER_ID)+1 PARAMETER_ID from ESERVICE_ADM.dbo.PARAMETER),'eservice_jd','JD-009',N'經代繳費紀錄','JD-009',
	 (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='EVENT_TYPE' and SYSTEM_ID='eservice_jd'),'1',getdate(),'admin');
GO

insert into ESERVICE_ADM.dbo.PARAMETER
	(PARAMETER_ID,SYSTEM_ID,PARAMETER_CODE,PARAMETER_NAME,PARAMETER_VALUE,PARAMETER_CATEGORY_ID,STATUS,CREATE_DATE,CREATE_USER)
values
	((select max(PARAMETER_ID)+1 PARAMETER_ID from ESERVICE_ADM.dbo.PARAMETER),'eservice_jd','JD-010',N'經代保單紅利資料','JD-010',
	 (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='EVENT_TYPE' and SYSTEM_ID='eservice_jd'),'1',getdate(),'admin');
GO

insert into ESERVICE_ADM.dbo.PARAMETER
	(PARAMETER_ID,SYSTEM_ID,PARAMETER_CODE,PARAMETER_NAME,PARAMETER_VALUE,PARAMETER_CATEGORY_ID,STATUS,CREATE_DATE,CREATE_USER)
values
	((select max(PARAMETER_ID)+1 PARAMETER_ID from ESERVICE_ADM.dbo.PARAMETER),'eservice_jd','JD-011',N'經代生存/滿期給付資料','JD-011',
	 (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='EVENT_TYPE' and SYSTEM_ID='eservice_jd'),'1',getdate(),'admin');
GO

insert into ESERVICE_ADM.dbo.PARAMETER
	(PARAMETER_ID,SYSTEM_ID,PARAMETER_CODE,PARAMETER_NAME,PARAMETER_VALUE,PARAMETER_CATEGORY_ID,STATUS,CREATE_DATE,CREATE_USER)
values
	((select max(PARAMETER_ID)+1 PARAMETER_ID from ESERVICE_ADM.dbo.PARAMETER),'eservice_jd','JD-012',N'經代契約變更資料','JD-012',
	 (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='EVENT_TYPE' and SYSTEM_ID='eservice_jd'),'1',getdate(),'admin');
GO

insert into ESERVICE_ADM.dbo.PARAMETER
	(PARAMETER_ID,SYSTEM_ID,PARAMETER_CODE,PARAMETER_NAME,PARAMETER_VALUE,PARAMETER_CATEGORY_ID,STATUS,CREATE_DATE,CREATE_USER)
values
	((select max(PARAMETER_ID)+1 PARAMETER_ID from ESERVICE_ADM.dbo.PARAMETER),'eservice_jd','JD-013',N'經代保單收益分配','JD-013',
	 (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='EVENT_TYPE' and SYSTEM_ID='eservice_jd'),'1',getdate(),'admin');
GO

insert into ESERVICE_ADM.dbo.PARAMETER
	(PARAMETER_ID,SYSTEM_ID,PARAMETER_CODE,PARAMETER_NAME,PARAMETER_VALUE,PARAMETER_CATEGORY_ID,STATUS,CREATE_DATE,CREATE_USER)
values
	((select max(PARAMETER_ID)+1 PARAMETER_ID from ESERVICE_ADM.dbo.PARAMETER),'eservice_jd','JD-014',N'經代交易歷史記錄','JD-014',
	 (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='EVENT_TYPE' and SYSTEM_ID='eservice_jd'),'1',getdate(),'admin');
GO

insert into ESERVICE_ADM.dbo.PARAMETER
	(PARAMETER_ID,SYSTEM_ID,PARAMETER_CODE,PARAMETER_NAME,PARAMETER_VALUE,PARAMETER_CATEGORY_ID,STATUS,CREATE_DATE,CREATE_USER)
values
	((select max(PARAMETER_ID)+1 PARAMETER_ID from ESERVICE_ADM.dbo.PARAMETER),'eservice_jd','JD-015',N'經代保費費用','JD-015',
	 (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='EVENT_TYPE' and SYSTEM_ID='eservice_jd'),'1',getdate(),'admin');
GO

insert into ESERVICE_ADM.dbo.PARAMETER
	(PARAMETER_ID,SYSTEM_ID,PARAMETER_CODE,PARAMETER_NAME,PARAMETER_VALUE,PARAMETER_CATEGORY_ID,STATUS,CREATE_DATE,CREATE_USER)
values
	((select max(PARAMETER_ID)+1 PARAMETER_ID from ESERVICE_ADM.dbo.PARAMETER),'eservice_jd','JD-016',N'經代報酬率通知設定','JD-016',
	 (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='EVENT_TYPE' and SYSTEM_ID='eservice_jd'),'1',getdate(),'admin');
GO

insert into ESERVICE_ADM.dbo.PARAMETER
	(PARAMETER_ID,SYSTEM_ID,PARAMETER_CODE,PARAMETER_NAME,PARAMETER_VALUE,PARAMETER_CATEGORY_ID,STATUS,CREATE_DATE,CREATE_USER)
values
	((select max(PARAMETER_ID)+1 PARAMETER_ID from ESERVICE_ADM.dbo.PARAMETER),'eservice_jd','JD-017',N'經代投資損益及投報率','JD-017',
	 (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='EVENT_TYPE' and SYSTEM_ID='eservice_jd'),'1',getdate(),'admin');
GO

insert into ESERVICE_ADM.dbo.PARAMETER
	(PARAMETER_ID,SYSTEM_ID,PARAMETER_CODE,PARAMETER_NAME,PARAMETER_VALUE,PARAMETER_CATEGORY_ID,STATUS,CREATE_DATE,CREATE_USER)
values
	((select max(PARAMETER_ID)+1 PARAMETER_ID from ESERVICE_ADM.dbo.PARAMETER),'eservice_jd','JD-018',N'經代解約金試算','JD-018',
	 (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='EVENT_TYPE' and SYSTEM_ID='eservice_jd'),'1',getdate(),'admin');
GO

insert into ESERVICE_ADM.dbo.PARAMETER
	(PARAMETER_ID,SYSTEM_ID,PARAMETER_CODE,PARAMETER_NAME,PARAMETER_VALUE,PARAMETER_CATEGORY_ID,STATUS,CREATE_DATE,CREATE_USER)
values
	((select max(PARAMETER_ID)+1 PARAMETER_ID from ESERVICE_ADM.dbo.PARAMETER),'eservice_jd','JD-019',N'經代投資標的淨值','JD-019',
	 (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='EVENT_TYPE' and SYSTEM_ID='eservice_jd'),'1',getdate(),'admin');
GO