use ESERVICE_ADM

create sequence JD_PARAMETER_CATEGORY_SEQ
minvalue 1
maxvalue 9223372036854775807
start with 1
increment by 1
no cache;

INSERT INTO PARAMETER_CATEGORY(PARAMETER_CATEGORY_ID,
SYSTEM_ID,
CATEGORY_CODE,
CATEGORY_NAME,
REMARK,
STATUS,
CREATE_DATE,
CREATE_USER,
UPDATE_DATE,
UPDATE_USER) SELECT NEXT VALUE for JD_PARAMETER_CATEGORY_SEQ + (select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER_CATEGORY),
'eservice_jd',
CATEGORY_CODE,
CATEGORY_NAME,
REMARK,
STATUS,
SYSDATETIME(),
CREATE_USER,
SYSDATETIME(),
UPDATE_USER FROM PARAMETER_CATEGORY WHERE SYSTEM_ID = 'eservice'

create sequence JD_PARAMETER_SEQ
minvalue 1
maxvalue 9223372036854775807
start with 1
increment by 1
no cache;

INSERT ESERVICE_ADM.DBO.PARAMETER (
     PARAMETER_ID,
SYSTEM_ID,
PARAMETER_CODE,
PARAMETER_NAME,
PARAMETER_VALUE,
PARAMETER_CATEGORY_ID,
STATUS,
ENCRYPT_TYPE,
CREATE_DATE,
CREATE_USER,
UPDATE_DATE,
UPDATE_USER)
SELECT NEXT VALUE for JD_PARAMETER_SEQ + (select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER) PARAMETER_ID, 'eservice_jd' SYSTEM_ID,
     A.PARAMETER_CODE, A.PARAMETER_NAME, A.PARAMETER_VALUE,
     (SELECT TOP 1 PARAMETER_CATEGORY_ID FROM PARAMETER_CATEGORY B WHERE B.CATEGORY_CODE = (
        SELECT TOP 1 CATEGORY_CODE FROM PARAMETER_CATEGORY C WHERE C.PARAMETER_CATEGORY_ID = A.PARAMETER_CATEGORY_ID
     ) AND SYSTEM_ID = 'eservice_jd') CATEGORY_ID, '1' STATUS,
        'N' ENCRYPT_TYPE,
        getdate() CREATE_DATE,
        'admin' CREATE_USER,
        getdate() UPDATE_DATE,
        'admin' UPDATE_USER
        FROM ESERVICE_ADM.DBO.PARAMETER A WHERE SYSTEM_ID = 'eservice'
        AND (SELECT TOP 1 PARAMETER_CATEGORY_ID FROM PARAMETER_CATEGORY B WHERE B.CATEGORY_CODE = (
        SELECT TOP 1 CATEGORY_CODE FROM PARAMETER_CATEGORY C WHERE C.PARAMETER_CATEGORY_ID = A.PARAMETER_CATEGORY_ID
     ) AND SYSTEM_ID = 'eservice_jd') IS NOT NULL


DROP SEQUENCE JD_PARAMETER_CATEGORY_SEQ
DROP SEQUENCE JD_PARAMETER_SEQ

INSERT INTO ESERVICE_ADM.[dbo].[MESSAGING_TEMPLATE]([MESSAGING_TEMPLATE_ID],[SYSTEM_ID],[MESSAGING_TEMPLATE_CODE],[MESSAGING_TEMPLATE_NAME],[STATUS],[TRIGGER_TYPE],[EVENT_TYPE],[SEND_TYPE],[SEND_TIME],[CIRCLE_TYPE],[CIRCLE_VALUE],[RECEIVER_MODE],[MESSAGING_SUBJECT],[MESSAGING_CONTENT],[CREATE_DATE],[CREATE_USER],[UPDATE_DATE],[UPDATE_USER])
VALUES((select max([MESSAGING_TEMPLATE_ID])+1 from ESERVICE_ADM.dbo.MESSAGING_TEMPLATE),N'eservice_jd',N'ELIFE_JD_MAIL-001',N'照會之截止日通知'
,3,N'api',NULL,N'email',NULL,NULL,NULL,N'dynamic',N'照會截止日通知'
,N'要保人${AppName}/被保險人${InsName}-保單號碼${POLICY_No}案件的照會回覆截止日期為${DueDate}，再請確認是否已回覆。', getdate(),N'admin',getdate(),N'admin')
GO

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice_jd', N'MSG_PARAM_APP_NAME', N'通信模板參數-要保險人'
, N'AppName',
(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='MessagingParameter' AND SYSTEM_ID = 'eservice_jd'), NULL, NULL, 1, N'N', NULL, getdate(), N'admin', getdate(), N'admin')
go

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice_jd', N'MSG_PARAM_INS_NAME', N'通信模板參數-被保險人'
, N'InsName',
(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='MessagingParameter' AND SYSTEM_ID = 'eservice_jd'), NULL, NULL, 1, N'N', NULL, getdate(), N'admin', getdate(), N'admin')
go

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice_jd', N'MSG_PARAM_DUE_DATE', N'通信模板參數-回覆截止日'
, N'DueDate',
(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='MessagingParameter' AND SYSTEM_ID = 'eservice_jd'), NULL, NULL, 1, N'N', NULL, getdate(), N'admin', getdate(), N'admin')
go

INSERT INTO  ESERVICE_ADM.[dbo].[MESSAGING_PARAMETER]
           ([MESSAGING_TEMPLATE_ID]
           ,[PARAMETER_ID])
     VALUES
           ((select MESSAGING_TEMPLATE_ID  FROM   ESERVICE_ADM.dbo.[MESSAGING_TEMPLATE]  WHERE SYSTEM_ID='eservice_jd' and [MESSAGING_TEMPLATE_CODE]='ELIFE_JD_MAIL-001')
           ,(select PARAMETER_ID  FROM   ESERVICE_ADM.dbo.PARAMETER  WHERE SYSTEM_ID='eservice_jd' and PARAMETER_CODE='MSG_PARAM_POLICY_NO')
           )
GO

INSERT INTO  ESERVICE_ADM.[dbo].[MESSAGING_PARAMETER]
           ([MESSAGING_TEMPLATE_ID]
           ,[PARAMETER_ID])
     VALUES
           ((select MESSAGING_TEMPLATE_ID  FROM   ESERVICE_ADM.dbo.[MESSAGING_TEMPLATE]  WHERE SYSTEM_ID='eservice_jd' and [MESSAGING_TEMPLATE_CODE]='ELIFE_JD_MAIL-001')
           ,(select PARAMETER_ID  FROM   ESERVICE_ADM.dbo.PARAMETER  WHERE SYSTEM_ID='eservice_jd' and PARAMETER_CODE='MSG_PARAM_APP_NAME')
           )
GO

INSERT INTO  ESERVICE_ADM.[dbo].[MESSAGING_PARAMETER]
           ([MESSAGING_TEMPLATE_ID]
           ,[PARAMETER_ID])
     VALUES
           ((select MESSAGING_TEMPLATE_ID  FROM   ESERVICE_ADM.dbo.[MESSAGING_TEMPLATE]  WHERE SYSTEM_ID='eservice_jd' and [MESSAGING_TEMPLATE_CODE]='ELIFE_JD_MAIL-001')
           ,(select PARAMETER_ID  FROM   ESERVICE_ADM.dbo.PARAMETER  WHERE SYSTEM_ID='eservice_jd' and PARAMETER_CODE='MSG_PARAM_INS_NAME')
           )
GO

INSERT INTO  ESERVICE_ADM.[dbo].[MESSAGING_PARAMETER]
           ([MESSAGING_TEMPLATE_ID]
           ,[PARAMETER_ID])
     VALUES
           ((select MESSAGING_TEMPLATE_ID  FROM   ESERVICE_ADM.dbo.[MESSAGING_TEMPLATE]  WHERE SYSTEM_ID='eservice_jd' and [MESSAGING_TEMPLATE_CODE]='ELIFE_JD_MAIL-001')
           ,(select PARAMETER_ID  FROM   ESERVICE_ADM.dbo.PARAMETER  WHERE SYSTEM_ID='eservice_jd' and PARAMETER_CODE='MSG_PARAM_DUE_DATE')
           )
GO

