CREATE DATABASE ESERVICE_JD
GO

USE [ESERVICE_JD]
GO

CREATE TABLE [ESERVICE_JD].[dbo].[USERS](
	[USER_ID] [nvarchar](50) NOT NULL,
	[USER_TYPE] [nvarchar](6) NULL,
	[ROC_ID] [nvarchar](10) NOT NULL,
	[MOBILE] [nvarchar](50) NULL,
	[EMAIL] [nvarchar](100) NULL,
	[LOGIN_FAIL_COUNT] [numeric](38, 4) NULL,
	[LAST_CHANG_PASSWORD_DATE] [datetime] NULL,
	[SMS_FLAG] [nvarchar](1) NULL,
	[MAIL_FLAG] [nvarchar](1) NULL,
	[FB_ID] [nvarchar](100) NULL,
	[MOICA_ID] [nvarchar](100) NULL,
	[CREATE_DATE] [datetime] NULL,
	[CREATE_USER] [nvarchar](50) NULL,
	[ONLINE_FLAG] [nvarchar](1) NULL,
	[STATUS] [nvarchar](10) NULL
) ON [PRIMARY]
GO

ALTER TABLE [ESERVICE_JD].[dbo].[USERS] ADD  CONSTRAINT [DF_USERS_STATUS]  DEFAULT (N'enable') FOR [STATUS]
GO

CREATE FUNCTION [dbo].[FN_DEBASE64]
	(@String NVARCHAR(512))
RETURNS NVARCHAR(512)
AS
BEGIN
    RETURN CAST(CAST(N'' AS XML).value('xs:base64Binary(sql:variable("@String"))', 'VARBINARY(MAX)') AS NVARCHAR(MAX))
END
GO

CREATE FUNCTION [dbo].[FN_ENBASE64]
	(@String NVARCHAR(512))
RETURNS NVARCHAR(512)
AS
BEGIN
	DECLARE @BinString VARBINARY(MAX)
	SET @BinString = CAST(@String AS VARBINARY(MAX))
	RETURN CAST(N'' AS XML).value('xs:base64Binary(xs:hexBinary(sql:variable("@BinString")))','NVARCHAR(512)')
END
GO

CREATE TABLE [ESERVICE_JD].[dbo].[DEPARTMENT](
    [DEP_ID] [nvarchar](50) NOT NULL,
    [DEP_NAME] [nvarchar](100) NOT NULL,
    [DESCRIPTION] [nvarchar](200) NULL,
    [PARENT_DEP] [nvarchar](50) NULL,
    [CREATE_USER] [nvarchar](50) NULL,
    [CREATE_DATE] [date] NULL,
    [MODIFY_USER] [nvarchar](50) NULL,
    [MODIFY_DATE] [date] NULL
    ) ON [PRIMARY]
GO

CREATE TABLE [ESERVICE_JD].[dbo].[MESSAGE](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[TITLE] [nvarchar](50) NOT NULL,
	[MSG] [nvarchar](100) NOT NULL,
	[STATUS] [numeric](38, 4) NOT NULL,
	[CREATE_DATE] [datetime] NULL,
	[USER_ID] [varchar](10) NOT NULL,
	[NOTIFY_TIME] [datetime] NOT NULL,
 CONSTRAINT [SYS_C0010047] PRIMARY KEY CLUSTERED
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [ESERVICE_JD].[dbo].[USER_DEPARTMENT](
	[USER_ID] [varchar](50) NOT NULL,
	[DEP_ID] [varchar](50) NOT NULL,
	[TITLE_ID] [varchar](50) NULL
) ON [PRIMARY]
GO

CREATE TABLE [ESERVICE_JD].[dbo].[ROLE_DEPARTMENT](
	[ROLE_ID] [varchar](50) NOT NULL,
	[DEP_ID] [varchar](50) NOT NULL,
) ON [PRIMARY]
GO
