insert ESERVICE_JD.dbo.[DEPARTMENT](
    DEP_ID,
    DEP_NAME,
    DESCRIPTION,
    PARENT_DEP,
    CREATE_USER,
    CREATE_DATE,
    MODIFY_USER,
    MODIFY_DATE
)values
('0', N'Root', '', '', 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](
    DEP_ID,
    DEP_NAME,
    DESCRIPTION,
    PARENT_DEP,
    CREATE_USER,
    CREATE_DATE,
    MODIFY_USER,
    MODIFY_DATE
)values
('30000', N'臺灣銀行國內營業單位', '', '0', 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'營業部', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'館前分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'臺南分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'臺中分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'高雄分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'基隆分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'中興新村分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'嘉義分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'新竹分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'彰化分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'屏東分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'花蓮分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'延平分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'中山分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'高雄加工出口區分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'宜蘭分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'臺東分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'澎湖分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'鳳山分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'桃園分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'板橋分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'新營分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'苗栗分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'豐原分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'斗六分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'南投分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'南門分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'公館分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'左營分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'北投分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'霧峰分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'金門分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'馬祖分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'安平分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'中壢分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'三重分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'頭份分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'前鎮分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'城中分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'民權分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'潭子分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'連城分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'員林分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'松江分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'鼓山分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'龍山分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'忠孝分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'信義分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'復興分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'三民分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'臺中港分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'羅東分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'埔里分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'岡山分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'新興分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'苓雅分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'松山分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'健行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'中和分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'太保分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'竹北分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'士林分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'新莊分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'大甲分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'新竹科學園區分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'樹林分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'新店分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'黎明分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'民生分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'永康分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'三多分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'臺北世貿中心分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'大安分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'華江分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'潮州分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'蘇澳分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'大雅分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'楠梓分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'臺中工業區分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'敦化分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'南港分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'和平分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'水湳分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'中崙分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'土城分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'桃園國際機場分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'大昌分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'五甲分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'博愛分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'中庄分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'平鎮分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'仁愛分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'南崁分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'圓山分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'五股分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'大里分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'安南分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'西屯分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'天母分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'鹿港分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'內壢分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'臺南科學園區分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'虎尾分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'淡水分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'內湖分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'嘉北分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'東港分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'汐止分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'梧棲分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'小港分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'中屏分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'群賢分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'北大路分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'文山分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'太平分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'德芳分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'建國分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'屏東農科園區分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'東桃園分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'蘆洲分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'高雄國際機場分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'永吉簡易型分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'東門簡易型分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'愛國簡易型分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'台電簡易型分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'北府簡易型分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'臺北港分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'臺中科學園區分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'高雄科學園區分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'東湖分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'高榮分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'南港軟體園區分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'龍潭分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'仁德分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'林口分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'木柵分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'臺南創新園區分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'武昌分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'臺北分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'金山分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'信安分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'劍潭分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'萬華分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'板新分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'新永和分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'南新莊分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'新明分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'六家分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'北臺中分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'嘉南分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'南都分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'北高雄分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'成功分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'北花蓮分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'新湖分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'五福分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'六甲頂分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'中都分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'臺北國際機場分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'新莊副都心分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'仁武分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'臺中國際機場分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'臺中精密園區分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values  ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]), N'亞矽創新分行', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺灣銀行國內營業單位'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]),N'臺銀人壽', '', '0', 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]),N'總公司', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺銀人壽'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]),N'台南分公司', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺銀人壽'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]),N'台中分公司', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺銀人壽'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]),N'高雄分公司', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺銀人壽'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]),N'嘉義分公司', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺銀人壽'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]),N'新竹分公司', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺銀人壽'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]),N'花蓮服務中心', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺銀人壽'), 'admin', GETDATE(), 'admin', GETDATE());
insert ESERVICE_JD.dbo.[DEPARTMENT](     DEP_ID,     DEP_NAME,     DESCRIPTION,     PARENT_DEP,     CREATE_USER,     CREATE_DATE,     MODIFY_USER,     MODIFY_DATE )values ((select Max(DEP_ID)+1 from ESERVICE_JD.dbo.[DEPARTMENT]),N'桃園分公司', '', (SELECT DEP_ID from ESERVICE_JD.dbo.[DEPARTMENT] WHERE DEP_NAME = N'臺銀人壽'), 'admin', GETDATE(), 'admin', GETDATE());
