USE ESERVICE_ADM
GO

INSERT INTO ESERVICE_ADM.DBO.ROLE_FUNC_AUTH(FUNCTION_ID, ROLE_ID, CREATE_USER, CREATE_DATE)
SELECT B.FUNCTION_ID, A.ROLE_ID,  'admin', SYSDATETIME()   FROM (SELECT ROLE_ID FROM ROLE A WHERE DIV_ROLE_ID IN ('CHANNEL_LEADER', 'BRANCH_LEADER', 'GENERAL_PERSONNEL', 'IC_PERSONNEL', 'ADMINISTRATOR')) A, (SELECT FUNCTION_ID FROM ESERVICE_ADM.DBO.FUNCTION_ITEM WHERE
FUNCTION_NAME IN ('經代支援系統',
'個人中心',
'客戶管理',
'保單進度及照會管理',
'送件列表',
'變更密碼',
'保單查詢',
'案件進度查詢') AND SYS_ID = 'eservice_jd') B
