USE ESERVICE_ADM
GO

INSERT INTO ROLE_FUNC_AUTH(FUNCTION_ID, ROLE_ID, CREATE_USER, CREATE_DATE)
SELECT FUNCTION_ID,(SELECT top 1 ROLE_ID FROM ROLE WHERE DIV_ROLE_ID = 'CHANNEL_LEADER'), 'admin', SYSDATETIME() FROM ESERVICE_ADM.DBO.FUNCTION_ITEM WHERE
FUNCTION_NAME IN ('經代支援系統',
'個人中心',
'客戶管理',
'保單進度及照會管理',
'個人案件列表',
'變更密碼',
'保單查詢',
'案件進度查詢') AND SYS_ID = 'eservice_jd'

INSERT INTO ROLE_FUNC_AUTH(FUNCTION_ID, ROLE_ID, CREATE_USER, CREATE_DATE)
SELECT FUNCTION_ID,(SELECT top 1 ROLE_ID FROM ROLE WHERE DIV_ROLE_ID = 'BRANCH_LEADER'), 'admin', SYSDATETIME() FROM ESERVICE_ADM.DBO.FUNCTION_ITEM WHERE
FUNCTION_NAME IN ('經代支援系統',
'個人中心',
'客戶管理',
'保單進度及照會管理',
'個人案件列表',
'變更密碼',
'保單查詢',
'案件進度查詢') AND SYS_ID = 'eservice_jd'

INSERT INTO ROLE_FUNC_AUTH(FUNCTION_ID, ROLE_ID, CREATE_USER, CREATE_DATE)
SELECT FUNCTION_ID,(SELECT top 1 ROLE_ID FROM ROLE WHERE DIV_ROLE_ID = 'GENERAL_PERSONNEL'), 'admin', SYSDATETIME() FROM ESERVICE_ADM.DBO.FUNCTION_ITEM WHERE
FUNCTION_NAME IN ('經代支援系統',
'個人中心',
'客戶管理',
'保單進度及照會管理',
'個人案件列表',
'變更密碼',
'保單查詢',
'案件進度查詢') AND SYS_ID = 'eservice_jd'

INSERT INTO ROLE_FUNC_AUTH(FUNCTION_ID, ROLE_ID, CREATE_USER, CREATE_DATE)
SELECT FUNCTION_ID,(SELECT top 1 ROLE_ID FROM ROLE WHERE DIV_ROLE_ID = 'IC_PERSONNEL'), 'admin', SYSDATETIME() FROM ESERVICE_ADM.DBO.FUNCTION_ITEM WHERE
FUNCTION_NAME IN ('經代支援系統',
'個人中心',
'客戶管理',
'保單進度及照會管理',
'個人案件列表',
'變更密碼',
'保單查詢',
'案件進度查詢') AND SYS_ID = 'eservice_jd'

INSERT INTO ROLE_FUNC_AUTH(FUNCTION_ID, ROLE_ID, CREATE_USER, CREATE_DATE)
SELECT FUNCTION_ID,(SELECT top 1 ROLE_ID FROM ROLE WHERE DIV_ROLE_ID = 'ADMINISTRATOR'), 'admin', SYSDATETIME() FROM ESERVICE_ADM.DBO.FUNCTION_ITEM WHERE
FUNCTION_NAME IN ('經代支援系統',
'個人中心',
'客戶管理',
'保單進度及照會管理',
'個人案件列表',
'變更密碼',
'保單查詢',
'案件進度查詢') AND SYS_ID = 'eservice_jd'