-- 已持有投資標的轉換
INSERT ESERVICE_ADM.dbo.PARAMETER_CATEGORY (PARAMETER_CATEGORY_ID, SYSTEM_ID, CATEGORY_CODE, CATEGORY_NAME, STATUS, CREATE_DATE, CREATE_USER)
VALUES ((select max(PARAMETER_CATEGORY_ID)+1 from ESERVICE_ADM.dbo.PARAMETER_CATEGORY), 'eservice', 'INVESTMENT_TRANSFORMATION', N'已持有投資標的轉換條款', 1, getdate(), 'admin')
go

		--- 已持有投資標的轉換[備註]條款
INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'INVESTMENT_TRANSFORMATION_REMARKS', N' 已持有投資標的轉換備註條款信息',
		N'1、未來保費投資標的申請如於當日15:00提出申請則視為當日申請，逾時則視為次一工作日申請。<br/>
          2、相同標的不得同時申請投資標的部分提領及投資標的轉換。<br/>
          3、申請『投資標的轉換』之保單，如果仍有已申請但未完成的交易項目，須待前一交易完成後方可提出。<br/>
          4、各投資標的之配置比例必須為10的倍數且總和需為 100%。<br/>
          5、本保單投資標的總數以10 個為上限，每次交易最多得同時選擇10個投資標的做為未來繳入保費的投資配置項目。<br/>
          6、已持有標的轉換後，如未來保費投資標的也要轉換時，則必須再做未來保費投資配置變更。<br/>
          7、新約定投資標的之風險屬性須符合要保人最新風險屬性等級，如前次所作風險屬性等級評估已達1年以上，須重新評估要保人之風險屬性等級，並作為日後變更投資標的申請之依據。<br/>
          8、如新約定投資標的非屬保守型，且距前次所作風險屬性等級評估已達1年以上，須重新評估要保人之風險屬性等級，並作為日後變更投資標的申請之依據。<br/>
          9、您於指定投資標的前，應充分瞭解下列以投資高收益債券為訴求之基金之特有風險：(1)信用風險：由於高收益債券之信用評等未達投資等級或未經信用評等，可能面臨債券發行機構違約不支付本金、利息或破產之風險。(2)利率風險：由於債券易受利率之變動而影響其價格，故可能因利率上升導致債券價格下跌，而蒙受虧損之風險，高收益債亦然。(3)流動性風險：高收益債券可能因市場交易不活絡而造成流動性下降，而有無法在短期內依合理價格出售的風險。(4)如要保人指定以高收益債券為訴求之基金為投資標的者，不宜占其投資組合過高之比重，且不適合無法承擔相關風險之要保人。(5)若高收益債券基金為配息型，基金的配息可能由基金 的收益或本金中支付。任何涉及由本金支出的部分，可能導致原始投資金額減損。部分基金進行配息前未先扣除行政管理相關費用。(6)高收益債券基金可能投資美國144A債券（境內基金投資比例最高可達基金總資產30%；境外基金不限），該債券屬私募性質，易發生流動性不足，財務訊息揭露不完整或價格不透明導致高波動性之風險。<br/>',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='INVESTMENT_TRANSFORMATION'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go
	--- 已持有投資標的轉換[同意]條款
INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'INVESTMENT_TRANSFORMATION_CONSENT', N' 已持有投資標的轉換[同意條款]條款信息',
		N'<iframe src="pdf/terms/臺銀人壽外幣投資標的批註條款-0G_c.pdf" width="100%" height="100%"></iframe>',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='INVESTMENT_TRANSFORMATION'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go

	--- 已持有投資標的[比例]條款
INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'INVESTMENT_TRANSFORMATION_PROPORTION', N' 已持有投資標的轉換[比例備註]條款信息',
		N'1、未來保費投資標的申請如於當日15:00提出申請則視為當日申請，逾時則視為次一工作日申請。<br/>
          2、相同標的不得同時申請投資標的部分提領及投資標的轉換。<br/>
          3、申請『投資標的轉換』之保單，如果仍有已申請但未完成的交易項目，須待前一交易完成後方可提出。<br/>
          4、各投資標的之配置比例必須為10的倍數且總和需為 100%。<br/>
          5、本保單投資標的總數以10 個為上限，每次交易最多得同時選擇10個投資標的做為未來繳入保費的投資配置項目。<br/>
          6、已持有標的轉換後，如未來保費投資標的也要轉換時，則必須再做未來保費投資配置變更。<br/>
          7、新約定投資標的之風險屬性須符合要保人最新風險屬性等級，如前次所作風險屬性等級評估已達1年以上，須重新評估要保人之風險屬性等級，並作為日後變更投資標的申請之依據。<br/>
          8、若您的投資風險屬性為保守型，您可選擇保守型的基金RR1~RR2。<br/>
          9、若您的投資風險屬性為穩健型，您可選擇保守型及穩健型的基金RR1~RR4。<br/>
          10、若您的投資風險屬性為積極型型，您可選擇保守型、穩健型及積極型型的基金RR1~RR5。<br/>',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='INVESTMENT_TRANSFORMATION'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go

-- 未來保費投資標的與分配比例
INSERT ESERVICE_ADM.dbo.PARAMETER_CATEGORY (PARAMETER_CATEGORY_ID, SYSTEM_ID, CATEGORY_CODE, CATEGORY_NAME, STATUS, CREATE_DATE, CREATE_USER)
VALUES ((select max(PARAMETER_CATEGORY_ID)+1 from ESERVICE_ADM.dbo.PARAMETER_CATEGORY), 'eservice', 'INVESTMENT_DISTRIBUTION', N'未來保費投資標的與分配比例條款', 1, getdate(), 'admin')
go

		---未來保費投資標的與分配比例[備註]條款
INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'INVESTMENT_DISTRIBUTION_REMARKS', N' 未來保費投資標的與分配比例備註條款信息',
		N'<li>1、未來保費投資標的申請如於當日15:00提出申請則視為當日申請，逾時則視為次一工作日申請。</li>
         <li>2、各投資標的之配置比例必須為10的倍數且總和需為 100%。</li>
         <li>3、本保單投資標的總數以10 個為上限，每次交易最多得同時選擇10個投資標的做為未來繳入保費的投資配置項目。</li>
         <li>4、若尚有未投資淨保險費時，保費投資標的種類及比例變更經本公司受理後即進入投資標的交易作業流程，故本公司受理後即不再接受撤銷或中途變更。</li>
         <li>5、新約定投資標的之風險屬性須符合要保人最新風險屬性等級，如前次所作風險屬性等級評估已達1年以上，須重新評估要保人之風險屬性等級，並作為日後變更投
            資標的申請之依據。</li>
         <li>6、如新約定投資標的非屬保守型，且距前次所作風險屬性等級評估已達1年以上，須重新評估要保人之風險屬性等級，並作為日後變更投資標的申請之依據。
            您於指定投資標的前，應充分瞭解下列以投資高收益債券為訴求之基金之特有風險：(1)信用風險：由於高收益債券之信用評等未達投資等級或未經信用評等，可能
            面臨債券發行機構違約不支付本金、利息或破產之風險。(2)利率風險：由於債券易受利率之變動而影響其價格，故可能因利率上升導致債券價格下跌，而蒙受虧損
         	   之風險，高收益債亦然。(3)流動性風險：高收益債券可能因市場交易不活絡而造成流動性下降，而有無法在短期內依合理價格出售的風險。(4)如要保人指定以高收
         	   益債券為訴求之基金為投資標的者，不宜占其投資組合過高之比重，且不適合無法承擔相關風險之要保人。(5)若高收益債券基金為配息型，基金的配息可能由基金
         	   的收益或本金中支付。任何涉及由本金支出的部分，可能導致原始投資金額減損。部分基金進行配息前未先扣除行政管理相關費用。(6)高收益債券基金可能投資美
         	   國144A債券（境內基金投資比例最高可達基金總資產30%；境外基金不限），該債券屬私募性質，易發生流動性不足，財務訊息揭露不完整或價格不透明導致高
         	   波動性之風險</li>',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='INVESTMENT_DISTRIBUTION'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go
	--- 未來保費投資標的與分配比例[同意]條款
INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'INVESTMENT_DISTRIBUTION_CONSENT', N'未來保費投資標的與分配比例[同意條款]條款信息',
		N'<iframe src="pdf/terms/臺銀人壽外幣投資標的批註條款-0G_c.pdf" width="100%" height="100%"></iframe>',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='INVESTMENT_DISTRIBUTION'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'INVESTMENT_DISTRIBUTION_URI', N'未來保費投資標的與分配比例-我要瞭解基金內容',
		N'http://10.7.168.94/webex/investmentnetvalue/main/',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='INVESTMENT_DISTRIBUTION'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'INVESTMENT_LIMIT', N'未來保費投資標的與分配比例-數量',
		N'10',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='INVESTMENT_DISTRIBUTION'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go

--- 變更風險屬性-風險屬性分析表
INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'RISK_ATTRIBUTE_ANALYSIS_STATEMENT', N'變更風險屬性-風險屬性分析表',
		N'<div class="check-title">風險屬性分析表</div> <div class="check-body grey2"> <div class="plus-list"> <div class="col-sm-2 text-left">總 分</div> <div class="col-sm-2 text-left">投資組合類型</div> <div class="col-sm-8 text-left">風險屬性說明</div> </div> <div class="check-list inlineBlock"> <div class="col-sm-2">10 分以下</div> <div class="col-sm-2"><p class="orange chMiddle">保守型</p><p>(A)</p></div> <div class="col-sm-8">您的投資態度偏向保守，可承擔的投資風險亦較低，建議選擇風險較低或能提供 穩定收益的投資工具，如債券、貨幣型基金等較為安全。</div> </div> <div class="check-list inlineBlock"> <div class="col-sm-2">11~20 分</div> <div class="col-sm-2"><p class="orange chMiddle">穩健型</p><p>(B)</p></div> <div class="col-sm-8">您希望自己的資產可以穩定成長，所以願意承擔適度的風險去賺取適度的報酬。 投資的重點應注意適度分散，以成長型基金為主，收益型基金為輔，並避免投資 過度集中。 </div> </div> <div class="check-list inlineBlock"> <div class="col-sm-2">20 分以上</div> <div class="col-sm-2"><p class="orange chMiddle">積極型</p><p>(C)</p></div> <div class="col-sm-8">您希望自己的資產可以穩定成長，所以願意承擔適度的風險去賺取適度的報酬。 投資的重點應注意適度分散，以成長型基金為主，收益型基金為輔，並避免投資 過度集中。 </div> </div> </div>',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='INVESTMENT_DISTRIBUTION'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go

		---未來保費投資標的與分配比例[備註]
INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'INVESTMENT_DISTRIBUTION_REMARK1', N' 未來保費投資標的與分配比例備註',
		N'1、未來保費投資標的申請如於當日15:00提出申請則視為當日申請，逾時則視為次一工作日申請。</br>
         2、各投資標的之配置比例必須為10的倍數且總和需為 100%。</br>
         3、本保單投資標的總數以10 個為上限，每次交易最多得同時選擇10個投資標的做為未來繳入保費的投資配置項目。</br>
         4、若尚有未投資淨保險費時，保費投資標的種類及比例變更經本公司受理後即進入投資標的交易作業流程，故本公司受理後即不再接受撤銷或中途變更。</br>
         5、新約定投資標的之風險屬性須符合要保人最新風險屬性等級，如前次所作風險屬性等級評估已達1年以上，須重新評估要保人之風險屬性等級，並作為日後變更投</br>
            資標的申請之依據。</br>
         6、若您的投資風險屬性為保守型，您可選擇保守型的基金RR1~RR2。</br>
         7、若您的投資風險屬性為穩健型，您可選擇保守型及穩健型的基金RR1~RR4。</br>
         8、若您的投資風險屬性為積極型型，您可選擇保守型、穩健型及積極型型的基金RR1~RR5。</br>',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='INVESTMENT_DISTRIBUTION'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go

---未來保費投資標的與分配比例
INSERT ESERVICE_ADM.dbo.PARAMETER
    (
	PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER
	)
VALUES
   (
   (select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER)
	, N'eservice'
	, N'INVESTMENT'
	, N'未來保費投資標的與分配比例'
	, N'INVESTMENT'
	, (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='ONLINE_CHANGE')
	, NULL
	, NULL
	, 1
	, NULL
	, NULL
	, getdate()
	, N'system'
	, NULL
	, NULL
	)
go
---已持有投資標的轉換

INSERT ESERVICE_ADM.dbo.PARAMETER
    (
	PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER
	)
VALUES
   (
   (select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER)
	, N'eservice'
	, N'CONVERSION'
	, N'已持有投資標的轉換'
	, N'CONVERSION'
	, (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='ONLINE_CHANGE')
	, NULL
	, NULL
	, 1
	, NULL
	, NULL
	, getdate()
	, N'system'
	, NULL
	, NULL
	)
go

--投資標,限制投資比例大小值組
INSERT ESERVICE_ADM.dbo.PARAMETER_CATEGORY (PARAMETER_CATEGORY_ID, SYSTEM_ID, CATEGORY_CODE, CATEGORY_NAME, STATUS, CREATE_DATE, CREATE_USER)
VALUES ((select max(PARAMETER_CATEGORY_ID)+1 from ESERVICE_ADM.dbo.PARAMETER_CATEGORY), 'eservice', 'INVESTMENT_LIMIT_RATIO', N'投資標,限制投資比例大小值組', 1, getdate(), 'admin')
go

		--- 投資標,限制投資比例大小值 ('UC','UH','UR','UQ','UP','US','UU')
INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'UC_MIN', N'UC保單投資大小限制',
		N'10',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='INVESTMENT_LIMIT_RATIO'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go
INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'UC_MAX', N'UC保單投資大小限制',
		N'100',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='INVESTMENT_LIMIT_RATIO'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go
INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'UH_MIN', N'UH保單投資大小限制',
		N'10',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='INVESTMENT_LIMIT_RATIO'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go
INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'UH_MAX', N'UH保單投資大小限制',
		N'100',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='INVESTMENT_LIMIT_RATIO'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go
INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'UR_MIN', N'UR保單投資大小限制',
		N'10',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='INVESTMENT_LIMIT_RATIO'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go
INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'UR_MAX', N'UR保單投資大小限制',
		N'100',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='INVESTMENT_LIMIT_RATIO'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'UQ_MIN', N'UQ保單投資大小限制',
		N'10',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='INVESTMENT_LIMIT_RATIO'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go
INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'UQ_MAX', N'UQ保單投資大小限制',
		N'100',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='INVESTMENT_LIMIT_RATIO'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go
INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'UP_MIN', N'UP保單投資大小限制',
		N'10',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='INVESTMENT_LIMIT_RATIO'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go
INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'UP_MAX', N'UP保單投資大小限制',
		N'100',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='INVESTMENT_LIMIT_RATIO'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go
INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'US_MIN', N'US保單投資大小限制',
		N'10',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='INVESTMENT_LIMIT_RATIO'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go
INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'US_MAX', N'US保單投資大小限制',
		N'100',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='INVESTMENT_LIMIT_RATIO'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go
INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'UU_MIN', N'UU保單投資大小限制',
		N'10',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='INVESTMENT_LIMIT_RATIO'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go
INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'UU_MAX', N'UU保單投資大小限制',
		N'100',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='INVESTMENT_LIMIT_RATIO'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go




		--- 臺幣  欲轉出基金與比例,限制比例小值
INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'NTD_PROPORTION_MIN', N'臺幣欲轉出基金與比例,限制比例小值',
		N'10',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='INVESTMENT_LIMIT_RATIO'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go


		---美元   欲轉出基金與比例,限制比例小值
INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'USD_PROPORTION_MIN', N'美元欲轉出基金與比例,限制比例小值',
		N'10',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='INVESTMENT_LIMIT_RATIO'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go

		--- 臺幣  欲轉出基金單位,限制比例-此項是為金額,單位后台計算
INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'NTD_UNIT_MIN', N'臺幣欲轉出基金單位,限制比例-此項是為金額,單位后台計算',
		N'500',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='INVESTMENT_LIMIT_RATIO'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go


		---美元  欲轉出基金單位,限制比例-此項是為金額,單位后台計算
INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'USD_UNIT_MIN', N'美元欲轉出基金單位,限制比例-此項是為金額,單位后台計算',
		N'100',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='INVESTMENT_LIMIT_RATIO'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go


INSERT ESERVICE_ADM.dbo.PARAMETER
    (
	PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER
	)
VALUES
   (
   (select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER)
	, N'eservice'
	, N'DEPOSIT'
	, N'保單提領(贖回)'
	, N'DEPOSIT'
	, (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='ONLINE_CHANGE')
	, NULL
	, NULL
	, 1
	, NULL
	, NULL
	, getdate()
	, N'system'
	, NULL
	, NULL
	)
go

-- 設定停損停利通知
INSERT ESERVICE_ADM.dbo.PARAMETER_CATEGORY (PARAMETER_CATEGORY_ID, SYSTEM_ID, CATEGORY_CODE, CATEGORY_NAME, STATUS, CREATE_DATE, CREATE_USER)
VALUES ((select max(PARAMETER_CATEGORY_ID)+1 from ESERVICE_ADM.dbo.PARAMETER_CATEGORY), 'eservice', 'NOTIFICATION', N'設定停損停利通知', 1, getdate(), 'admin')
go

--設定停損停利通知[備註]
INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'NOTIFICATION_REMARK1', N'設定停損停利通知',
		N'<li>若您的投資風險屬性為保守型，您可選擇保守型的基金RR1~RR2。</li>
          <li>若您的投資風險屬性為穩健型，您可選擇保守型及穩健型的基金RR1~RR4。</li>
          <li>若您的投資風險屬性為積極型型，您可選擇保守型、穩健型及積極型型的基金RR1~RR5。</li>
          <li>為確保保險商品符合您的投資能力及風險性，投資風險屬性若有變更，本公司將以您最新的風險屬性作為名下所有保單日後變更的評估依據。</li>',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='NOTIFICATION'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go

INSERT ESERVICE_ADM.dbo.PARAMETER
    (
	PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER
	)
VALUES
   (
   (select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER)
	, N'eservice'
	, N'CASH_PAYMENT'
	, N'收益分配或撥回資產分配方式'
	, N'CASH_PAYMENT'
	, (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='ONLINE_CHANGE')
	, NULL
	, NULL
	, 1
	, NULL
	, NULL
	, getdate()
	, N'system'
	, NULL
	, NULL
	)
go

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ( (SELECT MAX(PARAMETER_ID)+1 FROM  ESERVICE_ADM.dbo.PARAMETER ), N'eservice', N'WORDING_INVESTMENT_001', N'未來保費投資標的與分配比例', N'可新增或移除投資標的', (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE = 'PAGE_WORDING'), 0, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL);

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ( (SELECT MAX(PARAMETER_ID)+1 FROM  ESERVICE_ADM.dbo.PARAMETER ), N'eservice', N'WORDING_INVESTMENT_002', N'已持有投資標的轉換', N'可直接不同基金單位轉換', (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE = 'PAGE_WORDING'), 0, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL);

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ( (SELECT MAX(PARAMETER_ID)+1 FROM  ESERVICE_ADM.dbo.PARAMETER ), N'eservice', N'WORDING_INVESTMENT_003', N'保單提領(贖回)', N'可執行保單提領贖回', (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE = 'PAGE_WORDING'), 0, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL);

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ( (SELECT MAX(PARAMETER_ID)+1 FROM  ESERVICE_ADM.dbo.PARAMETER ), N'eservice', N'WORDING_INVESTMENT_004', N'收益分配或撥回資產分配方式', N'設定給付方式', (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE = 'PAGE_WORDING'), 0, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL);

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ( (SELECT MAX(PARAMETER_ID)+1 FROM  ESERVICE_ADM.dbo.PARAMETER ), N'eservice', N'WORDING_INVESTMENT_005', N'變更風險屬性', N'可變更個人投資風險屬性', (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE = 'PAGE_WORDING'), 0, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL);

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ( (SELECT MAX(PARAMETER_ID)+1 FROM  ESERVICE_ADM.dbo.PARAMETER ), N'eservice', N'WORDING_INVESTMENT_006', N'定期定額保費變更', N'彈性保費', (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE = 'PAGE_WORDING'), 0, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL);

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ( (SELECT MAX(PARAMETER_ID)+1 FROM  ESERVICE_ADM.dbo.PARAMETER ), N'eservice', N'WORDING_INVESTMENT_007', N'設定停利停損通知', N'申請內容的相關說明', (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE = 'PAGE_WORDING'), 0, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL);
go

-- 風險投資校驗
INSERT ESERVICE_ADM.dbo.PARAMETER_CATEGORY (PARAMETER_CATEGORY_ID, SYSTEM_ID, CATEGORY_CODE, CATEGORY_NAME, STATUS, CREATE_DATE, CREATE_USER)
VALUES ((select max(PARAMETER_CATEGORY_ID)+1 from ESERVICE_ADM.dbo.PARAMETER_CATEGORY), 'eservice', 'INVESTMENT_CHECK_LIST', N'風險投資校驗', 1, getdate(), 'admin')

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ( (SELECT MAX(PARAMETER_ID)+1 FROM  ESERVICE_ADM.dbo.PARAMETER ), N'eservice', N'PROCESS_INVESTMENT_LIST', N'投資進行中類型', N'INVESTMENT,CONVERSION,DEPOSIT,FUND_NOTIFICATION,CASH_PAYMENT,RISK_LEVEL,CHANGE_PREMIUM', (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE = 'INVESTMENT_CHECK_LIST'), 0, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL);
go

---給管理人員的內容模板配置數據
-- 添加投資型首家件通知管理人員 MESSAGING_TEMPLATE条件
---【管理人員】
INSERT INTO  ESERVICE_ADM.[dbo].[MESSAGING_TEMPLATE]([MESSAGING_TEMPLATE_ID],[SYSTEM_ID],[MESSAGING_TEMPLATE_CODE],[MESSAGING_TEMPLATE_NAME],[STATUS],[TRIGGER_TYPE],[EVENT_TYPE],[SEND_TYPE],[SEND_TIME],[CIRCLE_TYPE],[CIRCLE_VALUE],[RECEIVER_MODE],[MESSAGING_SUBJECT],[MESSAGING_CONTENT],[CREATE_DATE],[CREATE_USER],[UPDATE_DATE],[UPDATE_USER])
VALUES((select max([MESSAGING_TEMPLATE_ID])+1 from ESERVICE_ADM.dbo.MESSAGING_TEMPLATE),N'eservice',N'ELIFE_MAIL_027',N'投資型首家件通知管理人員MAIL模版 ',3,N'api ',NULL,N'email',NULL,NULL,NULL,N'dynamic',N'投資型首家件通知管理人員內容',N'申請日期 : ${DATA}<br/>申請功能 :${APPLICATION_FUNCTION}<br/>申請狀態 : ${TransStatus}<br/>申請序號 :${TransNum}<br/>保單號碼 :${POLICY_NO}<br/>', getdate(),N'admin',getdate(),N'admin')
GO

INSERT ESERVICE_ADM.dbo.MESSAGING_PARAMETER (MESSAGING_TEMPLATE_ID,PARAMETER_ID) VALUES ((select MESSAGING_TEMPLATE_ID from ESERVICE_ADM.dbo.MESSAGING_TEMPLATE where MESSAGING_TEMPLATE_CODE = 'ELIFE_MAIL_027'),
		(select PARAMETER_ID from   ESERVICE_ADM.dbo.PARAMETER  where  PARAMETER_CODE='MSG_PARAM_DATA'));
GO

INSERT ESERVICE_ADM.dbo.MESSAGING_PARAMETER (MESSAGING_TEMPLATE_ID,PARAMETER_ID) VALUES ((select MESSAGING_TEMPLATE_ID from ESERVICE_ADM.dbo.MESSAGING_TEMPLATE where MESSAGING_TEMPLATE_CODE = 'ELIFE_MAIL_027'),
		(select PARAMETER_ID from   ESERVICE_ADM.dbo.PARAMETER  where  PARAMETER_CODE='MSG_PARAM_APPLICATION_FUNCTION'));
GO
INSERT ESERVICE_ADM.dbo.MESSAGING_PARAMETER (MESSAGING_TEMPLATE_ID,PARAMETER_ID) VALUES ((select MESSAGING_TEMPLATE_ID from ESERVICE_ADM.dbo.MESSAGING_TEMPLATE where MESSAGING_TEMPLATE_CODE = 'ELIFE_MAIL_027'),
		(select PARAMETER_ID from   ESERVICE_ADM.dbo.PARAMETER  where  PARAMETER_CODE='MSG_PARAM_TransStatus'));
GO
INSERT ESERVICE_ADM.dbo.MESSAGING_PARAMETER (MESSAGING_TEMPLATE_ID,PARAMETER_ID) VALUES ((select MESSAGING_TEMPLATE_ID from ESERVICE_ADM.dbo.MESSAGING_TEMPLATE where MESSAGING_TEMPLATE_CODE = 'ELIFE_MAIL_027'),
		(select PARAMETER_ID from   ESERVICE_ADM.dbo.PARAMETER  where  PARAMETER_CODE='MSG_PARAM_TransNum'));
GO
INSERT ESERVICE_ADM.dbo.MESSAGING_PARAMETER (MESSAGING_TEMPLATE_ID,PARAMETER_ID) VALUES ((select MESSAGING_TEMPLATE_ID from ESERVICE_ADM.dbo.MESSAGING_TEMPLATE where MESSAGING_TEMPLATE_CODE = 'ELIFE_MAIL_027'),
		(select PARAMETER_ID from   ESERVICE_ADM.dbo.PARAMETER  where  PARAMETER_CODE='MSG_PARAM_POLICY_NO'));
GO
--申請送出成功後給【管理】PARAMETER
INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'MSG_PARAM_APPLICATION_FUNCTION', N'通信模版參數-保單申請功能', N'APPLICATION_FUNCTION', (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='MessagingParameter'), NULL, NULL, 1, N'N', NULL, getdate(), N'admin', getdate(), N'admin')
go

--保戶前台線上申請送出成功後給【保戶】PARAMETER
INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'MSG_PARAM_TITLE', N'通信模版參數-保單標題', N'TITLE', (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='MessagingParameter'), NULL, NULL, 1, N'N', NULL, getdate(), N'admin', getdate(), N'admin')
go
--保戶前台線上申請送出成功後給【保戶】PARAMETER
INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'MSG_PARAM_MESSAGE', N'通信模版參數-保單消息', N'MESSAGE', (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='MessagingParameter'), NULL, NULL, 1, N'N', NULL, getdate(), N'admin', getdate(), N'admin')
go

---【保戶人員】
INSERT INTO  ESERVICE_ADM.[dbo].[MESSAGING_TEMPLATE]([MESSAGING_TEMPLATE_ID],[SYSTEM_ID],[MESSAGING_TEMPLATE_CODE],[MESSAGING_TEMPLATE_NAME],[STATUS],[TRIGGER_TYPE],[EVENT_TYPE],[SEND_TYPE],[SEND_TIME],[CIRCLE_TYPE],[CIRCLE_VALUE],[RECEIVER_MODE],[MESSAGING_SUBJECT],[MESSAGING_CONTENT],[CREATE_DATE],[CREATE_USER],[UPDATE_DATE],[UPDATE_USER])
VALUES((select max([MESSAGING_TEMPLATE_ID])+1 from ESERVICE_ADM.dbo.MESSAGING_TEMPLATE),N'eservice',N'ELIFE_MAIL_028',N'臺銀人壽投資型保單變更申請通知MAIL模版 ',3,N'api ',NULL,N'email',NULL,NULL,NULL,N'dynamic',N'臺銀人壽投資型保單變更申請通知',N'臺銀人壽投資型保單${TITLE}<br/>親愛的臺銀人壽保戶您好:${MESSAGE}<br/>如有疑問，請先至臺銀人壽會員專區查詢或請電洽:<br/>免費客服電話0800-011966<br/>市話服務:02-27849151轉保全科<br/>', getdate(),N'admin',getdate(),N'admin')
GO

INSERT ESERVICE_ADM.dbo.MESSAGING_PARAMETER (MESSAGING_TEMPLATE_ID,PARAMETER_ID) VALUES ((select MESSAGING_TEMPLATE_ID from ESERVICE_ADM.dbo.MESSAGING_TEMPLATE where MESSAGING_TEMPLATE_CODE = 'ELIFE_MAIL_028'),
		(select PARAMETER_ID from   ESERVICE_ADM.dbo.PARAMETER  where  PARAMETER_CODE='MSG_PARAM_TITLE'));
GO

INSERT ESERVICE_ADM.dbo.MESSAGING_PARAMETER (MESSAGING_TEMPLATE_ID,PARAMETER_ID) VALUES ((select MESSAGING_TEMPLATE_ID from ESERVICE_ADM.dbo.MESSAGING_TEMPLATE where MESSAGING_TEMPLATE_CODE = 'ELIFE_MAIL_028'),
		(select PARAMETER_ID from   ESERVICE_ADM.dbo.PARAMETER  where  PARAMETER_CODE='MSG_PARAM_MESSAGE'));
GO

INSERT ESERVICE_ADM.dbo.PARAMETER_CATEGORY (PARAMETER_CATEGORY_ID, SYSTEM_ID, CATEGORY_CODE, CATEGORY_NAME, STATUS, CREATE_DATE, CREATE_USER)
VALUES ((select max(PARAMETER_CATEGORY_ID)+1 from ESERVICE_ADM.dbo.PARAMETER_CATEGORY), 'eservice', 'DEPOSIT_PARAMETER_CATEGORY', N'保單提領(贖回)校驗', 1, getdate(), 'admin')

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'DEPOSIT_US_NTD_MIN_VALUE', N'US臺幣轉出金額',
		N'5000',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='DEPOSIT_PARAMETER_CATEGORY'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'DEPOSIT_US_NTD_SURPLUS_VALUE', N'US臺幣剩餘金額',
		N'10000',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='DEPOSIT_PARAMETER_CATEGORY'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'DEPOSIT_UU_USD_MIN_VALUE', N'UU美金轉出金額',
		N'150',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='DEPOSIT_PARAMETER_CATEGORY'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'DEPOSIT_UU_USD_SURPLUS_VALUE', N'UU美金剩餘金額',
		N'300',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='DEPOSIT_PARAMETER_CATEGORY'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'DEPOSIT_POST_SHOW', N'UC,UH',
		N'UC,UH',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='DEPOSIT_PARAMETER_CATEGORY'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'DEPOSIT_US_CURRENCY_ACCOUNT', N'RTNTD00420',
		N'RTNTD00420',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='DEPOSIT_PARAMETER_CATEGORY'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'DEPOSIT_UU_CURRENCY_ACCOUNT', N'RTUSD00430',
		N'RTUSD00430',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='DEPOSIT_PARAMETER_CATEGORY'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'DEPOSIT_US_STOP_ACCOUNT', N'RTNTD00430',
		N'RTNTD00430',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='DEPOSIT_PARAMETER_CATEGORY'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'DEPOSIT_UU_STOP_ACCOUNT', N'RTUSD00440',
		N'RTUSD00440',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='DEPOSIT_PARAMETER_CATEGORY'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'DISTRIBUTION_DEPOSIT_FUND_ERR_MSG', N'保單提領分配異常消息',
		N'請改採「自定投資標的比例」來設定提領金額!',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='DEPOSIT_PARAMETER_CATEGORY'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go

--- Questions and Options

INSERT [ESERVICE].[dbo].[OPTIONS] ([QUESTION_ID], [ITEM], [SEQ], [SCORE], [CREATE_TIME], [UPDATE_TIME]) VALUES (CAST(1 AS Numeric(18, 0)), N'A. 71歲以上', CAST(1 AS Numeric(3, 0)), CAST(0 AS Numeric(18, 0)), NULL, NULL)
INSERT [ESERVICE].[dbo].[OPTIONS] ([QUESTION_ID], [ITEM], [SEQ], [SCORE], [CREATE_TIME], [UPDATE_TIME]) VALUES (CAST(1 AS Numeric(18, 0)), N'B. 51歲以上~70歲', CAST(2 AS Numeric(3, 0)), CAST(1 AS Numeric(18, 0)), NULL, NULL)
INSERT [ESERVICE].[dbo].[OPTIONS] ([QUESTION_ID], [ITEM], [SEQ], [SCORE], [CREATE_TIME], [UPDATE_TIME]) VALUES (CAST(1 AS Numeric(18, 0)), N'C. 40歲以上~50歲', CAST(3 AS Numeric(3, 0)), CAST(2 AS Numeric(18, 0)), NULL, NULL)
INSERT [ESERVICE].[dbo].[OPTIONS] ([QUESTION_ID], [ITEM], [SEQ], [SCORE], [CREATE_TIME], [UPDATE_TIME]) VALUES (CAST(1 AS Numeric(18, 0)), N'D. 40歲以下', CAST(4 AS Numeric(3, 0)), CAST(3 AS Numeric(18, 0)), NULL, NULL)
INSERT [ESERVICE].[dbo].[OPTIONS] ([QUESTION_ID], [ITEM], [SEQ], [SCORE], [CREATE_TIME], [UPDATE_TIME]) VALUES (CAST(2 AS Numeric(18, 0)), N'A. 定存、傳統型保險商品', CAST(5 AS Numeric(3, 0)), CAST(0 AS Numeric(18, 0)), NULL, NULL)
INSERT [ESERVICE].[dbo].[OPTIONS] ([QUESTION_ID], [ITEM], [SEQ], [SCORE], [CREATE_TIME], [UPDATE_TIME]) VALUES (CAST(2 AS Numeric(18, 0)), N'B. 股票、債券、基金', CAST(6 AS Numeric(3, 0)), CAST(1 AS Numeric(18, 0)), NULL, NULL)
INSERT [ESERVICE].[dbo].[OPTIONS] ([QUESTION_ID], [ITEM], [SEQ], [SCORE], [CREATE_TIME], [UPDATE_TIME]) VALUES (CAST(2 AS Numeric(18, 0)), N'C. 結構型債券、期貨、選擇權或其他衍生性金融商品', CAST(7 AS Numeric(3, 0)), CAST(2 AS Numeric(18, 0)), NULL, NULL)
INSERT [ESERVICE].[dbo].[OPTIONS] ([QUESTION_ID], [ITEM], [SEQ], [SCORE], [CREATE_TIME], [UPDATE_TIME]) VALUES (CAST(3 AS Numeric(18, 0)), N'A. 未滿3個月', CAST(8 AS Numeric(3, 0)), CAST(0 AS Numeric(18, 0)), NULL, NULL)
INSERT [ESERVICE].[dbo].[OPTIONS] ([QUESTION_ID], [ITEM], [SEQ], [SCORE], [CREATE_TIME], [UPDATE_TIME]) VALUES (CAST(3 AS Numeric(18, 0)), N'B. 3個月以上~未滿3年', CAST(9 AS Numeric(3, 0)), CAST(1 AS Numeric(18, 0)), NULL, NULL)
INSERT [ESERVICE].[dbo].[OPTIONS] ([QUESTION_ID], [ITEM], [SEQ], [SCORE], [CREATE_TIME], [UPDATE_TIME]) VALUES ( CAST(3 AS Numeric(18, 0)), N'C. 3年以上', CAST(10 AS Numeric(3, 0)), CAST(2 AS Numeric(18, 0)), NULL, NULL)
INSERT [ESERVICE].[dbo].[OPTIONS] ([QUESTION_ID], [ITEM], [SEQ], [SCORE], [CREATE_TIME], [UPDATE_TIME]) VALUES ( CAST(4 AS Numeric(18, 0)), N'A. 0%', CAST(11 AS Numeric(3, 0)), CAST(0 AS Numeric(18, 0)), NULL, NULL)
INSERT [ESERVICE].[dbo].[OPTIONS] ([QUESTION_ID], [ITEM], [SEQ], [SCORE], [CREATE_TIME], [UPDATE_TIME]) VALUES ( CAST(4 AS Numeric(18, 0)), N'B.未滿25%　', CAST(12 AS Numeric(3, 0)), CAST(1 AS Numeric(18, 0)), NULL, NULL)
INSERT [ESERVICE].[dbo].[OPTIONS] ([QUESTION_ID], [ITEM], [SEQ], [SCORE], [CREATE_TIME], [UPDATE_TIME]) VALUES ( CAST(4 AS Numeric(18, 0)), N'C.25%以上〜未滿50%', CAST(13 AS Numeric(3, 0)), CAST(2 AS Numeric(18, 0)), NULL, NULL)
INSERT [ESERVICE].[dbo].[OPTIONS] ([QUESTION_ID], [ITEM], [SEQ], [SCORE], [CREATE_TIME], [UPDATE_TIME]) VALUES ( CAST(4 AS Numeric(18, 0)), N'D. 50%以上', CAST(14 AS Numeric(3, 0)), CAST(3 AS Numeric(18, 0)), NULL, NULL)
INSERT [ESERVICE].[dbo].[OPTIONS] ([QUESTION_ID], [ITEM], [SEQ], [SCORE], [CREATE_TIME], [UPDATE_TIME]) VALUES ( CAST(5 AS Numeric(18, 0)), N'A. 只可承受獲利，不能接受損失 【若選擇本選項，不論總分為何，均屬於「不適合購買投資型保單」】', CAST(15 AS Numeric(3, 0)), CAST(0 AS Numeric(18, 0)), NULL, NULL)
INSERT [ESERVICE].[dbo].[OPTIONS] ([QUESTION_ID], [ITEM], [SEQ], [SCORE], [CREATE_TIME], [UPDATE_TIME]) VALUES ( CAST(5 AS Numeric(18, 0)), N'B. 可能獲利5%，可能損失5%', CAST(16 AS Numeric(3, 0)), CAST(1 AS Numeric(18, 0)), NULL, NULL)
INSERT [ESERVICE].[dbo].[OPTIONS] ([QUESTION_ID], [ITEM], [SEQ], [SCORE], [CREATE_TIME], [UPDATE_TIME]) VALUES ( CAST(5 AS Numeric(18, 0)), N'C. 可能獲利10%，可能損失10%', CAST(17 AS Numeric(3, 0)), CAST(2 AS Numeric(18, 0)), NULL, NULL)
INSERT [ESERVICE].[dbo].[OPTIONS] ([QUESTION_ID], [ITEM], [SEQ], [SCORE], [CREATE_TIME], [UPDATE_TIME]) VALUES ( CAST(5 AS Numeric(18, 0)), N'D. 可能獲利15%，可能損失15%', CAST(18 AS Numeric(3, 0)), CAST(3 AS Numeric(18, 0)), NULL, NULL)
INSERT [ESERVICE].[dbo].[OPTIONS] ([QUESTION_ID], [ITEM], [SEQ], [SCORE], [CREATE_TIME], [UPDATE_TIME]) VALUES ( CAST(6 AS Numeric(18, 0)), N'A. 無', CAST(19 AS Numeric(3, 0)), CAST(0 AS Numeric(18, 0)), NULL, NULL)
INSERT [ESERVICE].[dbo].[OPTIONS] ([QUESTION_ID], [ITEM], [SEQ], [SCORE], [CREATE_TIME], [UPDATE_TIME]) VALUES ( CAST(6 AS Numeric(18, 0)), N'B. 未滿3小時', CAST(20 AS Numeric(3, 0)), CAST(1 AS Numeric(18, 0)), NULL, NULL)
INSERT [ESERVICE].[dbo].[OPTIONS] ([QUESTION_ID], [ITEM], [SEQ], [SCORE], [CREATE_TIME], [UPDATE_TIME]) VALUES ( CAST(6 AS Numeric(18, 0)), N'C. 3小時以上~未滿9小時', CAST(21 AS Numeric(3, 0)), CAST(2 AS Numeric(18, 0)), NULL, NULL)
INSERT [ESERVICE].[dbo].[OPTIONS] ([QUESTION_ID], [ITEM], [SEQ], [SCORE], [CREATE_TIME], [UPDATE_TIME]) VALUES ( CAST(6 AS Numeric(18, 0)), N'D. 9小時以上', CAST(22 AS Numeric(3, 0)), CAST(3 AS Numeric(18, 0)), NULL, NULL)
INSERT [ESERVICE].[dbo].[OPTIONS] ([QUESTION_ID], [ITEM], [SEQ], [SCORE], [CREATE_TIME], [UPDATE_TIME]) VALUES ( CAST(7 AS Numeric(18, 0)), N'A. 虧損未達6個月時就考慮賣掉', CAST(23 AS Numeric(3, 0)), CAST(0 AS Numeric(18, 0)), NULL, NULL)
INSERT [ESERVICE].[dbo].[OPTIONS] ([QUESTION_ID], [ITEM], [SEQ], [SCORE], [CREATE_TIME], [UPDATE_TIME]) VALUES ( CAST(7 AS Numeric(18, 0)), N'B. 虧損已經6個月以上才考慮進行調整', CAST(24 AS Numeric(3, 0)), CAST(1 AS Numeric(18, 0)), NULL, NULL)
INSERT [ESERVICE].[dbo].[OPTIONS] ([QUESTION_ID], [ITEM], [SEQ], [SCORE], [CREATE_TIME], [UPDATE_TIME]) VALUES ( CAST(7 AS Numeric(18, 0)), N'C. 持有1年以上，因長期投資才是致勝關鍵', CAST(25 AS Numeric(3, 0)), CAST(2 AS Numeric(18, 0)), NULL, NULL)
INSERT [ESERVICE].[dbo].[OPTIONS] ([QUESTION_ID], [ITEM], [SEQ], [SCORE], [CREATE_TIME], [UPDATE_TIME]) VALUES ( CAST(8 AS Numeric(18, 0)), N'A. 避免資產的損失', CAST(26 AS Numeric(3, 0)), CAST(0 AS Numeric(18, 0)), NULL, NULL)
INSERT [ESERVICE].[dbo].[OPTIONS] ([QUESTION_ID], [ITEM], [SEQ], [SCORE], [CREATE_TIME], [UPDATE_TIME]) VALUES ( CAST(8 AS Numeric(18, 0)), N'B. 資產穩健的成長', CAST(27 AS Numeric(3, 0)), CAST(1 AS Numeric(18, 0)), NULL, NULL)
INSERT [ESERVICE].[dbo].[OPTIONS] ([QUESTION_ID], [ITEM], [SEQ], [SCORE], [CREATE_TIME], [UPDATE_TIME]) VALUES ( CAST(8 AS Numeric(18, 0)), N'C. 資產迅速的成長', CAST(28 AS Numeric(3, 0)), CAST(2 AS Numeric(18, 0)), NULL, NULL)
INSERT [ESERVICE].[dbo].[OPTIONS] ([QUESTION_ID], [ITEM], [SEQ], [SCORE], [CREATE_TIME], [UPDATE_TIME]) VALUES ( CAST(9 AS Numeric(18, 0)), N'A. 影響程度大', CAST(29 AS Numeric(3, 0)), CAST(0 AS Numeric(18, 0)), NULL, NULL)
INSERT [ESERVICE].[dbo].[OPTIONS] ([QUESTION_ID], [ITEM], [SEQ], [SCORE], [CREATE_TIME], [UPDATE_TIME]) VALUES ( CAST(9 AS Numeric(18, 0)), N'B. 影響程度中', CAST(30 AS Numeric(3, 0)), CAST(1 AS Numeric(18, 0)), NULL, NULL)
INSERT [ESERVICE].[dbo].[OPTIONS] ([QUESTION_ID], [ITEM], [SEQ], [SCORE], [CREATE_TIME], [UPDATE_TIME]) VALUES ( CAST(9 AS Numeric(18, 0)), N'C. 影響程度小', CAST(31 AS Numeric(3, 0)), CAST(2 AS Numeric(18, 0)), NULL, NULL)
INSERT [ESERVICE].[dbo].[OPTIONS] ([QUESTION_ID], [ITEM], [SEQ], [SCORE], [CREATE_TIME], [UPDATE_TIME]) VALUES ( CAST(9 AS Numeric(18, 0)), N'D. 沒有影響', CAST(32 AS Numeric(3, 0)), CAST(3 AS Numeric(18, 0)), NULL, NULL)

INSERT [ESERVICE].[dbo].[QUESTION] ([ID], [QUESTION], [TITLE], [IS_MULTI], [SEQ], [EFFECTIVE_TIME], [STOP_TIME]) VALUES (next value for ESERVICE.dbo.QUESTION_SEQUENCE, N'1. 您目前的年齡', NULL, N'N', CAST(1 AS Numeric(3, 0)), getdate(), '2099-12-30')
INSERT [ESERVICE].[dbo].[QUESTION] ([ID], [QUESTION], [TITLE], [IS_MULTI], [SEQ], [EFFECTIVE_TIME], [STOP_TIME]) VALUES (next value for ESERVICE.dbo.QUESTION_SEQUENCE, N'2. 投資經驗（A）：【可複選，但以分數較高者計分】', NULL, N'Y', CAST(2 AS Numeric(3, 0)), getdate(), '2099-12-30')
INSERT [ESERVICE].[dbo].[QUESTION] ([ID], [QUESTION], [TITLE], [IS_MULTI], [SEQ], [EFFECTIVE_TIME], [STOP_TIME]) VALUES (next value for ESERVICE.dbo.QUESTION_SEQUENCE, N'3. 投資經驗（B）：【問項2為0分時，本問項一律為0分】', NULL, N'N', CAST(3 AS Numeric(3, 0)), getdate(), '2099-12-30')
INSERT [ESERVICE].[dbo].[QUESTION] ([ID], [QUESTION], [TITLE], [IS_MULTI], [SEQ], [EFFECTIVE_TIME], [STOP_TIME]) VALUES (next value for ESERVICE.dbo.QUESTION_SEQUENCE, N'4. 目前所投資具價值波動性的理財工具(如股票、基金、選擇權等)佔總資產的百分比為', NULL, N'N', CAST(4 AS Numeric(3, 0)), getdate(), '2099-12-30')
INSERT [ESERVICE].[dbo].[QUESTION] ([ID], [QUESTION], [TITLE], [IS_MULTI], [SEQ], [EFFECTIVE_TIME], [STOP_TIME]) VALUES (next value for ESERVICE.dbo.QUESTION_SEQUENCE, N'5. 您期望年投資報酬率及所能承受年投資風險為(包含價格與匯率波動)', NULL, N'N', CAST(5 AS Numeric(3, 0)), getdate(), '2099-12-30')
INSERT [ESERVICE].[dbo].[QUESTION] ([ID], [QUESTION], [TITLE], [IS_MULTI], [SEQ], [EFFECTIVE_TIME], [STOP_TIME]) VALUES (next value for ESERVICE.dbo.QUESTION_SEQUENCE, N'6. 您每月花多少時間吸收財經資訊', NULL, N'N', CAST(6 AS Numeric(3, 0)), getdate(), '2099-12-30')
INSERT [ESERVICE].[dbo].[QUESTION] ([ID], [QUESTION], [TITLE], [IS_MULTI], [SEQ], [EFFECTIVE_TIME], [STOP_TIME]) VALUES (next value for ESERVICE.dbo.QUESTION_SEQUENCE, N'7. 投資因市場波動使得有所虧損時，可能採取哪一項處理方式', NULL, N'N', CAST(7 AS Numeric(3, 0)), getdate(), '2099-12-30')
INSERT [ESERVICE].[dbo].[QUESTION] ([ID], [QUESTION], [TITLE], [IS_MULTI], [SEQ], [EFFECTIVE_TIME], [STOP_TIME]) VALUES (next value for ESERVICE.dbo.QUESTION_SEQUENCE, N'8. 您購買投資型保險商品想達成的財務目標', NULL, N'N', CAST(8 AS Numeric(3, 0)), getdate(), '2099-12-30')
INSERT [ESERVICE].[dbo].[QUESTION] ([ID], [QUESTION], [TITLE], [IS_MULTI], [SEQ], [EFFECTIVE_TIME], [STOP_TIME]) VALUES (next value for ESERVICE.dbo.QUESTION_SEQUENCE, N'9. 如您持有之整體投資資產下跌超過15%，請問對您的生活影響程 度為何', NULL, N'N', CAST(9 AS Numeric(3, 0)), getdate(), '2099-12-30')
go

INSERT ESERVICE_ADM.dbo.PARAMETER_CATEGORY (PARAMETER_CATEGORY_ID, SYSTEM_ID, CATEGORY_CODE, CATEGORY_NAME, STATUS, CREATE_DATE, CREATE_USER)
VALUES ((select max(PARAMETER_CATEGORY_ID)+1 from ESERVICE_ADM.dbo.PARAMETER_CATEGORY), 'eservice', 'INVESTMENT_TYPES', N'投資標類型', 1, getdate(), 'admin')
go

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'INVESTMENT_INVESTMENT_TYPE', N'未來保費投資標的與分配比例類型',
		N'UU,US',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='INVESTMENT_TYPES'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'CONVERSION_INVESTMENT_TYPE', N'已持有投資標的轉換類型',
		N'UU,US',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='INVESTMENT_TYPES'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'CASH_PAYMENT_INVESTMENT_TYPE', N'收益分配或撥回資產分配方式類型',
		N'US',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='INVESTMENT_TYPES'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'CHANGE_PREMIUM_INVESTMENT_TYPE', N'定期超額保費類型',
		N'UU,US',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='INVESTMENT_TYPES'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'FUND_NOTIFICATION_INVESTMENT_TYPE', N'設定停利停損通知類型',
		N'UU,US',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='INVESTMENT_TYPES'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'DEPOSIT_INVESTMENT_TYPE', N'保單提領(贖回)類型',
		N'UU,US',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='INVESTMENT_TYPES'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go

INSERT ESERVICE_ADM.dbo.PARAMETER
    (
	PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER
	)
VALUES
   (
   (select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER)
	, N'eservice'
	, N'CHANGE_PREMIUM'
	, N'定期超額保費'
	, N'CHANGE_PREMIUM'
	, (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='ONLINE_CHANGE')
	, NULL
	, NULL
	, 1
	, NULL
	, NULL
	, getdate()
	, N'system'
	, NULL
	, NULL
	)
go

INSERT ESERVICE_ADM.dbo.PARAMETER_CATEGORY (PARAMETER_CATEGORY_ID, SYSTEM_ID, CATEGORY_CODE, CATEGORY_NAME, STATUS, CREATE_DATE, CREATE_USER)
VALUES ((select max(PARAMETER_CATEGORY_ID)+1 from ESERVICE_ADM.dbo.PARAMETER_CATEGORY), 'eservice', 'RISK_LEVEL_TO_RR', N'風險屬性轉換基金等級', 1, getdate(), 'admin')
go

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'RISK_LEVEL_TO_RR_A', N'保守型',
		N'RR1,RR2',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='RISK_LEVEL_TO_RR'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'RISK_LEVEL_TO_RR_B', N'穩健型',
		N'RR1,RR2,RR3,RR4',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='RISK_LEVEL_TO_RR'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'RISK_LEVEL_TO_RR_C', N'積極型',
		N'RR1,RR2,RR3,RR4,RR5',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='RISK_LEVEL_TO_RR'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go

INSERT ESERVICE_ADM.dbo.PARAMETER_CATEGORY (PARAMETER_CATEGORY_ID, SYSTEM_ID, CATEGORY_CODE, CATEGORY_NAME, STATUS, CREATE_DATE, CREATE_USER)
VALUES ((select max(PARAMETER_CATEGORY_ID)+1 from ESERVICE_ADM.dbo.PARAMETER_CATEGORY), 'eservice', 'RISK_SCORE_TO_LEVEL', N'風險評分轉風險等級', 1, getdate(), 'admin')
go

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'RISK_SCORE_TO_LEVEL_A_MIN', N'A',
		N'0',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='RISK_SCORE_TO_LEVEL'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'RISK_SCORE_TO_LEVEL_A_MAX', N'A',
		N'10',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='RISK_SCORE_TO_LEVEL'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'RISK_SCORE_TO_LEVEL_B_MIN', N'B',
		N'10',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='RISK_SCORE_TO_LEVEL'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'RISK_SCORE_TO_LEVEL_B_MAX', N'B',
		N'20',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='RISK_SCORE_TO_LEVEL'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'RISK_SCORE_TO_LEVEL_C_MIN', N'C',
		N'20',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='RISK_SCORE_TO_LEVEL'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go

--- FUND_NOTIFICATION MESSAGE
INSERT INTO  ESERVICE_ADM.[dbo].[MESSAGING_TEMPLATE]([MESSAGING_TEMPLATE_ID],[SYSTEM_ID],[MESSAGING_TEMPLATE_CODE],[MESSAGING_TEMPLATE_NAME],[STATUS],[TRIGGER_TYPE],[EVENT_TYPE],[SEND_TYPE],[SEND_TIME],[CIRCLE_TYPE],[CIRCLE_VALUE],[RECEIVER_MODE],[MESSAGING_SUBJECT],[MESSAGING_CONTENT],[CREATE_DATE],[CREATE_USER],[UPDATE_DATE],[UPDATE_USER])
VALUES((select max([MESSAGING_TEMPLATE_ID])+1 from ESERVICE_ADM.dbo.MESSAGING_TEMPLATE),N'eservice',N'ELIFE_MAIL_FN',N'停利停損MAIL模版 ',3,N'api ',NULL,N'email',NULL,NULL,NULL,N'dynamic',N'停利停損內容',N'臺銀人壽投資型保單已達停利停損設定通知<br/> 親愛的臺銀人壽保戶您好: 本公司通知您所設定的投資型保單停利停損通知已達您的指定上下限值條件如下， 如有疑問，請先至臺銀人壽會員專區查詢或請電洽: 免費客服電話0800-011966 市話服務:02-27849151轉保全科<br/>${FUND_NOTIFICATION_DATA}', getdate(),N'admin',getdate(),N'admin')
GO

INSERT INTO [ESERVICE_ADM].[dbo].[MESSAGING_TEMPLATE_TMP] SELECT * FROM ESERVICE_ADM.dbo.[MESSAGING_TEMPLATE] WHERE MESSAGING_TEMPLATE_CODE = 'ELIFE_MAIL_FN'

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'MSG_FUND_NOTIFICATION_DATA', N'停利停損通知DATA', N'FUND_NOTIFICATION_DATA', (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='MessagingParameter'), NULL, NULL, 1, N'N', NULL, getdate(), N'admin', getdate(), N'admin')
go

INSERT ESERVICE_ADM.dbo.MESSAGING_PARAMETER (MESSAGING_TEMPLATE_ID,PARAMETER_ID) VALUES ((select MESSAGING_TEMPLATE_ID from ESERVICE_ADM.dbo.MESSAGING_TEMPLATE where MESSAGING_TEMPLATE_CODE = 'ELIFE_MAIL_FN'),
		(select PARAMETER_ID from   ESERVICE_ADM.dbo.PARAMETER  where  PARAMETER_CODE='MSG_FUND_NOTIFICATION_DATA'));
GO

INSERT INTO ESERVICE_ADM.[dbo].[MESSAGING_PARAMETER_TMP] SELECT * FROM ESERVICE_ADM.dbo.MESSAGING_PARAMETER WHERE MESSAGING_TEMPLATE_ID IN ((select MESSAGING_TEMPLATE_ID from ESERVICE_ADM.dbo.MESSAGING_TEMPLATE where MESSAGING_TEMPLATE_CODE = 'ELIFE_MAIL_FN'))
GO

UPDATE ESERVICE_ADM.[dbo].PARAMETER SET PARAMETER_VALUE = CONCAT(PARAMETER_VALUE, '&031:T') WHERE PARAMETER_CODE = 'TRANS_OK_CODE'
UPDATE ESERVICE_ADM.[dbo].PARAMETER SET PARAMETER_VALUE = CONCAT(PARAMETER_VALUE, '&033:T') WHERE PARAMETER_CODE = 'TRANS_OK_CODE'
UPDATE ESERVICE_ADM.[dbo].PARAMETER SET PARAMETER_VALUE = CONCAT(PARAMETER_VALUE, '&032:T') WHERE PARAMETER_CODE = 'TRANS_OK_CODE'
UPDATE ESERVICE_ADM.[dbo].PARAMETER SET PARAMETER_VALUE = CONCAT(PARAMETER_VALUE, '&030:T') WHERE PARAMETER_CODE = 'TRANS_OK_CODE'
UPDATE ESERVICE_ADM.[dbo].PARAMETER SET PARAMETER_VALUE = CONCAT(PARAMETER_VALUE, '&029:T') WHERE PARAMETER_CODE = 'TRANS_OK_CODE'
UPDATE ESERVICE_ADM.[dbo].PARAMETER SET PARAMETER_VALUE = CONCAT(PARAMETER_VALUE, '&028:T') WHERE PARAMETER_CODE = 'TRANS_OK_CODE'
UPDATE ESERVICE_ADM.[dbo].PARAMETER SET PARAMETER_VALUE = CONCAT(PARAMETER_VALUE, '&034:T') WHERE PARAMETER_CODE = 'TRANS_OK_CODE'
go

--- 投資損益模塊顯示
INSERT ESERVICE_ADM.dbo.PARAMETER_CATEGORY (PARAMETER_CATEGORY_ID, SYSTEM_ID, CATEGORY_CODE, CATEGORY_NAME, STATUS, CREATE_DATE, CREATE_USER)
VALUES ((select max(PARAMETER_CATEGORY_ID)+1 from ESERVICE_ADM.dbo.PARAMETER_CATEGORY), 'eservice', 'LISTING_MAP_TEMPLATE', N'投資損益模塊顯示', 1, getdate(), 'admin')
go

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'LISTING_MAP_TEMPLATE_UP', N' UP-frontstage/listing2-1模板',
		N'frontstage/listing2-1',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='LISTING_MAP_TEMPLATE'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'LISTING_MAP_TEMPLATE_UQ', N' UQ-frontstage/listing2-1模板',
		N'frontstage/listing2-1',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='LISTING_MAP_TEMPLATE'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'LISTING_MAP_TEMPLATE_UR', N' UR-frontstage/listing2-1模板',
		N'frontstage/listing2-1',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='LISTING_MAP_TEMPLATE'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'LISTING_MAP_TEMPLATE_UC', N' UC-frontstage/listing2-2模板',
		N'frontstage/listing2-2',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='LISTING_MAP_TEMPLATE'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'LISTING_MAP_TEMPLATE_UH', N' UH-frontstage/listing2-2模板',
		N'frontstage/listing2-2',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='LISTING_MAP_TEMPLATE'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'LISTING_MAP_TEMPLATE_US', N' US-frontstage/listing2-2模板',
		N'frontstage/listing2-2',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='LISTING_MAP_TEMPLATE'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'LISTING_MAP_TEMPLATE_UU', N' UU-frontstage/listing2-2模板',
		N'frontstage/listing2-2',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='LISTING_MAP_TEMPLATE'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go

--- 繳別-投資型保單類型
INSERT ESERVICE_ADM.dbo.PARAMETER_CATEGORY (PARAMETER_CATEGORY_ID, SYSTEM_ID, CATEGORY_CODE, CATEGORY_NAME, STATUS, CREATE_DATE, CREATE_USER)
VALUES ((select max(PARAMETER_CATEGORY_ID)+1 from ESERVICE_ADM.dbo.PARAMETER_CATEGORY), 'eservice', 'PAYMODE_INVESTMENT', N'繳別-投資型保單類型', 1, getdate(), 'admin')
go

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'PAYMODE_INVESTMENT_TYPE', N'UU,US保單變更月繳',
		N'UU,US',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='PAYMODE_INVESTMENT'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'PAYMODE_UU_MIN', N'UU_MIN_VALUE',
		N'2000',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='PAYMODE_INVESTMENT'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'PAYMODE_US_MIN', N'US_MIN_VALUE',
		N'2000',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='PAYMODE_INVESTMENT'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'PAYMODE_UP_MIN', N'UP_MIN_VALUE',
		N'2000',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='PAYMODE_INVESTMENT'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'PAYMODE_UQ_MIN', N'UQ_MIN_VALUE',
		N'2000',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='PAYMODE_INVESTMENT'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'PAYMODE_UR_MIN', N'UR_MIN_VALUE',
		N'2000',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='PAYMODE_INVESTMENT'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'PAYMODE_UC_MIN', N'UC_MIN_VALUE',
		N'2000',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='PAYMODE_INVESTMENT'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'PAYMODE_UH_MIN', N'UH_MIN_VALUE',
		N'2000',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='PAYMODE_INVESTMENT'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go

--- 定期超額保費-投資型保單類型
INSERT ESERVICE_ADM.dbo.PARAMETER_CATEGORY (PARAMETER_CATEGORY_ID, SYSTEM_ID, CATEGORY_CODE, CATEGORY_NAME, STATUS, CREATE_DATE, CREATE_USER)
VALUES ((select max(PARAMETER_CATEGORY_ID)+1 from ESERVICE_ADM.dbo.PARAMETER_CATEGORY), 'eservice', 'CHANGE_PREMIUM_INVESTMENT', N'定期超額保費-投資型保單類型', 1, getdate(), 'admin')
go

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'CHANGE_PREMIUM_UU_MIN', N'UU_MIN_VALUE',
		N'2000',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='CHANGE_PREMIUM_INVESTMENT'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'CHANGE_PREMIUM_US_MIN', N'US_MIN_VALUE',
		N'2000',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='CHANGE_PREMIUM_INVESTMENT'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'CHANGE_PREMIUM_UP_MIN', N'UP_MIN_VALUE',
		N'2000',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='CHANGE_PREMIUM_INVESTMENT'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'CHANGE_PREMIUM_UQ_MIN', N'UQ_MIN_VALUE',
		N'2000',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='CHANGE_PREMIUM_INVESTMENT'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'CHANGE_PREMIUM_UR_MIN', N'UR_MIN_VALUE',
		N'2000',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='CHANGE_PREMIUM_INVESTMENT'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'CHANGE_PREMIUM_UC_MIN', N'UC_MIN_VALUE',
		N'2000',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='CHANGE_PREMIUM_INVESTMENT'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'CHANGE_PREMIUM_UH_MIN', N'UH_MIN_VALUE',
		N'2000',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='CHANGE_PREMIUM_INVESTMENT'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go
