-- 已持有投資標的轉換
INSERT ESERVICE_ADM.dbo.PARAMETER_CATEGORY (PARAMETER_CATEGORY_ID, SYSTEM_ID, CATEGORY_CODE, CATEGORY_NAME, STATUS, CREATE_DATE, CREATE_USER)
VALUES ((select max(PARAMETER_CATEGORY_ID)+1 from ESERVICE_ADM.dbo.PARAMETER_CATEGORY), 'eservice', 'INVESTMENT_TRANSFORMATION', N'已持有投資標的轉換條款', 1, getdate(), 'admin')
go

		--- 已持有投資標的轉換[備註]條款
INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'INVESTMENT_TRANSFORMATION_REMARKS', N' 已持有投資標的轉換備註條款信息',
		N'	變額萬能壽險保單：如於15:00前提出申請，則視當日為申請之生效日，逾時則視次一工作日為申請之生效日。<br/>
			此次變更將於下一期應繳保費生效，續期保費將依照本次指定之標的的項目及百分比投資。<br/>
			每一投資標的投資比例不得低於10%，加總需等於100%。<br/>
			目前僅開放“要保人與被保險人為同一人”之保單於網路變更保單資料。<br/>',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='INVESTMENT_TRANSFORMATION'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go
	--- 已持有投資標的轉換[同意]條款
INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'INVESTMENT_TRANSFORMATION_CONSENT', N' 已持有投資標的轉換[同意條款]條款信息',
		N'<iframe src="pdf/terms/臺銀人壽外幣投資標的批註條款-0G_c.pdf" width="100%" height="100%"></iframe>',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='INVESTMENT_TRANSFORMATION'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go

	--- 已持有投資標的[比例]條款
INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'INVESTMENT_TRANSFORMATION_PROPORTION', N' 已持有投資標的轉換[比例備註]條款信息',
		N'若您的投資風險屬性為保守型，您可選擇保守型的基金RR1~RR2。<br/>
		 若您的投資風險屬性為穩健型，您可選擇保守型及穩健型的基金RR1~RR4。<br/>
		 若您的投資風險屬性為積極型型，您可選擇保守型、穩健型及積極型型的基金RR1~RR5。<br/>
		 為確保保險商品符合您的投資能力及風險性，投資風險屬性若有變更，本公司將以您最新的風險屬性作為名下所有保單日後變更的評估依據。<br/>',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='INVESTMENT_TRANSFORMATION'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go

-- 未來保費投資標的與分配比例
INSERT ESERVICE_ADM.dbo.PARAMETER_CATEGORY (PARAMETER_CATEGORY_ID, SYSTEM_ID, CATEGORY_CODE, CATEGORY_NAME, STATUS, CREATE_DATE, CREATE_USER)
VALUES ((select max(PARAMETER_CATEGORY_ID)+1 from ESERVICE_ADM.dbo.PARAMETER_CATEGORY), 'eservice', 'INVESTMENT_DISTRIBUTION', N'未來保費投資標的與分配比例條款', 1, getdate(), 'admin')
go

		---未來保費投資標的與分配比例[備註]條款
INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'INVESTMENT_DISTRIBUTION_REMARKS', N' 未來保費投資標的與分配比例備註條款信息',
		N' <li> 變額萬能壽險保單：如於15:00前提出申請，則是當日為申請生效日，遇時則視為次一工作日為申請之生效日。</li>
          <li>此次變更將於下一期應繳保費日生效，續期保費將依照本次指定之標的項目及百分比投資</li>
          <li>目前僅開放要保人與被保險人為同一人之保單於網路變更保單資料。</li>
          <li>若您的投資風險屬性為保守型，您可選擇保守型的基金RR1~RR2</li>
          <li>若您的投資風險屬性為穩健型，您可選擇穩健型的基金RR1~RR4</li>
          <li>若您的投資風險屬性為穩健型，您可選擇穩健型的基金RR1~RR5</li>
          <li>為確保保險商品符合您的投資能力及風險屬性，投資風險屬性若有變更，本公司將以您最新風險屬性作為名下所有保單日後變更的評估依據</li> ',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='INVESTMENT_DISTRIBUTION'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go
	--- 未來保費投資標的與分配比例[同意]條款
INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'INVESTMENT_DISTRIBUTION_CONSENT', N' 未來保費投資標的與分配比例[同意條款]條款信息',
		N'<iframe src="pdf/terms/臺銀人壽外幣投資標的批註條款-0G_c.pdf" width="100%" height="100%"></iframe>',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='INVESTMENT_DISTRIBUTION'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go

--- 變更風險屬性-風險屬性分析表
INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'RISK_ATTRIBUTE_ANALYSIS_STATEMENT', N'變更風險屬性-風險屬性分析表',
		N'<div class="check-title">風險屬性分析表</div> <div class="check-body grey2"> <div class="plus-list"> <div class="col-sm-2 text-left">總 分</div> <div class="col-sm-2 text-left">投資組合類型</div> <div class="col-sm-8 text-left">風險屬性說明</div> </div> <div class="check-list inlineBlock"> <div class="col-sm-2">10 分以下</div> <div class="col-sm-2"><p class="orange chMiddle">保守型</p><p>(A)</p></div> <div class="col-sm-8">您的投資態度偏向保守，可承擔的投資風險亦較低，建議選擇風險較低或能提供 穩定收益的投資工具，如債券、貨幣型基金等較為安全。</div> </div> <div class="check-list inlineBlock"> <div class="col-sm-2">11~20 分</div> <div class="col-sm-2"><p class="orange chMiddle">穩健型</p><p>(B)</p></div> <div class="col-sm-8">您希望自己的資產可以穩定成長，所以願意承擔適度的風險去賺取適度的報酬。 投資的重點應注意適度分散，以成長型基金為主，收益型基金為輔，並避免投資 過度集中。 </div> </div> <div class="check-list inlineBlock"> <div class="col-sm-2">20 分以上</div> <div class="col-sm-2"><p class="orange chMiddle">積極型</p><p>(C)</p></div> <div class="col-sm-8">您希望自己的資產可以穩定成長，所以願意承擔適度的風險去賺取適度的報酬。 投資的重點應注意適度分散，以成長型基金為主，收益型基金為輔，並避免投資 過度集中。 </div> </div> </div>',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='INVESTMENT_DISTRIBUTION'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go

		---未來保費投資標的與分配比例[備註]
INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'INVESTMENT_DISTRIBUTION_REMARK1', N' 未來保費投資標的與分配比例備註',
		N'<li>若您的投資風險屬性為保守型，您可選擇保守型的基金RR1~RR2。</li>
          <li>若您的投資風險屬性為穩健型，您可選擇保守型及穩健型的基金RR1~RR4。</li>
          <li>若您的投資風險屬性為積極型型，您可選擇保守型、穩健型及積極型型的基金RR1~RR5。</li>
          <li>為確保保險商品符合您的投資能力及風險性，投資風險屬性若有變更，本公司將以您最新的風險屬性作為名下所有保單日後變更的評估依據。</li>',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='INVESTMENT_DISTRIBUTION'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go

---未來保費投資標的與分配比例
INSERT ESERVICE_ADM.dbo.PARAMETER
    (
	PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER
	)
VALUES
   (
   (select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER)
	, N'eservice'
	, N'INVESTMENT'
	, N'未來保費投資標的與分配比例'
	, N'INVESTMENT'
	, (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='ONLINE_CHANGE')
	, NULL
	, NULL
	, 1
	, NULL
	, NULL
	, getdate()
	, N'system'
	, NULL
	, NULL
	)
go
---已持有投資標的轉換

INSERT ESERVICE_ADM.dbo.PARAMETER
    (
	PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER
	)
VALUES
   (
   (select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER)
	, N'eservice'
	, N'CONVERSION'
	, N'已持有投資標的轉換'
	, N'CONVERSION'
	, (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='ONLINE_CHANGE')
	, NULL
	, NULL
	, 1
	, NULL
	, NULL
	, getdate()
	, N'system'
	, NULL
	, NULL
	)
go

--投資標,限制投資比例大小值組
INSERT ESERVICE_ADM.dbo.PARAMETER_CATEGORY (PARAMETER_CATEGORY_ID, SYSTEM_ID, CATEGORY_CODE, CATEGORY_NAME, STATUS, CREATE_DATE, CREATE_USER)
VALUES ((select max(PARAMETER_CATEGORY_ID)+1 from ESERVICE_ADM.dbo.PARAMETER_CATEGORY), 'eservice', 'INVESTMENT_LIMIT_RATIO', N'投資標,限制投資比例大小值組', 1, getdate(), 'admin')
go

		--- 投資標,限制投資比例大小值 ('UC','UH','UR','UQ','UP','US','UU')
INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'UC_MIN', N'UC保單投資大小限制',
		N'10',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='INVESTMENT_LIMIT_RATIO'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go
INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'UC_MAX', N'UC保單投資大小限制',
		N'100',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='INVESTMENT_LIMIT_RATIO'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go
INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'UH_MIN', N'UH保單投資大小限制',
		N'10',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='INVESTMENT_LIMIT_RATIO'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go
INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'UH_MAX', N'UH保單投資大小限制',
		N'100',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='INVESTMENT_LIMIT_RATIO'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go
INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'UR_MIN', N'UR保單投資大小限制',
		N'10',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='INVESTMENT_LIMIT_RATIO'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go
INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'UR_MAX', N'UR保單投資大小限制',
		N'100',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='INVESTMENT_LIMIT_RATIO'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'UQ_MIN', N'UQ保單投資大小限制',
		N'10',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='INVESTMENT_LIMIT_RATIO'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go
INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'UQ_MAX', N'UQ保單投資大小限制',
		N'100',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='INVESTMENT_LIMIT_RATIO'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go
INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'UP_MIN', N'UP保單投資大小限制',
		N'10',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='INVESTMENT_LIMIT_RATIO'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go
INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'UP_MAX', N'UP保單投資大小限制',
		N'100',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='INVESTMENT_LIMIT_RATIO'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go
INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'US_MIN', N'US保單投資大小限制',
		N'10',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='INVESTMENT_LIMIT_RATIO'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go
INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'US_MAX', N'US保單投資大小限制',
		N'100',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='INVESTMENT_LIMIT_RATIO'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go
INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'UU_MIN', N'UU保單投資大小限制',
		N'10',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='INVESTMENT_LIMIT_RATIO'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go
INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'UU_MAX', N'UU保單投資大小限制',
		N'100',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='INVESTMENT_LIMIT_RATIO'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go




		--- 臺幣  欲轉出基金與比例,限制比例小值
INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'NTD_PROPORTION_MIN', N'臺幣欲轉出基金與比例,限制比例小值',
		N'10',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='INVESTMENT_LIMIT_RATIO'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go


		---美元   欲轉出基金與比例,限制比例小值
INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'USD_PROPORTION_MIN', N'美元欲轉出基金與比例,限制比例小值',
		N'10',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='INVESTMENT_LIMIT_RATIO'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go

		--- 臺幣  欲轉出基金單位,限制比例-此項是為金額,單位后台計算
INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'NTD_UNIT_MIN', N'臺幣欲轉出基金單位,限制比例-此項是為金額,單位后台計算',
		N'500',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='INVESTMENT_LIMIT_RATIO'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go


		---美元  欲轉出基金單位,限制比例-此項是為金額,單位后台計算
INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'USD_UNIT_MIN', N'美元欲轉出基金單位,限制比例-此項是為金額,單位后台計算',
		N'100',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='INVESTMENT_LIMIT_RATIO'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go




INSERT ESERVICE_ADM.dbo.PARAMETER
    (
	PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER
	)
VALUES
   (
   (select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER)
	, N'eservice'
	, N'DEPOSIT'
	, N'已持有投資標的轉換'
	, N'DEPOSIT'
	, (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='ONLINE_CHANGE')
	, NULL
	, NULL
	, 1
	, NULL
	, NULL
	, getdate()
	, N'system'
	, NULL
	, NULL
	)
go

-- 設定停損停利通知
INSERT ESERVICE_ADM.dbo.PARAMETER_CATEGORY (PARAMETER_CATEGORY_ID, SYSTEM_ID, CATEGORY_CODE, CATEGORY_NAME, STATUS, CREATE_DATE, CREATE_USER)
VALUES ((select max(PARAMETER_CATEGORY_ID)+1 from ESERVICE_ADM.dbo.PARAMETER_CATEGORY), 'eservice', 'NOTIFICATION', N'設定停損停利通知', 1, getdate(), 'admin')
go

--設定停損停利通知[備註]
INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'NOTIFICATION_REMARK1', N'設定停損停利通知',
		N'<li>若您的投資風險屬性為保守型，您可選擇保守型的基金RR1~RR2。</li>
          <li>若您的投資風險屬性為穩健型，您可選擇保守型及穩健型的基金RR1~RR4。</li>
          <li>若您的投資風險屬性為積極型型，您可選擇保守型、穩健型及積極型型的基金RR1~RR5。</li>
          <li>為確保保險商品符合您的投資能力及風險性，投資風險屬性若有變更，本公司將以您最新的風險屬性作為名下所有保單日後變更的評估依據。</li>',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='NOTIFICATION'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go

INSERT ESERVICE_ADM.dbo.PARAMETER
    (
	PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER
	)
VALUES
   (
   (select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER)
	, N'eservice'
	, N'CASH_PAYMENT'
	, N'收益分配或撥回資產分配方式'
	, N'CASH_PAYMENT'
	, (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='ONLINE_CHANGE')
	, NULL
	, NULL
	, 1
	, NULL
	, NULL
	, getdate()
	, N'system'
	, NULL
	, NULL
	)
go

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ( (SELECT MAX(PARAMETER_ID)+1 FROM  ESERVICE_ADM.dbo.PARAMETER ), N'eservice', N'WORDING_INVESTMENT_001', N'未來保費投資標的與分配比例', N'可新增或移除投資標的', (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE = 'PAGE_WORDING'), 0, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL);

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ( (SELECT MAX(PARAMETER_ID)+1 FROM  ESERVICE_ADM.dbo.PARAMETER ), N'eservice', N'WORDING_INVESTMENT_002', N'已持有投資標的轉換', N'可直接不同基金單位轉換', (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE = 'PAGE_WORDING'), 0, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL);

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ( (SELECT MAX(PARAMETER_ID)+1 FROM  ESERVICE_ADM.dbo.PARAMETER ), N'eservice', N'WORDING_INVESTMENT_003', N'保單提領(贖回)', N'可執行保單提領贖回', (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE = 'PAGE_WORDING'), 0, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL);

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ( (SELECT MAX(PARAMETER_ID)+1 FROM  ESERVICE_ADM.dbo.PARAMETER ), N'eservice', N'WORDING_INVESTMENT_004', N'收益分配或撥回資產分配方式', N'設定給付方式', (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE = 'PAGE_WORDING'), 0, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL);

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ( (SELECT MAX(PARAMETER_ID)+1 FROM  ESERVICE_ADM.dbo.PARAMETER ), N'eservice', N'WORDING_INVESTMENT_005', N'變更風險屬性', N'可變更個人投資風險屬性', (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE = 'PAGE_WORDING'), 0, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL);

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ( (SELECT MAX(PARAMETER_ID)+1 FROM  ESERVICE_ADM.dbo.PARAMETER ), N'eservice', N'WORDING_INVESTMENT_006', N'定期定額保費變更', N'彈性保費', (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE = 'PAGE_WORDING'), 0, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL);

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ( (SELECT MAX(PARAMETER_ID)+1 FROM  ESERVICE_ADM.dbo.PARAMETER ), N'eservice', N'WORDING_INVESTMENT_007', N'設定停利停損通知', N'申請內容的相關說明', (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE = 'PAGE_WORDING'), 0, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL);
go

-- 風險投資校驗
INSERT ESERVICE_ADM.dbo.PARAMETER_CATEGORY (PARAMETER_CATEGORY_ID, SYSTEM_ID, CATEGORY_CODE, CATEGORY_NAME, STATUS, CREATE_DATE, CREATE_USER)
VALUES ((select max(PARAMETER_CATEGORY_ID)+1 from ESERVICE_ADM.dbo.PARAMETER_CATEGORY), 'eservice', 'INVESTMENT_CHECK_LIST', N'風險投資校驗', 1, getdate(), 'admin')

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ( (SELECT MAX(PARAMETER_ID)+1 FROM  ESERVICE_ADM.dbo.PARAMETER ), N'eservice', N'PROCESS_INVESTMENT_LIST', N'投資進行中類型', N'INVESTMENT,CONVERSION,DEPOSIT,FUND_NOTIFICATION,CASH_PAYMENT,RISK_LEVEL', (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE = 'INVESTMENT_CHECK_LIST'), 0, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL);
go

---給管理人員的內容模板配置數據
-- 添加投資型首家件通知管理人員 MESSAGING_TEMPLATE条件
---【管理人員】
INSERT INTO  ESERVICE_ADM.[dbo].[MESSAGING_TEMPLATE]([MESSAGING_TEMPLATE_ID],[SYSTEM_ID],[MESSAGING_TEMPLATE_CODE],[MESSAGING_TEMPLATE_NAME],[STATUS],[TRIGGER_TYPE],[EVENT_TYPE],[SEND_TYPE],[SEND_TIME],[CIRCLE_TYPE],[CIRCLE_VALUE],[RECEIVER_MODE],[MESSAGING_SUBJECT],[MESSAGING_CONTENT],[CREATE_DATE],[CREATE_USER],[UPDATE_DATE],[UPDATE_USER])
VALUES((select max([MESSAGING_TEMPLATE_ID])+1 from ESERVICE_ADM.dbo.MESSAGING_TEMPLATE),N'eservice',N'ELIFE_MAIL_027',N'投資型首家件通知管理人員MAIL模版 ',3,N'api ',NULL,N'email',NULL,NULL,NULL,N'dynamic',N'投資型首家件通知管理人員內容',N'申請日期 : ${DATA}<br/>申請功能 :${APPLICATION_FUNCTION}<br/>申請狀態 : ${TransStatus}<br/>申請序號 :${TransNum}<br/>保單號碼 :${POLICY_NO}<br/>', getdate(),N'admin',getdate(),N'admin')
GO

INSERT ESERVICE_ADM.dbo.MESSAGING_PARAMETER (MESSAGING_TEMPLATE_ID,PARAMETER_ID) VALUES ((select MESSAGING_TEMPLATE_ID from ESERVICE_ADM.dbo.MESSAGING_TEMPLATE where MESSAGING_TEMPLATE_CODE = 'ELIFE_MAIL_027'),
		(select PARAMETER_ID from   ESERVICE_ADM.dbo.PARAMETER  where  PARAMETER_CODE='MSG_PARAM_DATA'));
GO

INSERT ESERVICE_ADM.dbo.MESSAGING_PARAMETER (MESSAGING_TEMPLATE_ID,PARAMETER_ID) VALUES ((select MESSAGING_TEMPLATE_ID from ESERVICE_ADM.dbo.MESSAGING_TEMPLATE where MESSAGING_TEMPLATE_CODE = 'ELIFE_MAIL_027'),
		(select PARAMETER_ID from   ESERVICE_ADM.dbo.PARAMETER  where  PARAMETER_CODE='MSG_PARAM_APPLICATION_FUNCTION'));
GO
INSERT ESERVICE_ADM.dbo.MESSAGING_PARAMETER (MESSAGING_TEMPLATE_ID,PARAMETER_ID) VALUES ((select MESSAGING_TEMPLATE_ID from ESERVICE_ADM.dbo.MESSAGING_TEMPLATE where MESSAGING_TEMPLATE_CODE = 'ELIFE_MAIL_027'),
		(select PARAMETER_ID from   ESERVICE_ADM.dbo.PARAMETER  where  PARAMETER_CODE='MSG_PARAM_TransStatus'));
GO
INSERT ESERVICE_ADM.dbo.MESSAGING_PARAMETER (MESSAGING_TEMPLATE_ID,PARAMETER_ID) VALUES ((select MESSAGING_TEMPLATE_ID from ESERVICE_ADM.dbo.MESSAGING_TEMPLATE where MESSAGING_TEMPLATE_CODE = 'ELIFE_MAIL_027'),
		(select PARAMETER_ID from   ESERVICE_ADM.dbo.PARAMETER  where  PARAMETER_CODE='MSG_PARAM_TransNum'));
GO
INSERT ESERVICE_ADM.dbo.MESSAGING_PARAMETER (MESSAGING_TEMPLATE_ID,PARAMETER_ID) VALUES ((select MESSAGING_TEMPLATE_ID from ESERVICE_ADM.dbo.MESSAGING_TEMPLATE where MESSAGING_TEMPLATE_CODE = 'ELIFE_MAIL_027'),
		(select PARAMETER_ID from   ESERVICE_ADM.dbo.PARAMETER  where  PARAMETER_CODE='MSG_PARAM_POLICY_NO'));
GO
--申請送出成功後給【管理】PARAMETER
INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'MSG_PARAM_APPLICATION_FUNCTION', N'通信模版參數-保單申請功能', N'APPLICATION_FUNCTION', (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='MessagingParameter'), NULL, NULL, 1, N'N', NULL, getdate(), N'admin', getdate(), N'admin')
go

--保戶前台線上申請送出成功後給【保戶】PARAMETER
INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'MSG_PARAM_TITLE', N'通信模版參數-保單標題', N'TITLE', (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='MessagingParameter'), NULL, NULL, 1, N'N', NULL, getdate(), N'admin', getdate(), N'admin')
go
--保戶前台線上申請送出成功後給【保戶】PARAMETER
INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'MSG_PARAM_MESSAGE', N'通信模版參數-保單消息', N'MESSAGE', (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='MessagingParameter'), NULL, NULL, 1, N'N', NULL, getdate(), N'admin', getdate(), N'admin')
go

---【保戶人員】
INSERT INTO  ESERVICE_ADM.[dbo].[MESSAGING_TEMPLATE]([MESSAGING_TEMPLATE_ID],[SYSTEM_ID],[MESSAGING_TEMPLATE_CODE],[MESSAGING_TEMPLATE_NAME],[STATUS],[TRIGGER_TYPE],[EVENT_TYPE],[SEND_TYPE],[SEND_TIME],[CIRCLE_TYPE],[CIRCLE_VALUE],[RECEIVER_MODE],[MESSAGING_SUBJECT],[MESSAGING_CONTENT],[CREATE_DATE],[CREATE_USER],[UPDATE_DATE],[UPDATE_USER])
VALUES((select max([MESSAGING_TEMPLATE_ID])+1 from ESERVICE_ADM.dbo.MESSAGING_TEMPLATE),N'eservice',N'ELIFE_MAIL_028',N'投資型首家件通知保戶MAIL模版 ',3,N'api ',NULL,N'email',NULL,NULL,NULL,N'dynamic',N'投資型首家件通知保戶內容',N'臺銀人壽投資型保單${TITLE}<br/>親愛的臺銀人壽保戶您好:${MESSAGE}<br/>如有疑問，請先至臺銀人壽會員專區查詢或請電洽:<br/>免費客服電話0800-011966<br/>市話服務:02-27849151轉保全科<br/>', getdate(),N'admin',getdate(),N'admin')
GO

INSERT ESERVICE_ADM.dbo.MESSAGING_PARAMETER (MESSAGING_TEMPLATE_ID,PARAMETER_ID) VALUES ((select MESSAGING_TEMPLATE_ID from ESERVICE_ADM.dbo.MESSAGING_TEMPLATE where MESSAGING_TEMPLATE_CODE = 'ELIFE_MAIL_028'),
		(select PARAMETER_ID from   ESERVICE_ADM.dbo.PARAMETER  where  PARAMETER_CODE='MSG_PARAM_TITLE'));
GO

INSERT ESERVICE_ADM.dbo.MESSAGING_PARAMETER (MESSAGING_TEMPLATE_ID,PARAMETER_ID) VALUES ((select MESSAGING_TEMPLATE_ID from ESERVICE_ADM.dbo.MESSAGING_TEMPLATE where MESSAGING_TEMPLATE_CODE = 'ELIFE_MAIL_028'),
		(select PARAMETER_ID from   ESERVICE_ADM.dbo.PARAMETER  where  PARAMETER_CODE='MSG_PARAM_MESSAGE'));
GO

INSERT ESERVICE_ADM.dbo.PARAMETER_CATEGORY (PARAMETER_CATEGORY_ID, SYSTEM_ID, CATEGORY_CODE, CATEGORY_NAME, STATUS, CREATE_DATE, CREATE_USER)
VALUES ((select max(PARAMETER_CATEGORY_ID)+1 from ESERVICE_ADM.dbo.PARAMETER_CATEGORY), 'eservice', 'DEPOST_PARAMETER_CATEGORY', N'保單提領(贖回)校驗', 1, getdate(), 'admin')

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'DEPOSIT_UC_NTD_MIN_VALUE', N'UC臺幣轉出金額',
		N'5000',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='DEPOST_PARAMETER_CATEGORY'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'DEPOSIT_UC_NTD_SURPLUS_VALUE', N'UC臺幣剩余金額',
		N'10000',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='DEPOST_PARAMETER_CATEGORY'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'DEPOSIT_UU_USD_MIN_VALUE', N'UU美金轉出金額',
		N'150',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='DEPOST_PARAMETER_CATEGORY'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'DEPOSIT_UU_USD_SURPLUS_VALUE', N'UU美金剩余金額',
		N'300',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='DEPOST_PARAMETER_CATEGORY'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'DEPOST_POST_SHOW', N'UU,UH',
		N'UC,UH',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='DEPOST_PARAMETER_CATEGORY'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'DEPOST_US_CURRENCY_ACCOUNT', N'RTNTD00420',
		N'RTNTD00420',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='DEPOST_PARAMETER_CATEGORY'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'DEPOST_UU_CURRENCY_ACCOUNT', N'RTUSD00430',
		N'RTUSD00430',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='DEPOST_PARAMETER_CATEGORY'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'DEPOST_US_STOP_ACCOUNT', N'RTNTD00430',
		N'RTNTD00430',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='DEPOST_PARAMETER_CATEGORY'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'DEPOST_UU_STOP_ACCOUNT', N'RTUSD00440',
		N'RTUSD00440',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='DEPOST_PARAMETER_CATEGORY'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go

--- Questions and Options

INSERT [ESERVICE].[dbo].[OPTIONS] ([QUESTION_ID], [ITEM], [SEQ], [SCORE], [CREATE_TIME], [UPDATE_TIME]) VALUES (CAST(1 AS Numeric(18, 0)), N'A. 71歲以上', CAST(1 AS Numeric(3, 0)), CAST(0 AS Numeric(18, 0)), NULL, NULL)
INSERT [ESERVICE].[dbo].[OPTIONS] ([QUESTION_ID], [ITEM], [SEQ], [SCORE], [CREATE_TIME], [UPDATE_TIME]) VALUES (CAST(1 AS Numeric(18, 0)), N'B. 51歲以上~70歲', CAST(2 AS Numeric(3, 0)), CAST(1 AS Numeric(18, 0)), NULL, NULL)
INSERT [ESERVICE].[dbo].[OPTIONS] ([QUESTION_ID], [ITEM], [SEQ], [SCORE], [CREATE_TIME], [UPDATE_TIME]) VALUES (CAST(1 AS Numeric(18, 0)), N'C. 40歲以上~50歲', CAST(3 AS Numeric(3, 0)), CAST(2 AS Numeric(18, 0)), NULL, NULL)
INSERT [ESERVICE].[dbo].[OPTIONS] ([QUESTION_ID], [ITEM], [SEQ], [SCORE], [CREATE_TIME], [UPDATE_TIME]) VALUES (CAST(1 AS Numeric(18, 0)), N'D. 40歲以下', CAST(4 AS Numeric(3, 0)), CAST(3 AS Numeric(18, 0)), NULL, NULL)
INSERT [ESERVICE].[dbo].[OPTIONS] ([QUESTION_ID], [ITEM], [SEQ], [SCORE], [CREATE_TIME], [UPDATE_TIME]) VALUES (CAST(2 AS Numeric(18, 0)), N'A. 定存、傳統型保險商品', CAST(5 AS Numeric(3, 0)), CAST(0 AS Numeric(18, 0)), NULL, NULL)
INSERT [ESERVICE].[dbo].[OPTIONS] ([QUESTION_ID], [ITEM], [SEQ], [SCORE], [CREATE_TIME], [UPDATE_TIME]) VALUES (CAST(2 AS Numeric(18, 0)), N'B. 股票、債券、基金', CAST(6 AS Numeric(3, 0)), CAST(1 AS Numeric(18, 0)), NULL, NULL)
INSERT [ESERVICE].[dbo].[OPTIONS] ([QUESTION_ID], [ITEM], [SEQ], [SCORE], [CREATE_TIME], [UPDATE_TIME]) VALUES (CAST(2 AS Numeric(18, 0)), N'C. 結構型債券、期貨、選擇權或其他衍生性金融商品', CAST(7 AS Numeric(3, 0)), CAST(2 AS Numeric(18, 0)), NULL, NULL)
INSERT [ESERVICE].[dbo].[OPTIONS] ([QUESTION_ID], [ITEM], [SEQ], [SCORE], [CREATE_TIME], [UPDATE_TIME]) VALUES (CAST(3 AS Numeric(18, 0)), N'A. 未滿3個月', CAST(8 AS Numeric(3, 0)), CAST(0 AS Numeric(18, 0)), NULL, NULL)
INSERT [ESERVICE].[dbo].[OPTIONS] ([QUESTION_ID], [ITEM], [SEQ], [SCORE], [CREATE_TIME], [UPDATE_TIME]) VALUES (CAST(3 AS Numeric(18, 0)), N'B. 3個月以上~未滿3年', CAST(9 AS Numeric(3, 0)), CAST(1 AS Numeric(18, 0)), NULL, NULL)
INSERT [ESERVICE].[dbo].[OPTIONS] ([QUESTION_ID], [ITEM], [SEQ], [SCORE], [CREATE_TIME], [UPDATE_TIME]) VALUES ( CAST(3 AS Numeric(18, 0)), N'C. 3年以上', CAST(10 AS Numeric(3, 0)), CAST(2 AS Numeric(18, 0)), NULL, NULL)
INSERT [ESERVICE].[dbo].[OPTIONS] ([QUESTION_ID], [ITEM], [SEQ], [SCORE], [CREATE_TIME], [UPDATE_TIME]) VALUES ( CAST(4 AS Numeric(18, 0)), N'A. 0%', CAST(11 AS Numeric(3, 0)), CAST(0 AS Numeric(18, 0)), NULL, NULL)
INSERT [ESERVICE].[dbo].[OPTIONS] ([QUESTION_ID], [ITEM], [SEQ], [SCORE], [CREATE_TIME], [UPDATE_TIME]) VALUES ( CAST(4 AS Numeric(18, 0)), N'B.未滿25%　', CAST(12 AS Numeric(3, 0)), CAST(1 AS Numeric(18, 0)), NULL, NULL)
INSERT [ESERVICE].[dbo].[OPTIONS] ([QUESTION_ID], [ITEM], [SEQ], [SCORE], [CREATE_TIME], [UPDATE_TIME]) VALUES ( CAST(4 AS Numeric(18, 0)), N'C.25%以上〜未滿50%', CAST(13 AS Numeric(3, 0)), CAST(2 AS Numeric(18, 0)), NULL, NULL)
INSERT [ESERVICE].[dbo].[OPTIONS] ([QUESTION_ID], [ITEM], [SEQ], [SCORE], [CREATE_TIME], [UPDATE_TIME]) VALUES ( CAST(4 AS Numeric(18, 0)), N'D. 50%以上', CAST(14 AS Numeric(3, 0)), CAST(3 AS Numeric(18, 0)), NULL, NULL)
INSERT [ESERVICE].[dbo].[OPTIONS] ([QUESTION_ID], [ITEM], [SEQ], [SCORE], [CREATE_TIME], [UPDATE_TIME]) VALUES ( CAST(5 AS Numeric(18, 0)), N'A. 只可承受獲利，不能接受損失 【若選擇本選項，不論總分為何，均屬於「不適合購買投資型保單」】', CAST(15 AS Numeric(3, 0)), CAST(0 AS Numeric(18, 0)), NULL, NULL)
INSERT [ESERVICE].[dbo].[OPTIONS] ([QUESTION_ID], [ITEM], [SEQ], [SCORE], [CREATE_TIME], [UPDATE_TIME]) VALUES ( CAST(5 AS Numeric(18, 0)), N'B. 可能獲利5%，可能損失5%', CAST(16 AS Numeric(3, 0)), CAST(1 AS Numeric(18, 0)), NULL, NULL)
INSERT [ESERVICE].[dbo].[OPTIONS] ([QUESTION_ID], [ITEM], [SEQ], [SCORE], [CREATE_TIME], [UPDATE_TIME]) VALUES ( CAST(5 AS Numeric(18, 0)), N'C. 可能獲利10%，可能損失10%', CAST(17 AS Numeric(3, 0)), CAST(2 AS Numeric(18, 0)), NULL, NULL)
INSERT [ESERVICE].[dbo].[OPTIONS] ([QUESTION_ID], [ITEM], [SEQ], [SCORE], [CREATE_TIME], [UPDATE_TIME]) VALUES ( CAST(5 AS Numeric(18, 0)), N'D. 可能獲利15%，可能損失15%', CAST(18 AS Numeric(3, 0)), CAST(3 AS Numeric(18, 0)), NULL, NULL)
INSERT [ESERVICE].[dbo].[OPTIONS] ([QUESTION_ID], [ITEM], [SEQ], [SCORE], [CREATE_TIME], [UPDATE_TIME]) VALUES ( CAST(6 AS Numeric(18, 0)), N'A. 無', CAST(19 AS Numeric(3, 0)), CAST(0 AS Numeric(18, 0)), NULL, NULL)
INSERT [ESERVICE].[dbo].[OPTIONS] ([QUESTION_ID], [ITEM], [SEQ], [SCORE], [CREATE_TIME], [UPDATE_TIME]) VALUES ( CAST(6 AS Numeric(18, 0)), N'B. 未滿3小時', CAST(20 AS Numeric(3, 0)), CAST(1 AS Numeric(18, 0)), NULL, NULL)
INSERT [ESERVICE].[dbo].[OPTIONS] ([QUESTION_ID], [ITEM], [SEQ], [SCORE], [CREATE_TIME], [UPDATE_TIME]) VALUES ( CAST(6 AS Numeric(18, 0)), N'C. 3小時以上~未滿9小時', CAST(21 AS Numeric(3, 0)), CAST(2 AS Numeric(18, 0)), NULL, NULL)
INSERT [ESERVICE].[dbo].[OPTIONS] ([QUESTION_ID], [ITEM], [SEQ], [SCORE], [CREATE_TIME], [UPDATE_TIME]) VALUES ( CAST(6 AS Numeric(18, 0)), N'D. 9小時以上', CAST(22 AS Numeric(3, 0)), CAST(3 AS Numeric(18, 0)), NULL, NULL)
INSERT [ESERVICE].[dbo].[OPTIONS] ([QUESTION_ID], [ITEM], [SEQ], [SCORE], [CREATE_TIME], [UPDATE_TIME]) VALUES ( CAST(7 AS Numeric(18, 0)), N'A. 虧損未達6個月時就考慮賣掉', CAST(23 AS Numeric(3, 0)), CAST(0 AS Numeric(18, 0)), NULL, NULL)
INSERT [ESERVICE].[dbo].[OPTIONS] ([QUESTION_ID], [ITEM], [SEQ], [SCORE], [CREATE_TIME], [UPDATE_TIME]) VALUES ( CAST(7 AS Numeric(18, 0)), N'B. 虧損已經6個月以上才考慮進行調整', CAST(24 AS Numeric(3, 0)), CAST(1 AS Numeric(18, 0)), NULL, NULL)
INSERT [ESERVICE].[dbo].[OPTIONS] ([QUESTION_ID], [ITEM], [SEQ], [SCORE], [CREATE_TIME], [UPDATE_TIME]) VALUES ( CAST(7 AS Numeric(18, 0)), N'C. 持有1年以上，因長期投資才是致勝關鍵', CAST(25 AS Numeric(3, 0)), CAST(2 AS Numeric(18, 0)), NULL, NULL)
INSERT [ESERVICE].[dbo].[OPTIONS] ([QUESTION_ID], [ITEM], [SEQ], [SCORE], [CREATE_TIME], [UPDATE_TIME]) VALUES ( CAST(8 AS Numeric(18, 0)), N'A. 避免資產的損失', CAST(26 AS Numeric(3, 0)), CAST(0 AS Numeric(18, 0)), NULL, NULL)
INSERT [ESERVICE].[dbo].[OPTIONS] ([QUESTION_ID], [ITEM], [SEQ], [SCORE], [CREATE_TIME], [UPDATE_TIME]) VALUES ( CAST(8 AS Numeric(18, 0)), N'B. 資產穩健的成長', CAST(27 AS Numeric(3, 0)), CAST(1 AS Numeric(18, 0)), NULL, NULL)
INSERT [ESERVICE].[dbo].[OPTIONS] ([QUESTION_ID], [ITEM], [SEQ], [SCORE], [CREATE_TIME], [UPDATE_TIME]) VALUES ( CAST(8 AS Numeric(18, 0)), N'C. 資產迅速的成長', CAST(28 AS Numeric(3, 0)), CAST(2 AS Numeric(18, 0)), NULL, NULL)
INSERT [ESERVICE].[dbo].[OPTIONS] ([QUESTION_ID], [ITEM], [SEQ], [SCORE], [CREATE_TIME], [UPDATE_TIME]) VALUES ( CAST(9 AS Numeric(18, 0)), N'A. 影響程度大', CAST(29 AS Numeric(3, 0)), CAST(0 AS Numeric(18, 0)), NULL, NULL)
INSERT [ESERVICE].[dbo].[OPTIONS] ([QUESTION_ID], [ITEM], [SEQ], [SCORE], [CREATE_TIME], [UPDATE_TIME]) VALUES ( CAST(9 AS Numeric(18, 0)), N'B. 影響程度中', CAST(30 AS Numeric(3, 0)), CAST(1 AS Numeric(18, 0)), NULL, NULL)
INSERT [ESERVICE].[dbo].[OPTIONS] ([QUESTION_ID], [ITEM], [SEQ], [SCORE], [CREATE_TIME], [UPDATE_TIME]) VALUES ( CAST(9 AS Numeric(18, 0)), N'C. 影響程度小', CAST(31 AS Numeric(3, 0)), CAST(2 AS Numeric(18, 0)), NULL, NULL)
INSERT [ESERVICE].[dbo].[OPTIONS] ([QUESTION_ID], [ITEM], [SEQ], [SCORE], [CREATE_TIME], [UPDATE_TIME]) VALUES ( CAST(9 AS Numeric(18, 0)), N'D. 沒有影響', CAST(32 AS Numeric(3, 0)), CAST(3 AS Numeric(18, 0)), NULL, NULL)

INSERT [ESERVICE].[dbo].[QUESTION] ([ID], [QUESTION], [TITLE], [IS_MULTI], [SEQ], [EFFECTIVE_TIME], [STOP_TIME]) VALUES (next value for QUESTION_SEQUENCE, N'1. 您目前的年齡', NULL, N'N', CAST(1 AS Numeric(3, 0)), getdate(), '2099-12-30')
INSERT [ESERVICE].[dbo].[QUESTION] ([ID], [QUESTION], [TITLE], [IS_MULTI], [SEQ], [EFFECTIVE_TIME], [STOP_TIME]) VALUES (next value for QUESTION_SEQUENCE, N'2. 投資經驗（A）：【可複選，但以分數較高者計分】', NULL, N'Y', CAST(2 AS Numeric(3, 0)), getdate(), '2099-12-30')
INSERT [ESERVICE].[dbo].[QUESTION] ([ID], [QUESTION], [TITLE], [IS_MULTI], [SEQ], [EFFECTIVE_TIME], [STOP_TIME]) VALUES (next value for QUESTION_SEQUENCE, N'3. 投資經驗（B）：【問項2為0分時，本問項一律為0分】', NULL, N'N', CAST(3 AS Numeric(3, 0)), getdate(), '2099-12-30')
INSERT [ESERVICE].[dbo].[QUESTION] ([ID], [QUESTION], [TITLE], [IS_MULTI], [SEQ], [EFFECTIVE_TIME], [STOP_TIME]) VALUES (next value for QUESTION_SEQUENCE, N'4. 目前所投資具價值波動性的理財工具(如股票、基金、選擇權等)佔總資產的百分比為', NULL, N'N', CAST(4 AS Numeric(3, 0)), getdate(), '2099-12-30')
INSERT [ESERVICE].[dbo].[QUESTION] ([ID], [QUESTION], [TITLE], [IS_MULTI], [SEQ], [EFFECTIVE_TIME], [STOP_TIME]) VALUES (next value for QUESTION_SEQUENCE, N'5. 您期望年投資報酬率及所能承受年投資風險為(包含價格與匯率波動)', NULL, N'N', CAST(5 AS Numeric(3, 0)), getdate(), '2099-12-30')
INSERT [ESERVICE].[dbo].[QUESTION] ([ID], [QUESTION], [TITLE], [IS_MULTI], [SEQ], [EFFECTIVE_TIME], [STOP_TIME]) VALUES (next value for QUESTION_SEQUENCE, N'6. 您每月花多少時間吸收財經資訊', NULL, N'N', CAST(6 AS Numeric(3, 0)), getdate(), '2099-12-30')
INSERT [ESERVICE].[dbo].[QUESTION] ([ID], [QUESTION], [TITLE], [IS_MULTI], [SEQ], [EFFECTIVE_TIME], [STOP_TIME]) VALUES (next value for QUESTION_SEQUENCE, N'7. 投資因市場波動使得有所虧損時，可能採取哪一項處理方式', NULL, N'N', CAST(7 AS Numeric(3, 0)), getdate(), '2099-12-30')
INSERT [ESERVICE].[dbo].[QUESTION] ([ID], [QUESTION], [TITLE], [IS_MULTI], [SEQ], [EFFECTIVE_TIME], [STOP_TIME]) VALUES (next value for QUESTION_SEQUENCE, N'8. 您購買投資型保險商品想達成的財務目標', NULL, N'N', CAST(8 AS Numeric(3, 0)), getdate(), '2099-12-30')
INSERT [ESERVICE].[dbo].[QUESTION] ([ID], [QUESTION], [TITLE], [IS_MULTI], [SEQ], [EFFECTIVE_TIME], [STOP_TIME]) VALUES (next value for QUESTION_SEQUENCE, N'9. 如您持有之整體投資資產下跌超過15%，請問對您的生活影響程 度為何', NULL, N'N', CAST(9 AS Numeric(3, 0)), getdate(), '2099-12-30')
go

INSERT ESERVICE_ADM.dbo.PARAMETER_CATEGORY (PARAMETER_CATEGORY_ID, SYSTEM_ID, CATEGORY_CODE, CATEGORY_NAME, STATUS, CREATE_DATE, CREATE_USER)
VALUES ((select max(PARAMETER_CATEGORY_ID)+1 from ESERVICE_ADM.dbo.PARAMETER_CATEGORY), 'eservice', 'INVESTMENT_TYPES', N'投資標類型', 1, getdate(), 'admin')
go

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'INVESTMENT_TYPE', N'投資標類型',
		N'UU,UC',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='INVESTMENT_TYPES'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go

INSERT ESERVICE_ADM.dbo.PARAMETER
    (
	PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER
	)
VALUES
   (
   (select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER)
	, N'eservice'
	, N'CHANGE_PREMIUM'
	, N'定期超額保費'
	, N'CHANGE_PREMIUM'
	, (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='ONLINE_CHANGE')
	, NULL
	, NULL
	, 1
	, NULL
	, NULL
	, getdate()
	, N'system'
	, NULL
	, NULL
	)
go

INSERT ESERVICE_ADM.dbo.PARAMETER_CATEGORY (PARAMETER_CATEGORY_ID, SYSTEM_ID, CATEGORY_CODE, CATEGORY_NAME, STATUS, CREATE_DATE, CREATE_USER)
VALUES ((select max(PARAMETER_CATEGORY_ID)+1 from ESERVICE_ADM.dbo.PARAMETER_CATEGORY), 'eservice', 'RISK_LEVEL_TO_RR', N'風險屬性轉換基金等級', 1, getdate(), 'admin')
go

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'RISK_LEVEL_TO_RR_A', N'保守型',
		N'RR1,RR2',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='RISK_LEVEL_TO_RR'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'RISK_LEVEL_TO_RR_B', N'穩健型',
		N'RR1,RR2,RR3,RR4',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='RISK_LEVEL_TO_RR'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'RISK_LEVEL_TO_RR_C', N'積極型',
		N'RR1,RR2,RR3,RR4,RR5',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='RISK_LEVEL_TO_RR'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go

INSERT ESERVICE_ADM.dbo.PARAMETER_CATEGORY (PARAMETER_CATEGORY_ID, SYSTEM_ID, CATEGORY_CODE, CATEGORY_NAME, STATUS, CREATE_DATE, CREATE_USER)
VALUES ((select max(PARAMETER_CATEGORY_ID)+1 from ESERVICE_ADM.dbo.PARAMETER_CATEGORY), 'eservice', 'RISK_SCORE_TO_LEVEL', N'風險評分轉風險等級', 1, getdate(), 'admin')
go

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'RISK_SCORE_TO_LEVEL_A_MIN', N'A',
		N'0',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='RISK_SCORE_TO_LEVEL'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'RISK_SCORE_TO_LEVEL_A_MAX', N'A',
		N'10',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='RISK_SCORE_TO_LEVEL'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'RISK_SCORE_TO_LEVEL_B_MIN', N'B',
		N'10',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='RISK_SCORE_TO_LEVEL'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'RISK_SCORE_TO_LEVEL_B_MAX', N'B',
		N'20',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='RISK_SCORE_TO_LEVEL'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'RISK_SCORE_TO_LEVEL_C_MIN', N'C',
		N'20',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='RISK_SCORE_TO_LEVEL'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go

--- FUND_NOTIFICATION MESSAGE
INSERT INTO  ESERVICE_ADM.[dbo].[MESSAGING_TEMPLATE]([MESSAGING_TEMPLATE_ID],[SYSTEM_ID],[MESSAGING_TEMPLATE_CODE],[MESSAGING_TEMPLATE_NAME],[STATUS],[TRIGGER_TYPE],[EVENT_TYPE],[SEND_TYPE],[SEND_TIME],[CIRCLE_TYPE],[CIRCLE_VALUE],[RECEIVER_MODE],[MESSAGING_SUBJECT],[MESSAGING_CONTENT],[CREATE_DATE],[CREATE_USER],[UPDATE_DATE],[UPDATE_USER])
VALUES((select max([MESSAGING_TEMPLATE_ID])+1 from ESERVICE_ADM.dbo.MESSAGING_TEMPLATE),N'eservice',N'ELIFE_MAIL_FN',N'停利停損MAIL模版 ',3,N'api ',NULL,N'email',NULL,NULL,NULL,N'dynamic',N'停利停損內容',N'臺銀人壽投資型保單已達停利停損設定通知<br/> 親愛的臺銀人壽保戶您好: 本公司通知您所設定的投資型保單停利停損通知已達您的指定上下限值條件如下， 如有疑問，請先至臺銀人壽會員專區查詢或請電洽: 免費客服電話0800-011966 市話服務:02-27849151轉保全科<br/>${FUND_NOTIFICATION_DATA}', getdate(),N'admin',getdate(),N'admin')
GO

INSERT INTO [ESERVICE_ADM].[dbo].[MESSAGING_TEMPLATE_TMP] SELECT * FROM ESERVICE_ADM.dbo.[MESSAGING_TEMPLATE] WHERE MESSAGING_TEMPLATE_CODE = 'ELIFE_MAIL_FN'

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'MSG_FUND_NOTIFICATION_DATA', N'停利停損通知DATA', N'FUND_NOTIFICATION_DATA', (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='MessagingParameter'), NULL, NULL, 1, N'N', NULL, getdate(), N'admin', getdate(), N'admin')
go

INSERT ESERVICE_ADM.dbo.MESSAGING_PARAMETER (MESSAGING_TEMPLATE_ID,PARAMETER_ID) VALUES ((select MESSAGING_TEMPLATE_ID from ESERVICE_ADM.dbo.MESSAGING_TEMPLATE where MESSAGING_TEMPLATE_CODE = 'ELIFE_MAIL_FN'),
		(select PARAMETER_ID from   ESERVICE_ADM.dbo.PARAMETER  where  PARAMETER_CODE='MSG_FUND_NOTIFICATION_DATA'));
GO

INSERT INTO ESERVICE_ADM.[dbo].[MESSAGING_PARAMETER_TMP] SELECT * FROM ESERVICE_ADM.dbo.MESSAGING_PARAMETER WHERE MESSAGING_TEMPLATE_ID IN ((select MESSAGING_TEMPLATE_ID from ESERVICE_ADM.dbo.MESSAGING_TEMPLATE where MESSAGING_TEMPLATE_CODE = 'ELIFE_MAIL_FN'))
GO

UPDATE ESERVICE_ADM.[dbo].PARAMETER SET PARAMETER_VALUE = CONCAT(PARAMETER_VALUE, '&031:T') WHERE PARAMETER_CODE = 'TRANS_OK_CODE'
UPDATE ESERVICE_ADM.[dbo].PARAMETER SET PARAMETER_VALUE = CONCAT(PARAMETER_VALUE, '&033:T') WHERE PARAMETER_CODE = 'TRANS_OK_CODE'
UPDATE ESERVICE_ADM.[dbo].PARAMETER SET PARAMETER_VALUE = CONCAT(PARAMETER_VALUE, '&032:T') WHERE PARAMETER_CODE = 'TRANS_OK_CODE'
UPDATE ESERVICE_ADM.[dbo].PARAMETER SET PARAMETER_VALUE = CONCAT(PARAMETER_VALUE, '&030:T') WHERE PARAMETER_CODE = 'TRANS_OK_CODE'
UPDATE ESERVICE_ADM.[dbo].PARAMETER SET PARAMETER_VALUE = CONCAT(PARAMETER_VALUE, '&029:T') WHERE PARAMETER_CODE = 'TRANS_OK_CODE'
UPDATE ESERVICE_ADM.[dbo].PARAMETER SET PARAMETER_VALUE = CONCAT(PARAMETER_VALUE, '&028:T') WHERE PARAMETER_CODE = 'TRANS_OK_CODE'
go