-- 已持有投資標的轉換
INSERT ESERVICE_ADM.dbo.PARAMETER_CATEGORY (PARAMETER_CATEGORY_ID, SYSTEM_ID, CATEGORY_CODE, CATEGORY_NAME, STATUS, CREATE_DATE, CREATE_USER)
VALUES ((select max(PARAMETER_CATEGORY_ID)+1 from ESERVICE_ADM.dbo.PARAMETER_CATEGORY), 'eservice', 'INVESTMENT_TRANSFORMATION', N'已持有投資標的轉換條款', 1, getdate(), 'admin')
go

		--- 已持有投資標的轉換[備註]條款
INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'INVESTMENT_TRANSFORMATION_REMARKS', N' 已持有投資標的轉換備註條款信息',
		N'	變額萬能壽險保單：如於15:00前提出申請，則視當日為申請之生效日，逾時則視次一工作日為申請之生效日。<br/>
			此次變更將於下一期應繳保費生效，續期保費將依照本次指定之標的的項目及百分比投資。<br/>
			每一投資標的投資比例不得低於10%，加總需等於100%。<br/>
			目前僅開放“要保人與被保險人為同一人”之保單於網路變更保單資料。<br/>',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='INVESTMENT_TRANSFORMATION'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go
	--- 已持有投資標的轉換[同意]條款
INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'INVESTMENT_TRANSFORMATION_CONSENT', N' 已持有投資標的轉換[同意條款]條款信息',
		N'<iframe src="pdf/terms/臺銀人壽外幣投資標的批註條款-0G_c.pdf" width="100%" height="100%"></iframe>',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='INVESTMENT_TRANSFORMATION'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go

	--- 已持有投資標的[比例]條款
INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'INVESTMENT_TRANSFORMATION_PROPORTION', N' 已持有投資標的轉換[比例備註]條款信息',
		N'若您的投資風險屬性為保守型，您可選擇保守型的基金RR1~RR2。<br/>
		 若您的投資風險屬性為穩健型，您可選擇保守型及穩健型的基金RR1~RR4。<br/>
		 若您的投資風險屬性為積極型型，您可選擇保守型、穩健型及積極型型的基金RR1~RR5。<br/>
		 為確保保險商品符合您的投資能力及風險性，投資風險屬性若有變更，本公司將以您最新的風險屬性作為名下所有保單日後變更的評估依據。<br/>',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='INVESTMENT_TRANSFORMATION'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go

-- 未來保費投資標的與分配比例
INSERT ESERVICE_ADM.dbo.PARAMETER_CATEGORY (PARAMETER_CATEGORY_ID, SYSTEM_ID, CATEGORY_CODE, CATEGORY_NAME, STATUS, CREATE_DATE, CREATE_USER)
VALUES ((select max(PARAMETER_CATEGORY_ID)+1 from ESERVICE_ADM.dbo.PARAMETER_CATEGORY), 'eservice', 'INVESTMENT_DISTRIBUTION', N'未來保費投資標的與分配比例條款', 1, getdate(), 'admin')
go

		---未來保費投資標的與分配比例[備註]條款
INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'INVESTMENT_DISTRIBUTION_REMARKS', N' 未來保費投資標的與分配比例備註條款信息',
		N' <li> 變額萬能壽險保單：如於15:00前提出申請，則是當日為申請生效日，遇時則視為次一工作日為申請之生效日。</li>
          <li>此次變更將於下一期應繳保費日生效，續期保費將依照本次指定之標的項目及百分比投資</li>
          <li>目前僅開放要保人與被保險人為同一人之保單於網路變更保單資料。</li>
          <li>若您的投資風險屬性為保守型，您可選擇保守型的基金RR1~RR2</li>
          <li>若您的投資風險屬性為穩健型，您可選擇穩健型的基金RR1~RR4</li>
          <li>若您的投資風險屬性為穩健型，您可選擇穩健型的基金RR1~RR5</li>
          <li>為確保保險商品符合您的投資能力及風險屬性，投資風險屬性若有變更，本公司將以您最新風險屬性作為名下所有保單日後變更的評估依據</li> ',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='INVESTMENT_DISTRIBUTION'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go
	--- 未來保費投資標的與分配比例[同意]條款
INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'INVESTMENT_DISTRIBUTION_CONSENT', N' 未來保費投資標的與分配比例[同意條款]條款信息',
		N'<iframe src="pdf/terms/臺銀人壽外幣投資標的批註條款-0G_c.pdf" width="100%" height="100%"></iframe>',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='INVESTMENT_DISTRIBUTION'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go

		---未來保費投資標的與分配比例[備註]
INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'INVESTMENT_DISTRIBUTION_REMARK1', N' 未來保費投資標的與分配比例備註',
		N'<li>若您的投資風險屬性為保守型，您可選擇保守型的基金RR1~RR2。</li>
          <li>若您的投資風險屬性為穩健型，您可選擇保守型及穩健型的基金RR1~RR4。</li>
          <li>若您的投資風險屬性為積極型型，您可選擇保守型、穩健型及積極型型的基金RR1~RR5。</li>
          <li>為確保保險商品符合您的投資能力及風險性，投資風險屬性若有變更，本公司將以您最新的風險屬性作為名下所有保單日後變更的評估依據。</li>',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='INVESTMENT_DISTRIBUTION'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go

---未來保費投資標的與分配比例
INSERT ESERVICE_ADM.dbo.PARAMETER
    (
	PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER
	)
VALUES
   (
   (select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER)
	, N'eservice'
	, N'INVESTMENT'
	, N'未來保費投資標的與分配比例'
	, N'INVESTMENT'
	, (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='ONLINE_CHANGE')
	, NULL
	, NULL
	, 1
	, NULL
	, NULL
	, getdate()
	, N'system'
	, NULL
	, NULL
	)
go
---已持有投資標的轉換

INSERT ESERVICE_ADM.dbo.PARAMETER
    (
	PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER
	)
VALUES
   (
   (select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER)
	, N'eservice'
	, N'CONVERSION'
	, N'已持有投資標的轉換'
	, N'CONVERSION'
	, (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='ONLINE_CHANGE')
	, NULL
	, NULL
	, 1
	, NULL
	, NULL
	, getdate()
	, N'system'
	, NULL
	, NULL
	)
go

--投資標,限制投資比例大小值組
INSERT ESERVICE_ADM.dbo.PARAMETER_CATEGORY (PARAMETER_CATEGORY_ID, SYSTEM_ID, CATEGORY_CODE, CATEGORY_NAME, STATUS, CREATE_DATE, CREATE_USER)
VALUES ((select max(PARAMETER_CATEGORY_ID)+1 from ESERVICE_ADM.dbo.PARAMETER_CATEGORY), 'eservice', 'INVESTMENT_LIMIT_RATIO', N'投資標,限制投資比例大小值組', 1, getdate(), 'admin')
go

		--- 投資標,限制投資比例大小值 ('UC','UH','UR','UQ','UP','US','UU')
INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'UC_MIN', N'UC保單投資大小限制',
		N'10',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='INVESTMENT_LIMIT_RATIO'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go
INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'UC_MAX', N'UC保單投資大小限制',
		N'100',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='INVESTMENT_LIMIT_RATIO'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go
INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'UH_MIN', N'UH保單投資大小限制',
		N'10',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='INVESTMENT_LIMIT_RATIO'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go
INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'UH_MAX', N'UH保單投資大小限制',
		N'100',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='INVESTMENT_LIMIT_RATIO'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go
INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'UR_MIN', N'UR保單投資大小限制',
		N'10',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='INVESTMENT_LIMIT_RATIO'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go
INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'UR_MAX', N'UR保單投資大小限制',
		N'100',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='INVESTMENT_LIMIT_RATIO'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'UQ_MIN', N'UQ保單投資大小限制',
		N'10',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='INVESTMENT_LIMIT_RATIO'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go
INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'UQ_MAX', N'UQ保單投資大小限制',
		N'100',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='INVESTMENT_LIMIT_RATIO'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go
INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'UP_MIN', N'UP保單投資大小限制',
		N'10',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='INVESTMENT_LIMIT_RATIO'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go
INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'UP_MAX', N'UP保單投資大小限制',
		N'100',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='INVESTMENT_LIMIT_RATIO'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go
INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'US_MIN', N'US保單投資大小限制',
		N'10',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='INVESTMENT_LIMIT_RATIO'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go
INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'US_MAX', N'US保單投資大小限制',
		N'100',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='INVESTMENT_LIMIT_RATIO'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go
INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'UU_MIN', N'UU保單投資大小限制',
		N'10',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='INVESTMENT_LIMIT_RATIO'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go
INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'UU_MAX', N'UU保單投資大小限制',
		N'100',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='INVESTMENT_LIMIT_RATIO'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go




		--- 臺幣  欲轉出基金與比例,限制比例小值
INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'NTD_PROPORTION_MIN', N'臺幣欲轉出基金與比例,限制比例小值',
		N'10',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='INVESTMENT_LIMIT_RATIO'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go


		---美元   欲轉出基金與比例,限制比例小值
INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'USD_PROPORTION_MIN', N'美元欲轉出基金與比例,限制比例小值',
		N'10',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='INVESTMENT_LIMIT_RATIO'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go

		--- 臺幣  欲轉出基金單位,限制比例-此項是為金額,單位后台計算
INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'NTD_UNIT_MIN', N'臺幣欲轉出基金單位,限制比例-此項是為金額,單位后台計算',
		N'500',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='INVESTMENT_LIMIT_RATIO'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go


		---美元  欲轉出基金單位,限制比例-此項是為金額,單位后台計算
INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'USD_UNIT_MIN', N'美元欲轉出基金單位,限制比例-此項是為金額,單位后台計算',
		N'100',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='INVESTMENT_LIMIT_RATIO'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go




INSERT ESERVICE_ADM.dbo.PARAMETER
    (
	PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER
	)
VALUES
   (
   (select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER)
	, N'eservice'
	, N'DEPOSIT'
	, N'已持有投資標的轉換'
	, N'DEPOSIT'
	, (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='ONLINE_CHANGE')
	, NULL
	, NULL
	, 1
	, NULL
	, NULL
	, getdate()
	, N'system'
	, NULL
	, NULL
	)
go

-- 設定停損停利通知
INSERT ESERVICE_ADM.dbo.PARAMETER_CATEGORY (PARAMETER_CATEGORY_ID, SYSTEM_ID, CATEGORY_CODE, CATEGORY_NAME, STATUS, CREATE_DATE, CREATE_USER)
VALUES ((select max(PARAMETER_CATEGORY_ID)+1 from ESERVICE_ADM.dbo.PARAMETER_CATEGORY), 'eservice', 'NOTIFICATION', N'設定停損停利通知', 1, getdate(), 'admin')
go

--設定停損停利通知[備註]
INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'NOTIFICATION_REMARK1', N'設定停損停利通知',
		N'<li>若您的投資風險屬性為保守型，您可選擇保守型的基金RR1~RR2。</li>
          <li>若您的投資風險屬性為穩健型，您可選擇保守型及穩健型的基金RR1~RR4。</li>
          <li>若您的投資風險屬性為積極型型，您可選擇保守型、穩健型及積極型型的基金RR1~RR5。</li>
          <li>為確保保險商品符合您的投資能力及風險性，投資風險屬性若有變更，本公司將以您最新的風險屬性作為名下所有保單日後變更的評估依據。</li>',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='NOTIFICATION'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go

INSERT ESERVICE_ADM.dbo.PARAMETER
    (
	PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER
	)
VALUES
   (
   (select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER)
	, N'eservice'
	, N'CASH_PAYMENT'
	, N'收益分配或撥回資產分配方式'
	, N'CASH_PAYMENT'
	, (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='ONLINE_CHANGE')
	, NULL
	, NULL
	, 1
	, NULL
	, NULL
	, getdate()
	, N'system'
	, NULL
	, NULL
	)
go

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ( (SELECT MAX(PARAMETER_ID)+1 FROM  ESERVICE_ADM.dbo.PARAMETER ), N'eservice', N'WORDING_30026', N'未來保費投資標的與分配比例', N'可新增或移除投資標的', (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE = 'PAGE_WORDING'), 0, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL);

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ( (SELECT MAX(PARAMETER_ID)+1 FROM  ESERVICE_ADM.dbo.PARAMETER ), N'eservice', N'WORDING_30027', N'已持有投資標的轉換', N'可直接不同基金單位轉換', (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE = 'PAGE_WORDING'), 0, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL);

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ( (SELECT MAX(PARAMETER_ID)+1 FROM  ESERVICE_ADM.dbo.PARAMETER ), N'eservice', N'WORDING_30028', N'保單提領(贖回)', N'可執行保單提領贖回', (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE = 'PAGE_WORDING'), 0, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL);

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ( (SELECT MAX(PARAMETER_ID)+1 FROM  ESERVICE_ADM.dbo.PARAMETER ), N'eservice', N'WORDING_30029', N'設定停利停損通知', N'設定保單投資標的停損停利通知', (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE = 'PAGE_WORDING'), 0, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL);

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ( (SELECT MAX(PARAMETER_ID)+1 FROM  ESERVICE_ADM.dbo.PARAMETER ), N'eservice', N'WORDING_30030', N'收益分配或撥回資產分配方式', N'設定給付方式', (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE = 'PAGE_WORDING'), 0, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL);
go

-- 風險投資校驗
INSERT ESERVICE_ADM.dbo.PARAMETER_CATEGORY (PARAMETER_CATEGORY_ID, SYSTEM_ID, CATEGORY_CODE, CATEGORY_NAME, STATUS, CREATE_DATE, CREATE_USER)
VALUES ((select max(PARAMETER_CATEGORY_ID)+1 from ESERVICE_ADM.dbo.PARAMETER_CATEGORY), 'eservice', 'INVESTMENT_CHECK_LIST', N'風險投資校驗', 1, getdate(), 'admin')

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ( (SELECT MAX(PARAMETER_ID)+1 FROM  ESERVICE_ADM.dbo.PARAMETER ), N'eservice', N'PROCESS_INVESTMENT_LIST', N'投資進行中類型', N'INVESTMENT,CONVERSION,DEPOSIT,FUND_NOTIFICATION,CASH_PAYMENT,RISK_LEVEL', (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE = 'INVESTMENT_CHECK_LIST'), 0, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL);
go

---給管理人員的內容模板配置數據
-- 添加投資型首家件通知管理人員 MESSAGING_TEMPLATE条件
---【管理人員】
INSERT INTO  ESERVICE_ADM.[dbo].[MESSAGING_TEMPLATE]([MESSAGING_TEMPLATE_ID],[SYSTEM_ID],[MESSAGING_TEMPLATE_CODE],[MESSAGING_TEMPLATE_NAME],[STATUS],[TRIGGER_TYPE],[EVENT_TYPE],[SEND_TYPE],[SEND_TIME],[CIRCLE_TYPE],[CIRCLE_VALUE],[RECEIVER_MODE],[MESSAGING_SUBJECT],[MESSAGING_CONTENT],[CREATE_DATE],[CREATE_USER],[UPDATE_DATE],[UPDATE_USER])
VALUES((select max([MESSAGING_TEMPLATE_ID])+1 from ESERVICE_ADM.dbo.MESSAGING_TEMPLATE),N'eservice',N'ELIFE_MAIL_027',N'投資型首家件通知管理人員MAIL模版 ',3,N'api ',NULL,N'email',NULL,NULL,NULL,N'dynamic',N'投資型首家件通知管理人員內容',N'申請日期 : ${DATA}<br/>申請功能 :${APPLICATION_FUNCTION}<br/>申請狀態 : ${TransStatus}<br/>申請序號 :${TransNum}<br/>保單號碼 :${POLICY_NO}<br/>', getdate(),N'admin',getdate(),N'admin')
GO

INSERT ESERVICE_ADM.dbo.MESSAGING_PARAMETER (MESSAGING_TEMPLATE_ID,PARAMETER_ID) VALUES ((select MESSAGING_TEMPLATE_ID from ESERVICE_ADM.dbo.MESSAGING_TEMPLATE where MESSAGING_TEMPLATE_CODE = 'ELIFE_MAIL_027'),
		(select PARAMETER_ID from   ESERVICE_ADM.dbo.PARAMETER  where  PARAMETER_CODE='MSG_PARAM_DATA'));
GO

INSERT ESERVICE_ADM.dbo.MESSAGING_PARAMETER (MESSAGING_TEMPLATE_ID,PARAMETER_ID) VALUES ((select MESSAGING_TEMPLATE_ID from ESERVICE_ADM.dbo.MESSAGING_TEMPLATE where MESSAGING_TEMPLATE_CODE = 'ELIFE_MAIL_027'),
		(select PARAMETER_ID from   ESERVICE_ADM.dbo.PARAMETER  where  PARAMETER_CODE='MSG_PARAM_APPLICATION_FUNCTION'));
GO
INSERT ESERVICE_ADM.dbo.MESSAGING_PARAMETER (MESSAGING_TEMPLATE_ID,PARAMETER_ID) VALUES ((select MESSAGING_TEMPLATE_ID from ESERVICE_ADM.dbo.MESSAGING_TEMPLATE where MESSAGING_TEMPLATE_CODE = 'ELIFE_MAIL_027'),
		(select PARAMETER_ID from   ESERVICE_ADM.dbo.PARAMETER  where  PARAMETER_CODE='MSG_PARAM_TransStatus'));
GO
INSERT ESERVICE_ADM.dbo.MESSAGING_PARAMETER (MESSAGING_TEMPLATE_ID,PARAMETER_ID) VALUES ((select MESSAGING_TEMPLATE_ID from ESERVICE_ADM.dbo.MESSAGING_TEMPLATE where MESSAGING_TEMPLATE_CODE = 'ELIFE_MAIL_027'),
		(select PARAMETER_ID from   ESERVICE_ADM.dbo.PARAMETER  where  PARAMETER_CODE='MSG_PARAM_TransNum'));
GO
INSERT ESERVICE_ADM.dbo.MESSAGING_PARAMETER (MESSAGING_TEMPLATE_ID,PARAMETER_ID) VALUES ((select MESSAGING_TEMPLATE_ID from ESERVICE_ADM.dbo.MESSAGING_TEMPLATE where MESSAGING_TEMPLATE_CODE = 'ELIFE_MAIL_027'),
		(select PARAMETER_ID from   ESERVICE_ADM.dbo.PARAMETER  where  PARAMETER_CODE='MSG_PARAM_POLICY_NO'));
GO
--申請送出成功後給【管理】PARAMETER
INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'MSG_PARAM_APPLICATION_FUNCTION', N'通信模版參數-保單申請功能', N'APPLICATION_FUNCTION', (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='MessagingParameter'), NULL, NULL, 1, N'N', NULL, getdate(), N'admin', getdate(), N'admin')
go

--保戶前台線上申請送出成功後給【保戶】PARAMETER
INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'MSG_PARAM_TITLE', N'通信模版參數-保單標題', N'TITLE', (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='MessagingParameter'), NULL, NULL, 1, N'N', NULL, getdate(), N'admin', getdate(), N'admin')
go
--保戶前台線上申請送出成功後給【保戶】PARAMETER
INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'MSG_PARAM_MESSAGE', N'通信模版參數-保單消息', N'MESSAGE', (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='MessagingParameter'), NULL, NULL, 1, N'N', NULL, getdate(), N'admin', getdate(), N'admin')
go

---【保戶人員】
INSERT INTO  ESERVICE_ADM.[dbo].[MESSAGING_TEMPLATE]([MESSAGING_TEMPLATE_ID],[SYSTEM_ID],[MESSAGING_TEMPLATE_CODE],[MESSAGING_TEMPLATE_NAME],[STATUS],[TRIGGER_TYPE],[EVENT_TYPE],[SEND_TYPE],[SEND_TIME],[CIRCLE_TYPE],[CIRCLE_VALUE],[RECEIVER_MODE],[MESSAGING_SUBJECT],[MESSAGING_CONTENT],[CREATE_DATE],[CREATE_USER],[UPDATE_DATE],[UPDATE_USER])
VALUES((select max([MESSAGING_TEMPLATE_ID])+1 from ESERVICE_ADM.dbo.MESSAGING_TEMPLATE),N'eservice',N'ELIFE_MAIL_028',N'投資型首家件通知保戶MAIL模版 ',3,N'api ',NULL,N'email',NULL,NULL,NULL,N'dynamic',N'投資型首家件通知保戶內容',N'臺銀人壽投資型保單${TITLE}<br/>親愛的臺銀人壽保戶您好:${MESSAGE}<br/>如有疑問，請先至臺銀人壽會員專區查詢或請電洽:<br/>免費客服電話0800-011966<br/>市話服務:02-27849151轉保全科<br/>', getdate(),N'admin',getdate(),N'admin')
GO

INSERT ESERVICE_ADM.dbo.MESSAGING_PARAMETER (MESSAGING_TEMPLATE_ID,PARAMETER_ID) VALUES ((select MESSAGING_TEMPLATE_ID from ESERVICE_ADM.dbo.MESSAGING_TEMPLATE where MESSAGING_TEMPLATE_CODE = 'ELIFE_MAIL_028'),
		(select PARAMETER_ID from   ESERVICE_ADM.dbo.PARAMETER  where  PARAMETER_CODE='MSG_PARAM_TITLE'));
GO

INSERT ESERVICE_ADM.dbo.MESSAGING_PARAMETER (MESSAGING_TEMPLATE_ID,PARAMETER_ID) VALUES ((select MESSAGING_TEMPLATE_ID from ESERVICE_ADM.dbo.MESSAGING_TEMPLATE where MESSAGING_TEMPLATE_CODE = 'ELIFE_MAIL_028'),
		(select PARAMETER_ID from   ESERVICE_ADM.dbo.PARAMETER  where  PARAMETER_CODE='MSG_PARAM_MESSAGE'));
GO

INSERT ESERVICE_ADM.dbo.PARAMETER_CATEGORY (PARAMETER_CATEGORY_ID, SYSTEM_ID, CATEGORY_CODE, CATEGORY_NAME, STATUS, CREATE_DATE, CREATE_USER)
VALUES ((select max(PARAMETER_CATEGORY_ID)+1 from ESERVICE_ADM.dbo.PARAMETER_CATEGORY), 'eservice', 'DEPOST_PARAMETER_CATEGORY', N'保單提領(贖回)校驗', 1, getdate(), 'admin')

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'DEPOSIT_UC_NTD_MAX_PERCENT', N'UC臺幣轉出百分比',
		N'80',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='DEPOST_PARAMETER_CATEGORY'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go

INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'DEPOSIT_UC_NTD_MIN_PERCENT', N'UC臺幣轉出百分比',
		N'20',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='DEPOST_PARAMETER_CATEGORY'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go


INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'DEPOSIT_UC_NTD_MIN_VALUE', N'UC臺幣轉出金額',
		N'50000',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='DEPOST_PARAMETER_CATEGORY'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go


INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'DEPOSIT_UC_NTD_MAX_VALUE', N'UC臺幣轉出金額',
		N'2000000',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='DEPOST_PARAMETER_CATEGORY'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go


INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice', N'DEPOSIT_UC_NTD_SURPLUS_VALUE', N'UC臺幣剩余金額',
		N'10000',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='DEPOST_PARAMETER_CATEGORY'), NULL, NULL, 1, NULL, NULL, getdate(), N'admin', NULL, NULL)
go