
--SYSTEMS table
/*
insert into ESERVICE_ADM.dbo.SYSTEMS
(SYS_ID,SYS_NAME,CREATE_USER,CREATE_TIMESTAMP)
values
('eservice_api','保單網路服務API','admin',getdate())
go
*/

-------------------------------------聯絡資料變更暨保全聯盟鏈------------------------------------
use ESERVICE_ADM;
go

-----Insert PARAMETER_CATEGORY
INSERT ESERVICE_ADM.DBO.PARAMETER_CATEGORY(
	PARAMETER_CATEGORY_ID,
	SYSTEM_ID,
	CATEGORY_CODE,
	CATEGORY_NAME,
	REMARK,
	STATUS,
	CREATE_DATE,
	CREATE_USER,
	UPDATE_DATE,
	UPDATE_USER)
VALUES (
   (select max(PARAMETER_CATEGORY_ID)+1 from ESERVICE_ADM.DBO.PARAMETER_CATEGORY),
   'eservice_api',
   'SYS_CIO_SCHEDULE',
   '日程安排-系統屬性',
   NULL,
   '1.0000',
   GETDATE(),
   'admin',
   NULL,
   NULL
)
go

INSERT ESERVICE_ADM.DBO.PARAMETER_CATEGORY(
	PARAMETER_CATEGORY_ID,
	SYSTEM_ID,
	CATEGORY_CODE,
	CATEGORY_NAME,
	REMARK,
	STATUS,
	CREATE_DATE,
	CREATE_USER,
	UPDATE_DATE,
	UPDATE_USER)
VALUES (
   (select max(PARAMETER_CATEGORY_ID)+1 from ESERVICE_ADM.DBO.PARAMETER_CATEGORY),
   'eservice_api',
   'SYS_CIO_BASE_URL',
   '基本URL-系統屬性',
   NULL,
   '1.0000',
   GETDATE(),
   'admin',
   NULL,
   NULL
)
go

INSERT ESERVICE_ADM.DBO.PARAMETER_CATEGORY(
	PARAMETER_CATEGORY_ID,
	SYSTEM_ID,
	CATEGORY_CODE,
	CATEGORY_NAME,
	REMARK,
	STATUS,
	CREATE_DATE,
	CREATE_USER,
	UPDATE_DATE,
	UPDATE_USER)
VALUES (
   (select max(PARAMETER_CATEGORY_ID)+1 from ESERVICE_ADM.DBO.PARAMETER_CATEGORY),
   'eservice_api',
   'SYS_CIO_API_URL',
   '資源定位地址-系統屬性',
   NULL,
   '1.0000',
   GETDATE(),
   'admin',
   NULL,
   NULL
)
go

-----Insert PARAMETER for CIO Schedule
INSERT ESERVICE_ADM.DBO.PARAMETER (
     PARAMETER_ID, SYSTEM_ID, 
     PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, 
     PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, 
     ENCRYPT_TYPE, PARENT_PARAMETER_ID, 
     CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER) 
VALUES (
     (select max(PARAMETER_ID)+1 from ESERVICE_ADM.DBO.PARAMETER), N'eservice_api', 
     N'cron.api.cio.disable', N'cron.api.cio.disable', N'Y', 
     (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.DBO.PARAMETER_CATEGORY where CATEGORY_CODE='SYS_CIO_SCHEDULE'), 0, NULL, 1, 
     NULL, NULL, 
     GETDATE(), N'admin', NULL, NULL)
go

INSERT ESERVICE_ADM.DBO.PARAMETER (
     PARAMETER_ID, SYSTEM_ID, 
     PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, 
     PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, 
     ENCRYPT_TYPE, PARENT_PARAMETER_ID, 
     CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER) 
VALUES (
     (select max(PARAMETER_ID)+1 from ESERVICE_ADM.DBO.PARAMETER), N'eservice_api', 
     N'cron.cio201.expression', N'cron.cio201.expression', N'0 */5 * * * ?', 
     (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.DBO.PARAMETER_CATEGORY where CATEGORY_CODE='SYS_CIO_SCHEDULE'), 0, NULL, 1, 
     NULL, NULL, 
     GETDATE(), N'admin', NULL, NULL)
go

INSERT ESERVICE_ADM.DBO.PARAMETER (
     PARAMETER_ID, SYSTEM_ID, 
     PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, 
     PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, 
     ENCRYPT_TYPE, PARENT_PARAMETER_ID, 
     CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER) 
VALUES (
     (select max(PARAMETER_ID)+1 from ESERVICE_ADM.DBO.PARAMETER), N'eservice_api', 
     N'cron.cio202.expression', N'cron.cio202.expression', N'0 */5 * * * ?', 
     (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.DBO.PARAMETER_CATEGORY where CATEGORY_CODE='SYS_CIO_SCHEDULE'), 0, NULL, 1, 
     NULL, NULL, 
     GETDATE(), N'admin', NULL, NULL)
go
INSERT ESERVICE_ADM.DBO.PARAMETER (
     PARAMETER_ID, SYSTEM_ID, 
     PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, 
     PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, 
     ENCRYPT_TYPE, PARENT_PARAMETER_ID, 
     CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER) 
VALUES (
     (select max(PARAMETER_ID)+1 from ESERVICE_ADM.DBO.PARAMETER), N'eservice_api', 
     N'cron.cio203.expression', N'cron.cio203.expression', N'0 */5 * * * ?', 
     (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.DBO.PARAMETER_CATEGORY where CATEGORY_CODE='SYS_CIO_SCHEDULE'), 0, NULL, 1, 
     NULL, NULL, 
     GETDATE(), N'admin', NULL, NULL)
go

INSERT ESERVICE_ADM.DBO.PARAMETER (
     PARAMETER_ID, SYSTEM_ID, 
     PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, 
     PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, 
     ENCRYPT_TYPE, PARENT_PARAMETER_ID, 
     CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER) 
VALUES (
     (select max(PARAMETER_ID)+1 from ESERVICE_ADM.DBO.PARAMETER), N'eservice_api', 
     N'cron.cio204.expression', N'cron.cio204.expression', N'0 */5 * * * ?', 
     (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.DBO.PARAMETER_CATEGORY where CATEGORY_CODE='SYS_CIO_SCHEDULE'), 0, NULL, 1, 
     NULL, NULL, 
     GETDATE(), N'admin', NULL, NULL)
go

INSERT ESERVICE_ADM.DBO.PARAMETER (
     PARAMETER_ID, SYSTEM_ID, 
     PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, 
     PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, 
     ENCRYPT_TYPE, PARENT_PARAMETER_ID, 
     CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER) 
VALUES (
     (select max(PARAMETER_ID)+1 from ESERVICE_ADM.DBO.PARAMETER), N'eservice_api', 
     N'cron.cio206.expression', N'cron.cio206.expression', N'0 */5 * * * ?', 
     (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.DBO.PARAMETER_CATEGORY where CATEGORY_CODE='SYS_CIO_SCHEDULE'), 0, NULL, 1, 
     NULL, NULL, 
     GETDATE(), N'admin', NULL, NULL)
go


INSERT ESERVICE_ADM.DBO.PARAMETER (
     PARAMETER_ID, SYSTEM_ID, 
     PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, 
     PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, 
     ENCRYPT_TYPE, PARENT_PARAMETER_ID, 
     CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER) 
VALUES (
     (select max(PARAMETER_ID)+1 from ESERVICE_ADM.DBO.PARAMETER), N'eservice_api', 
     N'cron.saveCioToEserviceTrans.expression', N'cron.saveCioToEserviceTrans.expression', N'0 */5 * * * ?', 
     (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.DBO.PARAMETER_CATEGORY where CATEGORY_CODE='SYS_CIO_SCHEDULE'), 0, NULL, 1, 
     NULL, NULL, 
     GETDATE(), N'admin', NULL, NULL)
go

INSERT ESERVICE_ADM.DBO.PARAMETER (
     PARAMETER_ID, SYSTEM_ID, 
     PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, 
     PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, 
     ENCRYPT_TYPE, PARENT_PARAMETER_ID, 
     CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER) 
VALUES (
     (select max(PARAMETER_ID)+1 from ESERVICE_ADM.DBO.PARAMETER), N'eservice_api', 
     N'cron.saveCioToEserviceUnionTempTable.expression', N'cron.saveCioToEserviceUnionTempTable.expression', N'0 */5 * * * ?', 
     (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.DBO.PARAMETER_CATEGORY where CATEGORY_CODE='SYS_CIO_SCHEDULE'), 0, NULL, 1, 
     NULL, NULL, 
     GETDATE(), N'admin', NULL, NULL)
go



INSERT ESERVICE_ADM.DBO.PARAMETER (
     PARAMETER_ID, SYSTEM_ID, 
     PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, 
     PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, 
     ENCRYPT_TYPE, PARENT_PARAMETER_ID, 
     CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER) 
VALUES (
     (select max(PARAMETER_ID)+1 from ESERVICE_ADM.DBO.PARAMETER), N'eservice_api', 
     N'alliance.api.baseRrl', N'alliance.api.baseRrl', N'http://10.210.1.181/lia-api', 
     (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.DBO.PARAMETER_CATEGORY where CATEGORY_CODE='SYS_CIO_BASE_URL'), 0, NULL, 1, 
     NULL, NULL, 
     GETDATE(), N'admin', NULL, NULL)
go

INSERT ESERVICE_ADM.DBO.PARAMETER (
     PARAMETER_ID, SYSTEM_ID, 
     PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, 
     PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, 
     ENCRYPT_TYPE, PARENT_PARAMETER_ID, 
     CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER) 
VALUES (
     (select max(PARAMETER_ID)+1 from ESERVICE_ADM.DBO.PARAMETER), N'eservice_api', 
     N'alliance.api201.url', N'alliance.api201.url', N'http://10.210.1.181/lia-api/api/ext/lia201i', 
     (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.DBO.PARAMETER_CATEGORY where CATEGORY_CODE='SYS_CIO_API_URL'), 0, NULL, 1, 
     NULL, NULL, 
     GETDATE(), N'admin', NULL, NULL)
go

INSERT ESERVICE_ADM.DBO.PARAMETER (
     PARAMETER_ID, SYSTEM_ID, 
     PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, 
     PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, 
     ENCRYPT_TYPE, PARENT_PARAMETER_ID, 
     CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER) 
VALUES (
     (select max(PARAMETER_ID)+1 from ESERVICE_ADM.DBO.PARAMETER), N'eservice_api', 
     N'alliance.api202.url', N'alliance.api202.url', N'http://10.210.1.181/lia-api/api/ext/lia202i', 
     (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.DBO.PARAMETER_CATEGORY where CATEGORY_CODE='SYS_CIO_API_URL'), 0, NULL, 1, 
     NULL, NULL, 
     GETDATE(), N'admin', NULL, NULL)
go

INSERT ESERVICE_ADM.DBO.PARAMETER (
     PARAMETER_ID, SYSTEM_ID, 
     PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, 
     PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, 
     ENCRYPT_TYPE, PARENT_PARAMETER_ID, 
     CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER) 
VALUES (
     (select max(PARAMETER_ID)+1 from ESERVICE_ADM.DBO.PARAMETER), N'eservice_api', 
     N'alliance.api203.url', N'alliance.api203.url', N'http://10.210.1.181/lia-api/api/ext/lia203i', 
     (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.DBO.PARAMETER_CATEGORY where CATEGORY_CODE='SYS_CIO_API_URL'), 0, NULL, 1, 
     NULL, NULL, 
     GETDATE(), N'admin', NULL, NULL)
go

INSERT ESERVICE_ADM.DBO.PARAMETER (
     PARAMETER_ID, SYSTEM_ID, 
     PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, 
     PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, 
     ENCRYPT_TYPE, PARENT_PARAMETER_ID, 
     CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER) 
VALUES (
     (select max(PARAMETER_ID)+1 from ESERVICE_ADM.DBO.PARAMETER), N'eservice_api', 
     N'alliance.api204.url', N'alliance.api204.url', N'http://10.210.1.181/lia-api/api/ext/lia204i', 
     (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.DBO.PARAMETER_CATEGORY where CATEGORY_CODE='SYS_CIO_API_URL'), 0, NULL, 1, 
     NULL, NULL, 
     GETDATE(), N'admin', NULL, NULL)
go
 
INSERT ESERVICE_ADM.DBO.PARAMETER (
     PARAMETER_ID, SYSTEM_ID, 
     PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, 
     PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, 
     ENCRYPT_TYPE, PARENT_PARAMETER_ID, 
     CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER) 
VALUES (
     (select max(PARAMETER_ID)+1 from ESERVICE_ADM.DBO.PARAMETER), N'eservice_api', 
     N'alliance.api206.url', N'alliance.api206.url', N'http://10.210.1.181/lia-api/api/ext/lia206i', 
     (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.DBO.PARAMETER_CATEGORY where CATEGORY_CODE='SYS_CIO_API_URL'), 0, NULL, 1, 
     NULL, NULL, 
     GETDATE(), N'admin', NULL, NULL)
go

--PARAMETER_CATEGORY
insert into ESERVICE_ADM.dbo.PARAMETER_CATEGORY
	(PARAMETER_CATEGORY_ID,SYSTEM_ID,CATEGORY_CODE,CATEGORY_NAME,REMARK,STATUS,CREATE_DATE,CREATE_USER,UPDATE_DATE,UPDATE_USER)
values
	(
		(select max(PARAMETER_CATEGORY_ID)+1 from ESERVICE_ADM.dbo.PARAMETER_CATEGORY),
		'eservice_adm',
		'SECURITY_ALLIANCE_ALERT_MAIL',
		'保全收件轉件通知',
		'轉存eservcie成功或失敗均需通知作業人員',
		'1',
		getdate(),
		'admin',
		getdate(),
		'admin'
	);
go
--PARAMETER
insert into ESERVICE_ADM.dbo.PARAMETER
	(PARAMETER_ID,SYSTEM_ID,PARAMETER_CODE,PARAMETER_NAME,PARAMETER_VALUE,PARAMETER_CATEGORY_ID,STATUS,ENCRYPT_TYPE,CREATE_DATE,CREATE_USER,UPDATE_DATE,UPDATE_USER)
values
	(
		(select max(PARAMETER_ID)+1 from ESERVICE_ADM.dbo.PARAMETER),
		'eservice_adm',
		'security_alliance_twfhclife_adm',
		'保全作業通知人員',
		'203216@twfhclife.com.tw;190064@twfhclife.com.tw;203352@twfhclife.com.tw;203352@twfhclife.com.tw;203990@twfhclife.com.tw;202712@twfhclife.com.tw',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='SECURITY_ALLIANCE_ALERT_MAIL'),
		'1',
		'N',
		getdate(),
		'admin',
		getdate(),
		'admin'
	);
go

---API調用聯盟API【無響應】，上限参数值
INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice_api', N'API_NO_RESPONSE_NUMBER', N'通信模版參數-API無響應超過最大次數模版'
, N'5',
(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='MessagingParameter'), NULL, NULL, 0, N'N', NULL, getdate(), N'admin', getdate(), N'admin')
go



--- API联盟【调用失败】，进行发送邮件参数
INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice_api', N'MSG_PARAM_PROGRAM_NAME', N'通信模板參數-批次排程的程式名稱'
, N'PROGRAM_NAME',
(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='MessagingParameter'), NULL, NULL, 1, N'N', NULL, getdate(), N'admin', getdate(), N'admin')
go
INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice_api', N'MSG_PARAM_NUMBER', N'通信模板參數-程式行號'
, N'NUMBER',
(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='MessagingParameter'), NULL, NULL, 1, N'N', NULL, getdate(), N'admin', getdate(), N'admin')
go
INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice_api', N'MSG_PARAM_DATA', N'通信模板參數-發生時間'
, N'DATA',
(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='MessagingParameter'), NULL, NULL, 1, N'N', NULL, getdate(), N'admin', getdate(), N'admin')
go
INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice_api', N'MSG_PARAM_CODE', N'通信模板參數- API(代號)'
, N'CODE',
(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='MessagingParameter'), NULL, NULL, 1, N'N', NULL, getdate(), N'admin', getdate(), N'admin')
go

-- API联盟【调用失败】发送邮件信息模板
INSERT INTO ESERVICE_ADM.[dbo].[MESSAGING_TEMPLATE]([MESSAGING_TEMPLATE_ID],[SYSTEM_ID],[MESSAGING_TEMPLATE_CODE],[MESSAGING_TEMPLATE_NAME],[STATUS],[TRIGGER_TYPE],[EVENT_TYPE],[SEND_TYPE],[SEND_TIME],[CIRCLE_TYPE],[CIRCLE_VALUE],[RECEIVER_MODE],[MESSAGING_SUBJECT],[MESSAGING_CONTENT],[CREATE_DATE],[CREATE_USER],[UPDATE_DATE],[UPDATE_USER])
VALUES((select max([MESSAGING_TEMPLATE_ID])+1 from ESERVICE_ADM.dbo.MESSAGING_TEMPLATE),N'eservice_api',N'API_NO_MAIL_012',N'聯盟相關API調不通【無回應】通知管理人員MAIL模版 '
,3,N'api ',NULL,N'email',NULL,NULL,NULL,N'dynamic',N'聯盟相關API調不通【無回應】通知管理人員MAIL模版'
,N'保全聯盟鏈 - 批次排程 - API呼叫異常</br></br>[${PROGRAM_NAME}] 第[${NUMBER}]行 API(${CODE}) 於 [${DATA}] 呼叫失敗', getdate(),N'admin',getdate(),N'admin')
GO
--- 添加通知【管理人員】API联盟调用失败[MESSAGING_PARAMETER]表
INSERT INTO  ESERVICE_ADM.[dbo].[MESSAGING_PARAMETER]
           ([MESSAGING_TEMPLATE_ID]
           ,[PARAMETER_ID])
     VALUES
           ((select MESSAGING_TEMPLATE_ID  FROM   ESERVICE_ADM.dbo.[MESSAGING_TEMPLATE]  WHERE SYSTEM_ID='eservice_api' and [MESSAGING_TEMPLATE_CODE]='API_NO_MAIL_012')
           ,(select PARAMETER_ID  FROM   ESERVICE_ADM.dbo.PARAMETER  WHERE SYSTEM_ID='eservice_api' and PARAMETER_CODE='MSG_PARAM_PROGRAM_NAME')
		   )
GO
INSERT INTO  ESERVICE_ADM.[dbo].[MESSAGING_PARAMETER]
           ([MESSAGING_TEMPLATE_ID]
           ,[PARAMETER_ID])
     VALUES
           ((select MESSAGING_TEMPLATE_ID  FROM   ESERVICE_ADM.dbo.[MESSAGING_TEMPLATE]  WHERE SYSTEM_ID='eservice_api' and [MESSAGING_TEMPLATE_CODE]='API_NO_MAIL_012')
           ,(select PARAMETER_ID  FROM   ESERVICE_ADM.dbo.PARAMETER  WHERE SYSTEM_ID='eservice_api' and PARAMETER_CODE='MSG_PARAM_NUMBER')
		   )
GO
INSERT INTO  ESERVICE_ADM.[dbo].[MESSAGING_PARAMETER]
           ([MESSAGING_TEMPLATE_ID]
           ,[PARAMETER_ID])
     VALUES
           ((select MESSAGING_TEMPLATE_ID  FROM   ESERVICE_ADM.dbo.[MESSAGING_TEMPLATE]  WHERE SYSTEM_ID='eservice_api' and [MESSAGING_TEMPLATE_CODE]='API_NO_MAIL_012')
           ,(select PARAMETER_ID  FROM   ESERVICE_ADM.dbo.PARAMETER  WHERE SYSTEM_ID='eservice_api' and PARAMETER_CODE='MSG_PARAM_DATA')
		   )
GO
INSERT INTO  ESERVICE_ADM.[dbo].[MESSAGING_PARAMETER]
           ([MESSAGING_TEMPLATE_ID]
           ,[PARAMETER_ID])
     VALUES
           ((select MESSAGING_TEMPLATE_ID  FROM   ESERVICE_ADM.dbo.[MESSAGING_TEMPLATE]  WHERE SYSTEM_ID='eservice_api' and [MESSAGING_TEMPLATE_CODE]='API_NO_MAIL_012')
           ,(select PARAMETER_ID  FROM   ESERVICE_ADM.dbo.PARAMETER  WHERE SYSTEM_ID='eservice_api' and PARAMETER_CODE='MSG_PARAM_CODE')
		   )
GO




--- 轉修eservice進件過程中有出程錯誤時通知後台管理人員，进行发送邮件参数
INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice_api', N'MSG_PARAM_EXCEPTION_LOG', N'通信模板參數-日誌'
, N'EXCEPTION_LOG',
(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='MessagingParameter'), NULL, NULL, 1, N'N', NULL, getdate(), N'admin', getdate(), N'admin')
go

-- 【轉修eservice進件過程中有出程錯誤時】通知後台管理人員 发送邮件，
INSERT INTO ESERVICE_ADM.[dbo].[MESSAGING_TEMPLATE]([MESSAGING_TEMPLATE_ID],[SYSTEM_ID],[MESSAGING_TEMPLATE_CODE],[MESSAGING_TEMPLATE_NAME],[STATUS],[TRIGGER_TYPE],[EVENT_TYPE],[SEND_TYPE],[SEND_TIME],[CIRCLE_TYPE],[CIRCLE_VALUE],[RECEIVER_MODE],[MESSAGING_SUBJECT],[MESSAGING_CONTENT],[CREATE_DATE],[CREATE_USER],[UPDATE_DATE],[UPDATE_USER])
VALUES((select max([MESSAGING_TEMPLATE_ID])+1 from ESERVICE_ADM.dbo.MESSAGING_TEMPLATE),N'eservice_api',N'TRANSFER_MAIL_013',N'【轉修eservice進件過程失败】，通知管理人員MAIL模版'
,3,N'api ',NULL,N'email',NULL,NULL,NULL,N'dynamic',N'【轉修eservice進件過程失败】，通知管理人員MAIL模版'
,N'保全聯盟鏈 - 批次排程 -轉收件 轉入eservice進件異常<br/>[${PROGRAM_NAME}] 第[${NUMBER}]行 於 [${DATA}] 執行失敗<br/>Exception log:<br/>${EXCEPTION_LOG}', getdate(),N'admin',getdate(),N'admin')
GO
--- 【轉修eservice進件過程中有出程錯誤時】通知後台管理人員[MESSAGING_PARAMETER]
INSERT INTO  ESERVICE_ADM.[dbo].[MESSAGING_PARAMETER]
           ([MESSAGING_TEMPLATE_ID]
           ,[PARAMETER_ID])
     VALUES
           ((select MESSAGING_TEMPLATE_ID  FROM   ESERVICE_ADM.dbo.[MESSAGING_TEMPLATE]  WHERE SYSTEM_ID='eservice_api' and [MESSAGING_TEMPLATE_CODE]='TRANSFER_MAIL_013')
           ,(select PARAMETER_ID  FROM   ESERVICE_ADM.dbo.PARAMETER  WHERE SYSTEM_ID='eservice_api' and PARAMETER_CODE='MSG_PARAM_PROGRAM_NAME')
		   )
GO
INSERT INTO  ESERVICE_ADM.[dbo].[MESSAGING_PARAMETER]
           ([MESSAGING_TEMPLATE_ID]
           ,[PARAMETER_ID])
     VALUES
           ((select MESSAGING_TEMPLATE_ID  FROM   ESERVICE_ADM.dbo.[MESSAGING_TEMPLATE]  WHERE SYSTEM_ID='eservice_api' and [MESSAGING_TEMPLATE_CODE]='TRANSFER_MAIL_013')
           ,(select PARAMETER_ID  FROM   ESERVICE_ADM.dbo.PARAMETER  WHERE SYSTEM_ID='eservice_api' and PARAMETER_CODE='MSG_PARAM_NUMBER')
		   )
GO

INSERT INTO  ESERVICE_ADM.[dbo].[MESSAGING_PARAMETER]
           ([MESSAGING_TEMPLATE_ID]
           ,[PARAMETER_ID])
     VALUES
           ((select MESSAGING_TEMPLATE_ID  FROM   ESERVICE_ADM.dbo.[MESSAGING_TEMPLATE]  WHERE SYSTEM_ID='eservice_api' and [MESSAGING_TEMPLATE_CODE]='TRANSFER_MAIL_013')
           ,(select PARAMETER_ID  FROM   ESERVICE_ADM.dbo.PARAMETER  WHERE SYSTEM_ID='eservice_api' and PARAMETER_CODE='MSG_PARAM_DATA')
		   )
GO

INSERT INTO  ESERVICE_ADM.[dbo].[MESSAGING_PARAMETER]
           ([MESSAGING_TEMPLATE_ID]
           ,[PARAMETER_ID])
     VALUES
           ((select MESSAGING_TEMPLATE_ID  FROM   ESERVICE_ADM.dbo.[MESSAGING_TEMPLATE]  WHERE SYSTEM_ID='eservice_api' and [MESSAGING_TEMPLATE_CODE]='TRANSFER_MAIL_013')
           ,(select PARAMETER_ID  FROM   ESERVICE_ADM.dbo.PARAMETER  WHERE SYSTEM_ID='eservice_api' and PARAMETER_CODE='MSG_PARAM_EXCEPTION_LOG')
		   )
GO

-- 轉修eservice進件過程中【一般件(非異常件)會通知管理人員與保戶】，进行发送邮件参数
INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice_api', N'MSG_PARAM_POLICY_NUMBER', N'通信模板參數-轉收件保單編號'
, N'POLICY_NUMBER',
(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='MessagingParameter'), NULL, NULL, 1, N'N', NULL, getdate(), N'admin', getdate(), N'admin')
go

-- 轉修eservice進件過程中【一般件(非異常件)會通知管理人員】发送邮件，
INSERT INTO ESERVICE_ADM.[dbo].[MESSAGING_TEMPLATE]([MESSAGING_TEMPLATE_ID],[SYSTEM_ID],[MESSAGING_TEMPLATE_CODE],[MESSAGING_TEMPLATE_NAME],[STATUS],[TRIGGER_TYPE],[EVENT_TYPE],[SEND_TYPE],[SEND_TIME],[CIRCLE_TYPE],[CIRCLE_VALUE],[RECEIVER_MODE],[MESSAGING_SUBJECT],[MESSAGING_CONTENT],[CREATE_DATE],[CREATE_USER],[UPDATE_DATE],[UPDATE_USER])
VALUES((select max([MESSAGING_TEMPLATE_ID])+1 from ESERVICE_ADM.dbo.MESSAGING_TEMPLATE),N'eservice_api',N'TRANSFER_MAIL_014',N'【轉修eservice成功進件一般件】通知管理人員MAIL模版'
,3,N'api ',NULL,N'email',NULL,NULL,NULL,N'dynamic',N'【轉修eservice成功進件一般件】通知管理人員MAIL模版'
,N'保全聯盟鏈 - 轉收件 <br/>已接收 保單編號: [${POLICY_NUMBER}]', getdate(),N'admin',getdate(),N'admin')
GO
-- 轉修eservice進件過程中【一般件(非異常件)會通知保戶】发送邮件
INSERT INTO ESERVICE_ADM.[dbo].[MESSAGING_TEMPLATE]([MESSAGING_TEMPLATE_ID],[SYSTEM_ID],[MESSAGING_TEMPLATE_CODE],[MESSAGING_TEMPLATE_NAME],[STATUS],[TRIGGER_TYPE],[EVENT_TYPE],[SEND_TYPE],[SEND_TIME],[CIRCLE_TYPE],[CIRCLE_VALUE],[RECEIVER_MODE],[MESSAGING_SUBJECT],[MESSAGING_CONTENT],[CREATE_DATE],[CREATE_USER],[UPDATE_DATE],[UPDATE_USER])
VALUES((select max([MESSAGING_TEMPLATE_ID])+1 from ESERVICE_ADM.dbo.MESSAGING_TEMPLATE),N'eservice_api',N'TRANSFER_MAIL_015',N'【轉修eservice成功進件一般件】通知保戶MAIL模版'
,3,N'api ',NULL,N'email',NULL,NULL,NULL,N'dynamic',N'【轉修eservice成功進件一般件】通知保戶MAIL模版'
,N'親愛的臺銀人壽保戶您好！ <br/>本公司已收受您的保全聯盟鏈轉送辦理契約內容變更申請案，並將盡速為您辦理。<br/>如有疑問，請洽本公司電話服務中心0800-011966', getdate(),N'admin',getdate(),N'admin')
GO
---  轉修eservice進件過程中【一般件(非異常件)會通知保戶】[MESSAGING_PARAMETER]
INSERT INTO  ESERVICE_ADM.[dbo].[MESSAGING_PARAMETER]
           ([MESSAGING_TEMPLATE_ID]
           ,[PARAMETER_ID])
     VALUES
           ((select MESSAGING_TEMPLATE_ID  FROM   ESERVICE_ADM.dbo.[MESSAGING_TEMPLATE]  WHERE SYSTEM_ID='eservice_api' and [MESSAGING_TEMPLATE_CODE]='TRANSFER_MAIL_014')
           ,(select PARAMETER_ID  FROM   ESERVICE_ADM.dbo.PARAMETER  WHERE SYSTEM_ID='eservice_api' and PARAMETER_CODE='MSG_PARAM_POLICY_NUMBER')
		   )
GO




-- 將轉收至本公司的案件【資料及影像成功存入本公司系統】，通知後台管理人員发送邮件
INSERT INTO ESERVICE_ADM.[dbo].[MESSAGING_TEMPLATE]([MESSAGING_TEMPLATE_ID],[SYSTEM_ID],[MESSAGING_TEMPLATE_CODE],[MESSAGING_TEMPLATE_NAME],[STATUS],[TRIGGER_TYPE],[EVENT_TYPE],[SEND_TYPE],[SEND_TIME],[CIRCLE_TYPE],[CIRCLE_VALUE],[RECEIVER_MODE],[MESSAGING_SUBJECT],[MESSAGING_CONTENT],[CREATE_DATE],[CREATE_USER],[UPDATE_DATE],[UPDATE_USER])
VALUES((select max([MESSAGING_TEMPLATE_ID])+1 from ESERVICE_ADM.dbo.MESSAGING_TEMPLATE),N'eservice_api',N'TRANSFER_MAIL_016',N'【資料及影像成功存入本公司系統】通知管理MAIL模版'
,3,N'api ',NULL,N'email',NULL,NULL,NULL,N'dynamic',N'【資料及影像成功存入本公司系統】通知管理MAIL模版'
,N'保全聯盟鏈 - 轉收件 <br/>案件資料及影像已存入本公司系統<br/>保單編號: [${POLICY_NUMBER}]', getdate(),N'admin',getdate(),N'admin')
GO

--- 【轉修eservice進件過程中有出程錯誤時】通知後台管理人員[MESSAGING_PARAMETER]
INSERT INTO  ESERVICE_ADM.[dbo].[MESSAGING_PARAMETER]
           ([MESSAGING_TEMPLATE_ID]
           ,[PARAMETER_ID])
     VALUES
           ((select MESSAGING_TEMPLATE_ID  FROM   ESERVICE_ADM.dbo.[MESSAGING_TEMPLATE]  WHERE SYSTEM_ID='eservice_api' and [MESSAGING_TEMPLATE_CODE]='TRANSFER_MAIL_016')
           ,(select PARAMETER_ID  FROM   ESERVICE_ADM.dbo.PARAMETER  WHERE SYSTEM_ID='eservice_api' and PARAMETER_CODE='MSG_PARAM_POLICY_NUMBER')
		   )
GO





-- 將轉收至本公司的案件【資料及影像存入失败本公司系統】，通知後台管理人員发送邮件
INSERT INTO ESERVICE_ADM.[dbo].[MESSAGING_TEMPLATE]([MESSAGING_TEMPLATE_ID],[SYSTEM_ID],[MESSAGING_TEMPLATE_CODE],[MESSAGING_TEMPLATE_NAME],[STATUS],[TRIGGER_TYPE],[EVENT_TYPE],[SEND_TYPE],[SEND_TIME],[CIRCLE_TYPE],[CIRCLE_VALUE],[RECEIVER_MODE],[MESSAGING_SUBJECT],[MESSAGING_CONTENT],[CREATE_DATE],[CREATE_USER],[UPDATE_DATE],[UPDATE_USER])
VALUES((select max([MESSAGING_TEMPLATE_ID])+1 from ESERVICE_ADM.dbo.MESSAGING_TEMPLATE),N'eservice_api',N'TRANSFER_MAIL_017',N'【資料及影像存入失敗本公司系統】通知管理MAIL模版'
,3,N'api ',NULL,N'email',NULL,NULL,NULL,N'dynamic',N'【資料及影像存入失敗本公司系統】通知管理MAIL模版'
,N'保全聯盟鏈 - 批次排程 - 轉收件 案件資料及影像存入本公司系統失敗<br/>[${PROGRAM_NAME}] 第[${NUMBER}]行 於 [${DATA}] 執行失敗<br/>Exception log:<br/>${EXCEPTION_LOG}', getdate(),N'admin',getdate(),N'admin')
GO


--- 將轉收至本公司的案件【資料及影像存入失败本公司系統】通知後台管理人員[MESSAGING_PARAMETER]
INSERT INTO  ESERVICE_ADM.[dbo].[MESSAGING_PARAMETER]
           ([MESSAGING_TEMPLATE_ID]
           ,[PARAMETER_ID])
     VALUES
           ((select MESSAGING_TEMPLATE_ID  FROM   ESERVICE_ADM.dbo.[MESSAGING_TEMPLATE]  WHERE SYSTEM_ID='eservice_api' and [MESSAGING_TEMPLATE_CODE]='TRANSFER_MAIL_017')
           ,(select PARAMETER_ID  FROM   ESERVICE_ADM.dbo.PARAMETER  WHERE SYSTEM_ID='eservice_api' and PARAMETER_CODE='MSG_PARAM_PROGRAM_NAME')
		   )
GO
INSERT INTO  ESERVICE_ADM.[dbo].[MESSAGING_PARAMETER]
           ([MESSAGING_TEMPLATE_ID]
           ,[PARAMETER_ID])
     VALUES
           ((select MESSAGING_TEMPLATE_ID  FROM   ESERVICE_ADM.dbo.[MESSAGING_TEMPLATE]  WHERE SYSTEM_ID='eservice_api' and [MESSAGING_TEMPLATE_CODE]='TRANSFER_MAIL_017')
           ,(select PARAMETER_ID  FROM   ESERVICE_ADM.dbo.PARAMETER  WHERE SYSTEM_ID='eservice_api' and PARAMETER_CODE='MSG_PARAM_NUMBER')
		   )
GO

INSERT INTO  ESERVICE_ADM.[dbo].[MESSAGING_PARAMETER]
           ([MESSAGING_TEMPLATE_ID]
           ,[PARAMETER_ID])
     VALUES
           ((select MESSAGING_TEMPLATE_ID  FROM   ESERVICE_ADM.dbo.[MESSAGING_TEMPLATE]  WHERE SYSTEM_ID='eservice_api' and [MESSAGING_TEMPLATE_CODE]='TRANSFER_MAIL_017')
           ,(select PARAMETER_ID  FROM   ESERVICE_ADM.dbo.PARAMETER  WHERE SYSTEM_ID='eservice_api' and PARAMETER_CODE='MSG_PARAM_DATA')
		   )
GO
INSERT INTO  ESERVICE_ADM.[dbo].[MESSAGING_PARAMETER]
           ([MESSAGING_TEMPLATE_ID]
           ,[PARAMETER_ID])
     VALUES
           ((select MESSAGING_TEMPLATE_ID  FROM   ESERVICE_ADM.dbo.[MESSAGING_TEMPLATE]  WHERE SYSTEM_ID='eservice_api' and [MESSAGING_TEMPLATE_CODE]='TRANSFER_MAIL_017')
           ,(select PARAMETER_ID  FROM   ESERVICE_ADM.dbo.PARAMETER  WHERE SYSTEM_ID='eservice_api' and PARAMETER_CODE='MSG_PARAM_EXCEPTION_LOG')
		   )
GO



-----轉修eservice進件-已註記異常件-處理通知後台管理人員，进行发送邮件参数
  INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
  VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice_api', N'MSG_PARAM_EMAIL', N'通信模板參數-保戶郵件地址'
  , N'EMAIL',
  (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='MessagingParameter'), NULL, NULL, 1, N'N', NULL, getdate(), N'admin', getdate(), N'admin')
  go

  -- 【轉修eservice進件-已註記異常件-處理】通知後台管理人員 发送邮件，
  INSERT INTO ESERVICE_ADM.[dbo].[MESSAGING_TEMPLATE]([MESSAGING_TEMPLATE_ID],[SYSTEM_ID],[MESSAGING_TEMPLATE_CODE],[MESSAGING_TEMPLATE_NAME],[STATUS],[TRIGGER_TYPE],[EVENT_TYPE],[SEND_TYPE],[SEND_TIME],[CIRCLE_TYPE],[CIRCLE_VALUE],[RECEIVER_MODE],[MESSAGING_SUBJECT],[MESSAGING_CONTENT],[CREATE_DATE],[CREATE_USER],[UPDATE_DATE],[UPDATE_USER])
  VALUES((select max([MESSAGING_TEMPLATE_ID])+1 from ESERVICE_ADM.dbo.MESSAGING_TEMPLATE),N'eservice_api',N'TRANSFER_MAIL_018',N'【已註記異常件處理】，通知管理人員MAIL模版'
  ,3,N'api ',NULL,N'email',NULL,NULL,NULL,N'dynamic',N'【已註記異常件處理】，通知管理人員MAIL模版'
  ,N'保全聯盟鏈 - 轉收件 <br/>保戶欲修改的資料不符合本公司規範，[${EMAIL}]<br/>可至後台查詢，連結: [http://localhost:8080/eservice_adm/onlineChange]<br/>查詢條件為[註記異常件] 建立時間為 [${DATA}]', getdate(),N'admin',getdate(),N'admin')
  GO

  --- 【轉修eservice進件-已註記異常件-處理】通知後台管理人員[MESSAGING_PARAMETER]
  INSERT INTO  ESERVICE_ADM.[dbo].[MESSAGING_PARAMETER]
             ([MESSAGING_TEMPLATE_ID]
             ,[PARAMETER_ID])
       VALUES
             ((select MESSAGING_TEMPLATE_ID  FROM   ESERVICE_ADM.dbo.[MESSAGING_TEMPLATE]  WHERE SYSTEM_ID='eservice_api' and [MESSAGING_TEMPLATE_CODE]='TRANSFER_MAIL_018')
             ,(select PARAMETER_ID  FROM   ESERVICE_ADM.dbo.PARAMETER  WHERE SYSTEM_ID='eservice_api' and PARAMETER_CODE='MSG_PARAM_EMAIL')
  		   )
  GO
  INSERT INTO  ESERVICE_ADM.[dbo].[MESSAGING_PARAMETER]
             ([MESSAGING_TEMPLATE_ID]
             ,[PARAMETER_ID])
       VALUES
             ((select MESSAGING_TEMPLATE_ID  FROM   ESERVICE_ADM.dbo.[MESSAGING_TEMPLATE]  WHERE SYSTEM_ID='eservice_api' and [MESSAGING_TEMPLATE_CODE]='TRANSFER_MAIL_018')
             ,(select PARAMETER_ID  FROM   ESERVICE_ADM.dbo.PARAMETER  WHERE SYSTEM_ID='eservice_api' and PARAMETER_CODE='MSG_PARAM_DATA')
  		   )
  GO

  -- 【轉修eservice進件-已註記異常件-處理】通知保戶人員 发送邮件，
  INSERT INTO ESERVICE_ADM.[dbo].[MESSAGING_TEMPLATE]([MESSAGING_TEMPLATE_ID],[SYSTEM_ID],[MESSAGING_TEMPLATE_CODE],[MESSAGING_TEMPLATE_NAME],[STATUS],[TRIGGER_TYPE],[EVENT_TYPE],[SEND_TYPE],[SEND_TIME],[CIRCLE_TYPE],[CIRCLE_VALUE],[RECEIVER_MODE],[MESSAGING_SUBJECT],[MESSAGING_CONTENT],[CREATE_DATE],[CREATE_USER],[UPDATE_DATE],[UPDATE_USER])
  VALUES((select max([MESSAGING_TEMPLATE_ID])+1 from ESERVICE_ADM.dbo.MESSAGING_TEMPLATE),N'eservice_api',N'TRANSFER_MAIL_019',N'【已註記異常件處理】，通知保戶人員MAIL模版'
  ,3,N'api ',NULL,N'email',NULL,NULL,NULL,N'dynamic',N'【已註記異常件處理】，通知保戶人員MAIL模版'
  ,N'親愛的臺銀人壽保戶您好！ <br/>台端經保全聯盟鏈轉送保單變更資料，因本公司未能受理線上要/被保人姓名或ID變更，故本次變更內容尚未辦理完成。<br/>請點選連結下載 契約內容申請書(連結: https://www.twfhclife.com.tw/wp-content/uploads/保險契約內容變更申請書.pdf)，並檢附相關證明文件紙本辦理此次變更事項。<br/>若本次有辦理要被保人姓名變更，請同時下載 變更簽章印鑑卡(連結: https://www.twfhclife.com.tw/wp-content/uploads/變更簽章印鑑卡.pdf)，辦理簽章樣式變更<br/>如需任何服務，歡迎聯絡電話服務中心 0800-011966', getdate(),N'admin',getdate(),N'admin')
  GO


--管理人員MAIL模版
-- 從壽險核心接收回案件狀態回饋檔後發送(狀態為已完成或失敗)，进行发送邮件参数
  INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
  VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice_batch', N'MSG_PARAM_POLICY_TYPE', N'保全聯盟鏈-類型'
  , N'POLICY_TYPE',
  (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='MessagingParameter'), NULL, NULL, 1, N'N', NULL, getdate(), N'admin', getdate(), N'admin')
  go
    INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
  VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice_batch', N'MSG_PARAM_POLICY_STATUS', N'保全聯盟鏈-迴響狀態'
  , N'POLICY_STATUS',
  (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='MessagingParameter'), NULL, NULL, 1, N'N', NULL, getdate(), N'admin', getdate(), N'admin')
  go

  -- 從壽險核心接收回案件狀態回饋檔後發送(狀態為已完成或失敗)通知管理人員MAIL模版
INSERT INTO ESERVICE_ADM.[dbo].[MESSAGING_TEMPLATE]([MESSAGING_TEMPLATE_ID],[SYSTEM_ID],[MESSAGING_TEMPLATE_CODE],[MESSAGING_TEMPLATE_NAME],[STATUS],[TRIGGER_TYPE],[EVENT_TYPE],[SEND_TYPE],[SEND_TIME],[CIRCLE_TYPE],[CIRCLE_VALUE],[RECEIVER_MODE],[MESSAGING_SUBJECT],[MESSAGING_CONTENT],[CREATE_DATE],[CREATE_USER],[UPDATE_DATE],[UPDATE_USER])
VALUES((select max([MESSAGING_TEMPLATE_ID])+1 from ESERVICE_ADM.dbo.MESSAGING_TEMPLATE),N'eservice_batch',N'TRANSFER_MAIL_020',N'【從壽險核心接收回案件狀態】管理MAIL模版'
,3,N'api ',NULL,N'email',NULL,NULL,NULL,N'dynamic',N'【從壽險核心接收回案件狀態】管理MAIL模版'
,N'保全聯盟鏈 - [${POLICY_TYPE}] <br/>保單編號: [${POLICY_NUMBER}]  壽險核心回應: [${POLICY_STATUS}]', getdate(),N'admin',getdate(),N'admin')
GO

  --- 【從壽險核心接收回案件狀態回饋檔後發送(狀態為已完成或失敗)】通知後台管理人員[MESSAGING_PARAMETER]
INSERT INTO  ESERVICE_ADM.[dbo].[MESSAGING_PARAMETER]
		 ([MESSAGING_TEMPLATE_ID]
		 ,[PARAMETER_ID])
VALUES
		 ((select MESSAGING_TEMPLATE_ID  FROM   ESERVICE_ADM.dbo.[MESSAGING_TEMPLATE]  WHERE SYSTEM_ID='eservice_batch' and [MESSAGING_TEMPLATE_CODE]='TRANSFER_MAIL_020')
		 ,(select PARAMETER_ID  FROM   ESERVICE_ADM.dbo.PARAMETER  WHERE SYSTEM_ID='eservice_batch' and PARAMETER_CODE='MSG_PARAM_POLICY_TYPE')
	   )
GO
 
INSERT INTO  ESERVICE_ADM.[dbo].[MESSAGING_PARAMETER]
		 ([MESSAGING_TEMPLATE_ID]
		 ,[PARAMETER_ID])
VALUES
		 ((select MESSAGING_TEMPLATE_ID  FROM   ESERVICE_ADM.dbo.[MESSAGING_TEMPLATE]  WHERE SYSTEM_ID='eservice_batch' and [MESSAGING_TEMPLATE_CODE]='TRANSFER_MAIL_020')
		 ,(select PARAMETER_ID  FROM   ESERVICE_ADM.dbo.PARAMETER  WHERE SYSTEM_ID='eservice_batch' and PARAMETER_CODE='MSG_PARAM_POLICY_STATUS')
	   )
GO

INSERT INTO  ESERVICE_ADM.[dbo].[MESSAGING_PARAMETER]
	 ([MESSAGING_TEMPLATE_ID]
	 ,[PARAMETER_ID])
VALUES
	((select MESSAGING_TEMPLATE_ID  FROM   ESERVICE_ADM.dbo.[MESSAGING_TEMPLATE]  WHERE SYSTEM_ID='eservice_batch' and [MESSAGING_TEMPLATE_CODE]='TRANSFER_MAIL_020')
	,(select PARAMETER_ID  FROM   ESERVICE_ADM.dbo.PARAMETER  WHERE SYSTEM_ID='eservice_api' and PARAMETER_CODE='MSG_PARAM_POLICY_NUMBER')
	)
GO


--通知保戶內容模版


-- 從壽險核心接收回案件狀態回饋檔後發送(狀態為已完成或失敗)，进行通知保戶內容发送邮件参数
INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
	VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice_batch', N'MSG_PARAM_POLICY_STATE', N'辦理契約-狀態'
	, N'POLICY_STATE',
	(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='MessagingParameter'), NULL, NULL, 1, N'N', NULL, getdate(), N'admin', getdate(), N'admin')
go


  -- 從壽險核心接收回案件狀態回饋檔後發送(狀態為已完成或失敗)进行通知保戶內容MAIL模版
INSERT INTO ESERVICE_ADM.[dbo].[MESSAGING_TEMPLATE]([MESSAGING_TEMPLATE_ID],[SYSTEM_ID],[MESSAGING_TEMPLATE_CODE],[MESSAGING_TEMPLATE_NAME],[STATUS],[TRIGGER_TYPE],[EVENT_TYPE],[SEND_TYPE],[SEND_TIME],[CIRCLE_TYPE],[CIRCLE_VALUE],[RECEIVER_MODE],[MESSAGING_SUBJECT],[MESSAGING_CONTENT],[CREATE_DATE],[CREATE_USER],[UPDATE_DATE],[UPDATE_USER])
	VALUES((select max([MESSAGING_TEMPLATE_ID])+1 from ESERVICE_ADM.dbo.MESSAGING_TEMPLATE),N'eservice_batch',N'TRANSFER_MAIL_021',N'【從壽險核心接收回案件】聯盟轉收件保戶MAIL模版'
	,3,N'api ',NULL,N'email',NULL,NULL,NULL,N'dynamic',N'【從壽險核心接收回案件】聯盟轉收件保戶MAIL模版',N'<br/>親愛的臺銀人壽保戶您好！ <br/>本公司已完成您的[${POLICY_STATE}]辦理契約內容變更申請案。<br/>如有疑問，請洽本公司電話服務中心0800-011966', getdate(),N'admin',getdate(),N'admin')
GO

INSERT INTO  ESERVICE_ADM.[dbo].[MESSAGING_PARAMETER]
	([MESSAGING_TEMPLATE_ID]
	,[PARAMETER_ID])
VALUES
	((select MESSAGING_TEMPLATE_ID  FROM   ESERVICE_ADM.dbo.[MESSAGING_TEMPLATE]  WHERE SYSTEM_ID='eservice_batch' and [MESSAGING_TEMPLATE_CODE]='TRANSFER_MAIL_021')
	,(select PARAMETER_ID  FROM   ESERVICE_ADM.dbo.PARAMETER  WHERE SYSTEM_ID='eservice_batch' and PARAMETER_CODE='MSG_PARAM_POLICY_STATE')
   )
GO


-- 從壽險核心接收回案件狀態回饋檔後發送(狀態為已完成或失敗)首家件-通知保戶內容MAIL模版
INSERT INTO ESERVICE_ADM.[dbo].[MESSAGING_TEMPLATE]([MESSAGING_TEMPLATE_ID],[SYSTEM_ID],[MESSAGING_TEMPLATE_CODE],[MESSAGING_TEMPLATE_NAME],[STATUS],[TRIGGER_TYPE],[EVENT_TYPE],[SEND_TYPE],[SEND_TIME],[CIRCLE_TYPE],[CIRCLE_VALUE],[RECEIVER_MODE],[MESSAGING_SUBJECT],[MESSAGING_CONTENT],[CREATE_DATE],[CREATE_USER],[UPDATE_DATE],[UPDATE_USER])
VALUES((select max([MESSAGING_TEMPLATE_ID])+1 from ESERVICE_ADM.dbo.MESSAGING_TEMPLATE),N'eservice_batch',N'TRANSFER_MAIL_022',N'【從壽險核心接收回案件】首家件保戶MAIL模版'
,3,N'api ',NULL,N'email',NULL,NULL,NULL,N'dynamic',N'【從壽險核心接收回案件】首家件保戶MAIL模版',N'<br/>親愛的臺銀人壽保戶您好！<br/> 本公司已完成您的線上辦理契約內容變更申請案，另已將您的變更資料經保全聯盟鏈轉送至您同意傳送之保險公司。<br/>如有疑問，請洽本公司電話服務中心0800-011966', getdate(),N'admin',getdate(),N'admin')
GO

 -- 修改範本
--update ESERVICE_ADM.[dbo].[MESSAGING_TEMPLATE] set  MESSAGING_CONTENT =N'<br/>親愛的臺銀人壽保戶您好！<br/> 本公司已完成您的線上辦理契約內容變更申請案，另已將您的變更資料經保全聯盟鏈轉送至您同意傳送之保險公司。<br/>如有疑問，請洽本公司電話服務中心0800-011966' where  [MESSAGING_TEMPLATE_CODE]='TRANSFER_MAIL_022'
/*
INSERT INTO  ESERVICE_ADM.[dbo].[MESSAGING_PARAMETER]
   ([MESSAGING_TEMPLATE_ID]
   ,[PARAMETER_ID])
VALUES
   ((select MESSAGING_TEMPLATE_ID  FROM   ESERVICE_ADM.dbo.[MESSAGING_TEMPLATE]  WHERE SYSTEM_ID='eservice_batch' and [MESSAGING_TEMPLATE_CODE]='TRANSFER_MAIL_022')
   ,(select PARAMETER_ID  FROM   ESERVICE_ADM.dbo.PARAMETER  WHERE SYSTEM_ID='eservice_batch' and PARAMETER_CODE='MSG_PARAM_POLICY_TYPE')
   )
GO
*/

----客戶通知  轉收件通知  臺銀人壽保單理賠申請通知
INSERT INTO ESERVICE_ADM.[dbo].[MESSAGING_TEMPLATE]([MESSAGING_TEMPLATE_ID],[SYSTEM_ID],[MESSAGING_TEMPLATE_CODE],[MESSAGING_TEMPLATE_NAME],[STATUS],[TRIGGER_TYPE],[EVENT_TYPE],[SEND_TYPE],[SEND_TIME],[CIRCLE_TYPE],[CIRCLE_VALUE],[RECEIVER_MODE],[MESSAGING_SUBJECT],[MESSAGING_CONTENT],[CREATE_DATE],[CREATE_USER],[UPDATE_DATE],[UPDATE_USER])
VALUES((select max([MESSAGING_TEMPLATE_ID])+1 from ESERVICE_ADM.dbo.MESSAGING_TEMPLATE),N'eservice',N'ELIFE_MAIL_023',N'【保單理賠申請通知】保戶轉收件MAIL模板'
,3,N'api ',NULL,N'email',NULL,NULL,NULL,N'dynamic',N'通知保戶轉收件通知MAIL模板',N'<table width="100%" align="center" border="0" cellpadding="0" cellspacing="0" style="border-collapse:collapse;border-spacing:0;margin:0;padding:0;width:100%" class="m_-1402362586549430844background"><tbody><tr><td align="center" valign="top" style="border-collapse:collapse;border-spacing:0;margin:0;padding:0" bgcolor="#F0F0F0"><br><table border="0" cellpadding="0" cellspacing="0" align="center" bgcolor="#FFFFFF" width="560" style="border-collapse:collapse;border-spacing:0;padding:0;width:inherit;max-width:560px" class="m_-1402362586549430844container"><tbody><tr><td align="center" valign="top" style="border-collapse:collapse;border-spacing:0;margin:0;padding:0;padding-left:6.25%;padding-right:6.25%;width:87.5%;font-size:24px;font-weight:bold;line-height:130%;padding-top:0px;padding-bottom:15px;color:#000000;font-family:Microsoft JhengHei" class="m_-1402362586549430844header"><a href="https://www.twfhclife.com.tw/" target="_blank"><img src="https://elife.twfhclife.com.tw/eservice/img/my-logo.png" class="CToWUd"></a></td></tr><tr><td align="center" valign="top" style="border-collapse:collapse;border-spacing:0;margin:0;padding:0;padding-bottom:3px;padding-left:6.25%;padding-right:6.25%;width:87.5%;font-size:18px;font-weight:600;line-height:150%;padding-top:5px;color:#000000;font-family:Microsoft JhengHei" class="m_-1402362586549430844subheader">臺銀人壽保單理賠申請通知</td></tr><tr><td align="left" valign="top" style="border-collapse:collapse;border-spacing:0;margin:0;padding:0;padding-left:6.25%;padding-right:6.25%;width:87.5%;font-size:16px;font-weight:400;line-height:160%;padding-top:25px;color:#000000;font-family:Microsoft JhengHei" class="m_-1402362586549430844paragraph">親愛的客戶您好：<br> 本公司已收訖您的保單理賠申請案，申請時間：${LoginTime}，申請序號：${TransNum}，案件狀態：${TransStatus}，將儘速為您辦理。如需其他服務請撥打本公司客服專線或洽詢各地分公司辦理。</td></tr><tr><td align="center" valign="top" style="border-collapse:collapse;border-spacing:0;margin:0;padding:0;padding-left:6.25%;padding-right:6.25%;width:87.5%;padding-top:5px" class="m_-1402362586549430844line"><hr color="#E0E0E0" align="center" width="100%" size="1" noshade="" style="margin:0;padding:0"></td></tr><tr><td align="center" valign="top" style="border-collapse:collapse;border-spacing:0;margin:0;padding:0;padding-left:6.25%;padding-right:6.25%" class="m_-1402362586549430844list-item"><table align="left" border="0" cellspacing="0" cellpadding="0" style="width:inherit;margin:0;padding:0;border-collapse:collapse;border-spacing:0"><tbody><tr><td align="left" valign="top" style="font-size:16px;padding-top:10px;padding-bottom:10px;padding-left:0px;color:#000000;font-family:Microsoft JhengHei">客服專線：0800-011-966</td></tr></tbody></table></td></tr></tbody></table><table border="0" cellpadding="0" cellspacing="0" align="center" width="560" style="border-collapse:collapse;border-spacing:0;padding:0;width:inherit;max-width:560px" class="m_-1402362586549430844wrapper"><tbody><tr><td align="center" valign="top" style="border-collapse:collapse;border-spacing:0;margin:0;padding:0;width:100%;font-size:18px;font-weight:400;line-height:150%;padding-top:20px;padding-bottom:20px;color:#999999;font-family:Microsoft JhengHei" class="m_-1402362586549430844footer">(本郵件是由系統自動寄送，請勿以此信件回覆。)</td></tr></tbody></table></td></tr></tbody></table>', getdate(),N'admin',getdate(),N'admin')
GO

INSERT INTO  ESERVICE_ADM.[dbo].[MESSAGING_PARAMETER]
   ([MESSAGING_TEMPLATE_ID]
   ,[PARAMETER_ID])
VALUES
   ((select MESSAGING_TEMPLATE_ID  FROM   ESERVICE_ADM.dbo.[MESSAGING_TEMPLATE]  WHERE SYSTEM_ID='eservice' and [MESSAGING_TEMPLATE_CODE]='ELIFE_MAIL_023')
   ,(select PARAMETER_ID  FROM   ESERVICE_ADM.dbo.PARAMETER  WHERE SYSTEM_ID='eservice_adm' and PARAMETER_CODE='MSG_PARAM_LoginTime')
   )
GO

INSERT INTO  ESERVICE_ADM.[dbo].[MESSAGING_PARAMETER]
   ([MESSAGING_TEMPLATE_ID]
   ,[PARAMETER_ID])
VALUES
   ((select MESSAGING_TEMPLATE_ID  FROM   ESERVICE_ADM.dbo.[MESSAGING_TEMPLATE]  WHERE SYSTEM_ID='eservice' and [MESSAGING_TEMPLATE_CODE]='ELIFE_MAIL_023')
   ,(select PARAMETER_ID  FROM   ESERVICE_ADM.dbo.PARAMETER  WHERE SYSTEM_ID='eservice_adm' and PARAMETER_CODE='MSG_PARAM_TransNum')
   )
GO

INSERT INTO  ESERVICE_ADM.[dbo].[MESSAGING_PARAMETER]
   ([MESSAGING_TEMPLATE_ID]
   ,[PARAMETER_ID])
VALUES
   ((select MESSAGING_TEMPLATE_ID  FROM   ESERVICE_ADM.dbo.[MESSAGING_TEMPLATE]  WHERE SYSTEM_ID='eservice' and [MESSAGING_TEMPLATE_CODE]='ELIFE_MAIL_023')
   ,(select PARAMETER_ID  FROM   ESERVICE_ADM.dbo.PARAMETER  WHERE SYSTEM_ID='eservice_adm' and PARAMETER_CODE='MSG_PARAM_TransStatus')
   )
GO


-- 客戶通知	首家件通知  臺銀人壽保單理賠申請通知
INSERT INTO ESERVICE_ADM.[dbo].[MESSAGING_TEMPLATE]([MESSAGING_TEMPLATE_ID],[SYSTEM_ID],[MESSAGING_TEMPLATE_CODE],[MESSAGING_TEMPLATE_NAME],[STATUS],[TRIGGER_TYPE],[EVENT_TYPE],[SEND_TYPE],[SEND_TIME],[CIRCLE_TYPE],[CIRCLE_VALUE],[RECEIVER_MODE],[MESSAGING_SUBJECT],[MESSAGING_CONTENT],[CREATE_DATE],[CREATE_USER],[UPDATE_DATE],[UPDATE_USER])
VALUES((select max([MESSAGING_TEMPLATE_ID])+1 from ESERVICE_ADM.dbo.MESSAGING_TEMPLATE),N'eservice',N'ELIFE_MAIL_024',N'【保單理賠申請通知】保戶首家件MAIL模板'
,3,N'api ',NULL,N'email',NULL,NULL,NULL,N'dynamic',N'通知保戶首家件通知MAIL模板',N'<table width="100%" align="center" border="0" cellpadding="0" cellspacing="0" style="border-collapse:collapse;border-spacing:0;margin:0;padding:0;width:100%" class="m_-1402362586549430844background"><tbody><tr><td align="center" valign="top" style="border-collapse:collapse;border-spacing:0;margin:0;padding:0" bgcolor="#F0F0F0"><br><table border="0" cellpadding="0" cellspacing="0" align="center" bgcolor="#FFFFFF" width="560" style="border-collapse:collapse;border-spacing:0;padding:0;width:inherit;max-width:560px" class="m_-1402362586549430844container"><tbody><tr><td align="center" valign="top" style="border-collapse:collapse;border-spacing:0;margin:0;padding:0;padding-left:6.25%;padding-right:6.25%;width:87.5%;font-size:24px;font-weight:bold;line-height:130%;padding-top:0px;padding-bottom:15px;color:#000000;font-family:Microsoft JhengHei" class="m_-1402362586549430844header"><a href="https://www.twfhclife.com.tw/" target="_blank"><img src="https://elife.twfhclife.com.tw/eservice/img/my-logo.png" class="CToWUd"></a></td></tr><tr><td align="center" valign="top" style="border-collapse:collapse;border-spacing:0;margin:0;padding:0;padding-bottom:3px;padding-left:6.25%;padding-right:6.25%;width:87.5%;font-size:18px;font-weight:600;line-height:150%;padding-top:5px;color:#000000;font-family:Microsoft JhengHei" class="m_-1402362586549430844subheader">臺銀人壽保單理賠申請通知</td></tr><tr><td align="left" valign="top" style="border-collapse:collapse;border-spacing:0;margin:0;padding:0;padding-left:6.25%;padding-right:6.25%;width:87.5%;font-size:16px;font-weight:400;line-height:160%;padding-top:25px;color:#000000;font-family:Microsoft JhengHei" class="m_-1402362586549430844paragraph">親愛的客戶您好：<br> 感謝您使用本公司保單網路服務，本公司已收到您的保單理賠申請案，申請時間：${LoginTime}，申請序號：${TransNum}，案件狀態：${TransStatus}，將儘速為您辦理。如需其他服務請撥打本公司客服專線或洽詢各地分公司辦理。</td></tr><tr><td align="center" valign="top" style="border-collapse:collapse;border-spacing:0;margin:0;padding:0;padding-left:6.25%;padding-right:6.25%;width:87.5%;padding-top:5px" class="m_-1402362586549430844line"><hr color="#E0E0E0" align="center" width="100%" size="1" noshade="" style="margin:0;padding:0"></td></tr><tr><td align="center" valign="top" style="border-collapse:collapse;border-spacing:0;margin:0;padding:0;padding-left:6.25%;padding-right:6.25%" class="m_-1402362586549430844list-item"><table align="left" border="0" cellspacing="0" cellpadding="0" style="width:inherit;margin:0;padding:0;border-collapse:collapse;border-spacing:0"><tbody><tr><td align="left" valign="top" style="font-size:16px;padding-top:10px;padding-bottom:10px;padding-left:0px;color:#000000;font-family:Microsoft JhengHei">客服專線：0800-011-966</td></tr></tbody></table></td></tr></tbody></table><table border="0" cellpadding="0" cellspacing="0" align="center" width="560" style="border-collapse:collapse;border-spacing:0;padding:0;width:inherit;max-width:560px" class="m_-1402362586549430844wrapper"><tbody><tr><td align="center" valign="top" style="border-collapse:collapse;border-spacing:0;margin:0;padding:0;width:100%;font-size:18px;font-weight:400;line-height:150%;padding-top:20px;padding-bottom:20px;color:#999999;font-family:Microsoft JhengHei" class="m_-1402362586549430844footer">(本郵件是由系統自動寄送，請勿以此信件回覆。)</td></tr></tbody></table></td></tr></tbody></table>', getdate(),N'admin',getdate(),N'admin')
GO




----客戶通知	首家件通知  臺銀人壽保單理賠申請通知
INSERT INTO  ESERVICE_ADM.[dbo].[MESSAGING_PARAMETER]
   ([MESSAGING_TEMPLATE_ID]
   ,[PARAMETER_ID])
VALUES
   ((select MESSAGING_TEMPLATE_ID  FROM   ESERVICE_ADM.dbo.[MESSAGING_TEMPLATE]  WHERE SYSTEM_ID='eservice' and [MESSAGING_TEMPLATE_CODE]='ELIFE_MAIL_024')
   ,(select PARAMETER_ID  FROM   ESERVICE_ADM.dbo.PARAMETER  WHERE SYSTEM_ID='eservice_adm' and PARAMETER_CODE='MSG_PARAM_LoginTime')
   )
GO

INSERT INTO  ESERVICE_ADM.[dbo].[MESSAGING_PARAMETER]
   ([MESSAGING_TEMPLATE_ID]
   ,[PARAMETER_ID])
VALUES
   ((select MESSAGING_TEMPLATE_ID  FROM   ESERVICE_ADM.dbo.[MESSAGING_TEMPLATE]  WHERE SYSTEM_ID='eservice' and [MESSAGING_TEMPLATE_CODE]='ELIFE_MAIL_024')
   ,(select PARAMETER_ID  FROM   ESERVICE_ADM.dbo.PARAMETER  WHERE SYSTEM_ID='eservice_adm' and PARAMETER_CODE='MSG_PARAM_TransNum')
   )
GO

INSERT INTO  ESERVICE_ADM.[dbo].[MESSAGING_PARAMETER]
   ([MESSAGING_TEMPLATE_ID]
   ,[PARAMETER_ID])
VALUES
   ((select MESSAGING_TEMPLATE_ID  FROM   ESERVICE_ADM.dbo.[MESSAGING_TEMPLATE]  WHERE SYSTEM_ID='eservice' and [MESSAGING_TEMPLATE_CODE]='ELIFE_MAIL_024')
   ,(select PARAMETER_ID  FROM   ESERVICE_ADM.dbo.PARAMETER  WHERE SYSTEM_ID='eservice_adm' and PARAMETER_CODE='MSG_PARAM_TransStatus')
   )
GO




-- 內部人員通知	首家件通知	理賠聯盟鏈首家理賠申請通知
INSERT INTO ESERVICE_ADM.[dbo].[MESSAGING_TEMPLATE]([MESSAGING_TEMPLATE_ID],[SYSTEM_ID],[MESSAGING_TEMPLATE_CODE],[MESSAGING_TEMPLATE_NAME],[STATUS],[TRIGGER_TYPE],[EVENT_TYPE],[SEND_TYPE],[SEND_TIME],[CIRCLE_TYPE],[CIRCLE_VALUE],[RECEIVER_MODE],[MESSAGING_SUBJECT],[MESSAGING_CONTENT],[CREATE_DATE],[CREATE_USER],[UPDATE_DATE],[UPDATE_USER])
VALUES((select max([MESSAGING_TEMPLATE_ID])+1 from ESERVICE_ADM.dbo.MESSAGING_TEMPLATE),N'eservice',N'ELIFE_MAIL_025',N'【理賠聯盟鏈首家理賠】MAIL模板'
,3,N'api ',NULL,N'email',NULL,NULL,NULL,N'dynamic',N'理賠聯盟鏈首家理賠申請通知MAIL模板',N'<table width="100%" align="center" border="0" cellpadding="0" cellspacing="0" style="border-collapse:collapse;border-spacing:0;margin:0;padding:0;width:100%" class="m_-1402362586549430844background"><tbody><tr><td align="center" valign="top" style="border-collapse:collapse;border-spacing:0;margin:0;padding:0" bgcolor="#F0F0F0"><br><table border="0" cellpadding="0" cellspacing="0" align="center" bgcolor="#FFFFFF" width="560" style="border-collapse:collapse;border-spacing:0;padding:0;width:inherit;max-width:560px" class="m_-1402362586549430844container"><tbody><tr><td align="center" valign="top" style="border-collapse:collapse;border-spacing:0;margin:0;padding:0;padding-left:6.25%;padding-right:6.25%;width:87.5%;font-size:24px;font-weight:bold;line-height:130%;padding-top:0px;padding-bottom:15px;color:#000000;font-family:Microsoft JhengHei" class="m_-1402362586549430844header"><a href="https://www.twfhclife.com.tw/" target="_blank"><img src="https://elife.twfhclife.com.tw/eservice/img/my-logo.png" class="CToWUd"></a></td></tr><tr><td align="center" valign="top" style="border-collapse:collapse;border-spacing:0;margin:0;padding:0;padding-bottom:3px;padding-left:6.25%;padding-right:6.25%;width:87.5%;font-size:18px;font-weight:600;line-height:150%;padding-top:5px;color:#000000;font-family:Microsoft JhengHei" class="m_-1402362586549430844subheader">理賠聯盟鏈首家理賠申請通知</td></tr><tr><td align="left" valign="top" style="border-collapse:collapse;border-spacing:0;margin:0;padding:0;padding-left:6.25%;padding-right:6.25%;width:87.5%;font-size:16px;font-weight:400;line-height:160%;padding-top:25px;color:#000000;font-family:Microsoft JhengHei" class="m_-1402362586549430844paragraph">收到首家案件 1 筆，申請時間：${LoginTime}，申請序號：${TransNum}，資料已寫入聯盟鏈理賠線上申請。</td></tr><tr><td align="center" valign="top" style="border-collapse:collapse;border-spacing:0;margin:0;padding:0;padding-left:6.25%;padding-right:6.25%;width:87.5%;padding-top:5px" class="m_-1402362586549430844line"><hr color="#E0E0E0" align="center" width="100%" size="1" noshade="" style="margin:0;padding:0"></td></tr><tr><td align="center" valign="top" style="border-collapse:collapse;border-spacing:0;margin:0;padding:0;padding-left:6.25%;padding-right:6.25%" class="m_-1402362586549430844list-item"><table align="left" border="0" cellspacing="0" cellpadding="0" style="width:inherit;margin:0;padding:0;border-collapse:collapse;border-spacing:0"><tbody><tr><td align="left" valign="top" style="font-size:16px;padding-top:10px;padding-bottom:10px;padding-left:0px;color:#000000;font-family:Microsoft JhengHei"></td></tr></tbody></table></td></tr></tbody></table><table border="0" cellpadding="0" cellspacing="0" align="center" width="560" style="border-collapse:collapse;border-spacing:0;padding:0;width:inherit;max-width:560px" class="m_-1402362586549430844wrapper"><tbody><tr><td align="center" valign="top" style="border-collapse:collapse;border-spacing:0;margin:0;padding:0;width:100%;font-size:18px;font-weight:400;line-height:150%;padding-top:20px;padding-bottom:20px;color:#999999;font-family:Microsoft JhengHei" class="m_-1402362586549430844footer">(本郵件是由系統自動寄送，請勿以此信件回覆。)</td></tr></tbody></table></td></tr></tbody></table>', getdate(),N'admin',getdate(),N'admin')
GO

INSERT INTO  ESERVICE_ADM.[dbo].[MESSAGING_PARAMETER]
   ([MESSAGING_TEMPLATE_ID]
   ,[PARAMETER_ID])
VALUES
   ((select MESSAGING_TEMPLATE_ID  FROM   ESERVICE_ADM.dbo.[MESSAGING_TEMPLATE]  WHERE SYSTEM_ID='eservice' and [MESSAGING_TEMPLATE_CODE]='ELIFE_MAIL_025')
   ,(select PARAMETER_ID  FROM   ESERVICE_ADM.dbo.PARAMETER  WHERE SYSTEM_ID='eservice_adm' and PARAMETER_CODE='MSG_PARAM_LoginTime')
   )
GO

INSERT INTO  ESERVICE_ADM.[dbo].[MESSAGING_PARAMETER]
   ([MESSAGING_TEMPLATE_ID]
   ,[PARAMETER_ID])
VALUES
   ((select MESSAGING_TEMPLATE_ID  FROM   ESERVICE_ADM.dbo.[MESSAGING_TEMPLATE]  WHERE SYSTEM_ID='eservice' and [MESSAGING_TEMPLATE_CODE]='ELIFE_MAIL_025')
   ,(select PARAMETER_ID  FROM   ESERVICE_ADM.dbo.PARAMETER  WHERE SYSTEM_ID='eservice_adm' and PARAMETER_CODE='MSG_PARAM_TransNum')
   )
GO



---內部人員通知	轉收件通知	理賠聯盟鏈轉收申請通知


INSERT INTO ESERVICE_ADM.[dbo].[MESSAGING_TEMPLATE]([MESSAGING_TEMPLATE_ID],[SYSTEM_ID],[MESSAGING_TEMPLATE_CODE],[MESSAGING_TEMPLATE_NAME],[STATUS],[TRIGGER_TYPE],[EVENT_TYPE],[SEND_TYPE],[SEND_TIME],[CIRCLE_TYPE],[CIRCLE_VALUE],[RECEIVER_MODE],[MESSAGING_SUBJECT],[MESSAGING_CONTENT],[CREATE_DATE],[CREATE_USER],[UPDATE_DATE],[UPDATE_USER])
VALUES((select max([MESSAGING_TEMPLATE_ID])+1 from ESERVICE_ADM.dbo.MESSAGING_TEMPLATE),N'eservice',N'ELIFE_MAIL_026',N'【理賠聯盟鏈轉收申請】MAIL模板'
,3,N'api ',NULL,N'email',NULL,NULL,NULL,N'dynamic',N'理賠聯盟鏈轉收申請通知MAIL模板',N'<table width="100%" align="center" border="0" cellpadding="0" cellspacing="0" style="border-collapse:collapse;border-spacing:0;margin:0;padding:0;width:100%" class="m_-1402362586549430844background"><tbody><tr><td align="center" valign="top" style="border-collapse:collapse;border-spacing:0;margin:0;padding:0" bgcolor="#F0F0F0"><br><table border="0" cellpadding="0" cellspacing="0" align="center" bgcolor="#FFFFFF" width="560" style="border-collapse:collapse;border-spacing:0;padding:0;width:inherit;max-width:560px" class="m_-1402362586549430844container"><tbody><tr><td align="center" valign="top" style="border-collapse:collapse;border-spacing:0;margin:0;padding:0;padding-left:6.25%;padding-right:6.25%;width:87.5%;font-size:24px;font-weight:bold;line-height:130%;padding-top:0px;padding-bottom:15px;color:#000000;font-family:Microsoft JhengHei" class="m_-1402362586549430844header"><a href="https://www.twfhclife.com.tw/" target="_blank"><img src="https://elife.twfhclife.com.tw/eservice/img/my-logo.png" class="CToWUd"></a></td></tr><tr><td align="center" valign="top" style="border-collapse:collapse;border-spacing:0;margin:0;padding:0;padding-bottom:3px;padding-left:6.25%;padding-right:6.25%;width:87.5%;font-size:18px;font-weight:600;line-height:150%;padding-top:5px;color:#000000;font-family:Microsoft JhengHei" class="m_-1402362586549430844subheader">理賠聯盟鏈轉收申請通知</td></tr><tr><td align="left" valign="top" style="border-collapse:collapse;border-spacing:0;margin:0;padding:0;padding-left:6.25%;padding-right:6.25%;width:87.5%;font-size:16px;font-weight:400;line-height:160%;padding-top:25px;color:#000000;font-family:Microsoft JhengHei" class="m_-1402362586549430844paragraph">收到轉收案件 1 筆，申請時間：${LoginTime}，申請序號：${TransNum}，資料已寫入聯盟鏈理賠線上申請。</td></tr><tr><td align="center" valign="top" style="border-collapse:collapse;border-spacing:0;margin:0;padding:0;padding-left:6.25%;padding-right:6.25%;width:87.5%;padding-top:5px" class="m_-1402362586549430844line"><hr color="#E0E0E0" align="center" width="100%" size="1" noshade="" style="margin:0;padding:0"></td></tr><tr><td align="center" valign="top" style="border-collapse:collapse;border-spacing:0;margin:0;padding:0;padding-left:6.25%;padding-right:6.25%" class="m_-1402362586549430844list-item"><table align="left" border="0" cellspacing="0" cellpadding="0" style="width:inherit;margin:0;padding:0;border-collapse:collapse;border-spacing:0"><tbody><tr><td align="left" valign="top" style="font-size:16px;padding-top:10px;padding-bottom:10px;padding-left:0px;color:#000000;font-family:Microsoft JhengHei"></td></tr></tbody></table></td></tr></tbody></table><table border="0" cellpadding="0" cellspacing="0" align="center" width="560" style="border-collapse:collapse;border-spacing:0;padding:0;width:inherit;max-width:560px" class="m_-1402362586549430844wrapper"><tbody><tr><td align="center" valign="top" style="border-collapse:collapse;border-spacing:0;margin:0;padding:0;width:100%;font-size:18px;font-weight:400;line-height:150%;padding-top:20px;padding-bottom:20px;color:#999999;font-family:Microsoft JhengHei" class="m_-1402362586549430844footer">(本郵件是由系統自動寄送，請勿以此信件回覆。)</td></tr></tbody></table></td></tr></tbody></table>', getdate(),N'admin',getdate(),N'admin')
GO

INSERT INTO  ESERVICE_ADM.[dbo].[MESSAGING_PARAMETER]
   ([MESSAGING_TEMPLATE_ID]
   ,[PARAMETER_ID])
VALUES
   ((select MESSAGING_TEMPLATE_ID  FROM   ESERVICE_ADM.dbo.[MESSAGING_TEMPLATE]  WHERE SYSTEM_ID='eservice' and [MESSAGING_TEMPLATE_CODE]='ELIFE_MAIL_026')
   ,(select PARAMETER_ID  FROM   ESERVICE_ADM.dbo.PARAMETER  WHERE SYSTEM_ID='eservice_adm' and PARAMETER_CODE='MSG_PARAM_LoginTime')
   )
GO

INSERT INTO  ESERVICE_ADM.[dbo].[MESSAGING_PARAMETER]
   ([MESSAGING_TEMPLATE_ID]
   ,[PARAMETER_ID])
VALUES
   ((select MESSAGING_TEMPLATE_ID  FROM   ESERVICE_ADM.dbo.[MESSAGING_TEMPLATE]  WHERE SYSTEM_ID='eservice' and [MESSAGING_TEMPLATE_CODE]='ELIFE_MAIL_026')
   ,(select PARAMETER_ID  FROM   ESERVICE_ADM.dbo.PARAMETER  WHERE SYSTEM_ID='eservice_adm' and PARAMETER_CODE='MSG_PARAM_TransNum')
   )
GO


---- 修改異常件的管理者通知信件內容
-----轉修eservice進件-已註記異常件-處理通知後台管理人員，进行发送邮件参数
  INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
  VALUES ((select max(parameter_id)+1 from ESERVICE_ADM.dbo.PARAMETER), N'eservice_api', N'MSG_PARAM_CACE_NUMBER', N'通信模板參數-案件編號'
  , N'CACE_NUMBER',
  (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='MessagingParameter'), NULL, NULL, 1, N'N', NULL, getdate(), N'admin', getdate(), N'admin')
  go

 -- 【轉修eservice進件-已註記異常件-處理】通知後台管理人員 发送邮件，
 -- 修改模板信息
 update   ESERVICE_ADM.[dbo].[MESSAGING_TEMPLATE] set  MESSAGING_CONTENT=N'保全聯盟鏈 - 轉收件<br/>保戶欲修改的資料不符合本公司規範，[已傳送E-Mail給保戶需轉為人工紙本申請]<br/>可至共享平台查詢，連結: [https://lia-share.twfhclife.com.tw/]<br/>查詢案件編號: [${DATA}-${CACE_NUMBER}]<br/>'
	WHERE  MESSAGING_TEMPLATE_CODE ='TRANSFER_MAIL_018'


  --- 【轉修eservice進件-已註記異常件-處理】通知後台管理人員[MESSAGING_PARAMETER]
  --删除模板
  DELETE  ESERVICE_ADM.[dbo].[MESSAGING_PARAMETER] where [MESSAGING_TEMPLATE_ID]=  (select MESSAGING_TEMPLATE_ID  FROM   ESERVICE_ADM.dbo.[MESSAGING_TEMPLATE]  WHERE SYSTEM_ID='eservice_api' and [MESSAGING_TEMPLATE_CODE]='TRANSFER_MAIL_018')
   --重新添加新的
  INSERT INTO  ESERVICE_ADM.[dbo].[MESSAGING_PARAMETER]
             ([MESSAGING_TEMPLATE_ID]
             ,[PARAMETER_ID])
       VALUES
             ((select MESSAGING_TEMPLATE_ID  FROM   ESERVICE_ADM.dbo.[MESSAGING_TEMPLATE]  WHERE SYSTEM_ID='eservice_api' and [MESSAGING_TEMPLATE_CODE]='TRANSFER_MAIL_018')
             ,(select PARAMETER_ID   FROM   ESERVICE_ADM.dbo.PARAMETER  WHERE SYSTEM_ID='eservice_api' and PARAMETER_CODE='MSG_PARAM_CACE_NUMBER')
  		   )
  GO
    INSERT INTO  ESERVICE_ADM.[dbo].[MESSAGING_PARAMETER]
             ([MESSAGING_TEMPLATE_ID]
             ,[PARAMETER_ID])
       VALUES
             ((select MESSAGING_TEMPLATE_ID  FROM   ESERVICE_ADM.dbo.[MESSAGING_TEMPLATE]  WHERE SYSTEM_ID='eservice_api' and [MESSAGING_TEMPLATE_CODE]='TRANSFER_MAIL_018')
             ,(select PARAMETER_ID  FROM   ESERVICE_ADM.dbo.PARAMETER  WHERE SYSTEM_ID='eservice_api' and PARAMETER_CODE='MSG_PARAM_DATA')
  		   )
  GO

--modify 20210913-start
insert into ESERVICE_ADM.dbo.PARAMETER
	(PARAMETER_ID,SYSTEM_ID,PARAMETER_CODE,PARAMETER_NAME,PARAMETER_VALUE,PARAMETER_CATEGORY_ID,STATUS,ENCRYPT_TYPE,CREATE_DATE,CREATE_USER,UPDATE_DATE,UPDATE_USER,REMARK)
values
	(
		(select max(PARAMETER_ID)+1 from ESERVICE_ADM.dbo.PARAMETER),
		'eservice_adm',
		'API_NO_MAIL_012',
		'聯盟IT通知人員',
		'202712@twfhclife.com.tw;203990@twfhclife.com.tw',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='SECURITY_ALLIANCE_ALERT_MAIL'),
		'1',
		'N',
		getdate(),
		'admin',
		getdate(),
		'admin',
		'聯盟相關API調不通【無回應】管理人員'
	);
go

insert into ESERVICE_ADM.dbo.PARAMETER
	(PARAMETER_ID,SYSTEM_ID,PARAMETER_CODE,PARAMETER_NAME,PARAMETER_VALUE,PARAMETER_CATEGORY_ID,STATUS,ENCRYPT_TYPE,CREATE_DATE,CREATE_USER,UPDATE_DATE,UPDATE_USER,REMARK)
values
	(
		(select max(PARAMETER_ID)+1 from ESERVICE_ADM.dbo.PARAMETER),
		'eservice_adm',
		'TRANSFER_MAIL_013',
		'聯盟IT通知人員',
		'202712@twfhclife.com.tw;203990@twfhclife.com.tw',
		(select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='SECURITY_ALLIANCE_ALERT_MAIL'),
		'1',
		'N',
		getdate(),
		'admin',
		getdate(),
		'admin',
		'保全聯盟轉收件-【進件失敗】管理人員'
	);
go
--modify 20210913-end


