--INSERT
INSERT ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER) 
VALUES ( (SELECT MAX(PARAMETER_ID)+1 FROM  ESERVICE_ADM.dbo.PARAMETER ), N'eservice', N'E0000', N'E0000-系統操作錯誤提示-不允許的系統操作', N'不允許的系統操作', (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE = 'SYSTEM_MSG_PARAMETER'), NULL, N'不允許的系統操作', 1, NULL, NULL, getdate(), N'admin', NULL, NULL);

GO



