--FOR ESERVICE DB
use ESERVICE;
go

ALTER TABLE ESERVICE.DBO.TRANS_CONTACT_INFO ADD CASE_ID VARCHAR(50) NULL;
ALTER TABLE ESERVICE.DBO.TRANS_CONTACT_INFO ADD BATCH_ID FLOAT NULL;
GO


ALTER TABLE ESERVICE.DBO.TRANS_CONTACT_INFO_DTL ADD SEND_ALLIANCE VARCHAR(1) NULL;
ALTER TABLE ESERVICE.DBO.TRANS_CONTACT_INFO_DTL ADD FROM_COMPANY_ID VARCHAR(100) NULL;
ALTER TABLE ESERVICE.DBO.TRANS_CONTACT_INFO_DTL ADD TO_COMPANY_ID VARCHAR(1000) NULL;
GO

--move to DeathAlliance eservice, otherwise eservice_adm will error-start
/*
ALTER TABLE ESERVICE.DBO.INSURANCE_CLAIM_FILEDATAS ADD FILE_BASE64 VARCHAR(MAX) NULL;
GO
ALTER TABLE ESERVICE.DBO.TRANS_INSURANCE_CLAIM_FILEDATAS ADD FILE_BASE64 VARCHAR(MAX) NULL;
GO
*/
--move to DeathAlliance eservice, otherwise eservice_adm will error-end

