--After Alter All TABLE

--INSURANCE_CLAIM
select *
into ESERVICE.DBO.INSURANCE_CLAIM_BAK
from ESERVICE.DBO.INSURANCE_CLAIM
GO

--update data
update ESERVICE.DBO.INSURANCE_CLAIM
set ID_NO=ESERVICE.DBO.FN_ENBASE64(ID_NO),
	NAME=ESERVICE.DBO.FN_ENBASE64(NAME),
	BIRDATE=ESERVICE.DBO.FN_ENBASE64(BIRDATE),
	PHONE=ESERVICE.DBO.FN_ENBASE64(PHONE),
	ADDRESS=ESERVICE.DBO.FN_ENBASE64(ADDRESS),
	MAIL=ESERVICE.DBO.FN_ENBASE64(MAIL),
	BANK_ACCOUNT=ESERVICE.DBO.FN_ENBASE64(BANK_ACCOUNT),
	POLICE_NAME=ESERVICE.DBO.FN_ENBASE64(POLICE_NAME),
	POLICE_PHONE=ESERVICE.DBO.FN_ENBASE64(POLICE_PHONE) 
where 1=1;


--TRANS_INSURANCE_CLAIM
select *
into ESERVICE.DBO.TRANS_INSURANCE_CLAIM_BAK
from ESERVICE.DBO.TRANS_INSURANCE_CLAIM
GO

--update data
update ESERVICE.DBO.TRANS_INSURANCE_CLAIM
set ID_NO=ESERVICE.DBO.FN_ENBASE64(ID_NO),
	NAME=ESERVICE.DBO.FN_ENBASE64(NAME),
	BIRDATE=ESERVICE.DBO.FN_ENBASE64(BIRDATE),
	PHONE=ESERVICE.DBO.FN_ENBASE64(PHONE),
	ADDRESS=ESERVICE.DBO.FN_ENBASE64(ADDRESS),
	MAIL=ESERVICE.DBO.FN_ENBASE64(MAIL),
	BANK_ACCOUNT=ESERVICE.DBO.FN_ENBASE64(BANK_ACCOUNT),
	POLICE_NAME=ESERVICE.DBO.FN_ENBASE64(POLICE_NAME),
	POLICE_PHONE=ESERVICE.DBO.FN_ENBASE64(POLICE_PHONE),
	CUSTOMERNAME=ESERVICE.DBO.FN_ENBASE64(CUSTOMERNAME),
	TEL=ESERVICE.DBO.FN_ENBASE64(TEL)
where 1=1;


--DNS_ALLIANCE
select *
into ESERVICE.DBO.DNS_ALLIANCE_BAK
from ESERVICE.DBO.DNS_ALLIANCE
GO

--update data
update ESERVICE.DBO.DNS_ALLIANCE
set IDNO=ESERVICE.dbo.FN_ENBASE64(IDNO),
	NAME=ESERVICE.dbo.FN_ENBASE64(NAME),
	BIRDATE=ESERVICE.dbo.FN_ENBASE64(BIRDATE)
where 1=1;

--TRANS_DNS
select *
into ESERVICE.DBO.TRANS_DNS_BAK
from ESERVICE.DBO.TRANS_DNS
GO

--update data
update ESERVICE.DBO.TRANS_DNS
set IDNO=ESERVICE.DBO.FN_ENBASE64(IDNO),
	NAME=ESERVICE.DBO.FN_ENBASE64(NAME),
	BIRDATE=ESERVICE.DBO.FN_ENBASE64(BIRDATE)
where 1=1;



