
--insert TRANS_RULES
Insert into ESERVICE.dbo.TRANS_RULES (TRANS_TYPE,TRANS_NAME,POLICY_TYPE,TEXT1,TEXT2,TEXT3,TEXT4,DENY_MSG) values ('CHANGE_PAY_ACCOUNT','匯款帳號變更','UP','01、05','滿期金：lilipb.LIPB_BENI_CODE = 1 and lilipb.LIPB_ID_NO <> 空白 and lilipb.LIPB_NAME <> 空白;生存金：lilipb.LIPB_BENI_CODE = 5 and lilipb.LIPB_ID_NO <> 空白 and lilipb.LIPB_NAME <> 空白',null,null,'您選擇的保單不提供申請變更匯款帳號!!');
Insert into ESERVICE.dbo.TRANS_RULES (TRANS_TYPE,TRANS_NAME,POLICY_TYPE,TEXT1,TEXT2,TEXT3,TEXT4,DENY_MSG) values ('CHANGE_PAY_ACCOUNT','匯款帳號變更','UQ','01、05','滿期金：lilipb.LIPB_BENI_CODE = 1 and lilipb.LIPB_ID_NO <> 空白 and lilipb.LIPB_NAME <> 空白;生存金：lilipb.LIPB_BENI_CODE = 5 and lilipb.LIPB_ID_NO <> 空白 and lilipb.LIPB_NAME <> 空白',null,null,'您選擇的保單不提供申請變更匯款帳號!!');
Insert into ESERVICE.dbo.TRANS_RULES (TRANS_TYPE,TRANS_NAME,POLICY_TYPE,TEXT1,TEXT2,TEXT3,TEXT4,DENY_MSG) values ('CHANGE_PAY_ACCOUNT','匯款帳號變更','UR','01、05','滿期金：lilipb.LIPB_BENI_CODE = 1 and lilipb.LIPB_ID_NO <> 空白 and lilipb.LIPB_NAME <> 空白;生存金：lilipb.LIPB_BENI_CODE = 5 and lilipb.LIPB_ID_NO <> 空白 and lilipb.LIPB_NAME <> 空白',null,null,'您選擇的保單不提供申請變更匯款帳號!!');
Insert into ESERVICE.dbo.TRANS_RULES (TRANS_TYPE,TRANS_NAME,POLICY_TYPE,TEXT1,TEXT2,TEXT3,TEXT4,DENY_MSG) values ('PAYMODE','繳別','UP',null,null,null,null,'您選擇的保單不提供申請變更繳別!!');
Insert into ESERVICE.dbo.TRANS_RULES (TRANS_TYPE,TRANS_NAME,POLICY_TYPE,TEXT1,TEXT2,TEXT3,TEXT4,DENY_MSG) values ('PAYMODE','繳別','UQ',null,null,null,null,'您選擇的保單不提供申請變更繳別!!');
Insert into ESERVICE.dbo.TRANS_RULES (TRANS_TYPE,TRANS_NAME,POLICY_TYPE,TEXT1,TEXT2,TEXT3,TEXT4,DENY_MSG) values ('PAYMODE','繳別','UR',null,null,null,null,'您選擇的保單不提供申請變更繳別!!');
Insert into ESERVICE.dbo.TRANS_RULES (TRANS_TYPE,TRANS_NAME,POLICY_TYPE,TEXT1,TEXT2,TEXT3,TEXT4,DENY_MSG) values ('CONTACT_INFO','聯絡資料變更','UP',null,'LILIPM:LIPM_AGEN_CODE=LIDEDR:DEDR_AGEN_CODE and 線上申請的地址<>LIDEDR:DEDR_ADDR_BUS and 線上申請的地址<>LIDEDR:DEDR_ADDR_RES and 線上申請的地址<>LIDEDR:DEDR_ADDR_COMM',null,null,'您選擇的保單不提供申請變更聯絡資料!!');
Insert into ESERVICE.dbo.TRANS_RULES (TRANS_TYPE,TRANS_NAME,POLICY_TYPE,TEXT1,TEXT2,TEXT3,TEXT4,DENY_MSG) values ('CONTACT_INFO','聯絡資料變更','UQ',null,'LILIPM:LIPM_AGEN_CODE=LIDEDR:DEDR_AGEN_CODE and 線上申請的地址<>LIDEDR:DEDR_ADDR_BUS and 線上申請的地址<>LIDEDR:DEDR_ADDR_RES and 線上申請的地址<>LIDEDR:DEDR_ADDR_COMM',null,null,'您選擇的保單不提供申請變更聯絡資料!!');
Insert into ESERVICE.dbo.TRANS_RULES (TRANS_TYPE,TRANS_NAME,POLICY_TYPE,TEXT1,TEXT2,TEXT3,TEXT4,DENY_MSG) values ('CONTACT_INFO','聯絡資料變更','UR',null,'LILIPM:LIPM_AGEN_CODE=LIDEDR:DEDR_AGEN_CODE and 線上申請的地址<>LIDEDR:DEDR_ADDR_BUS and 線上申請的地址<>LIDEDR:DEDR_ADDR_RES and 線上申請的地址<>LIDEDR:DEDR_ADDR_COMM',null,null,'您選擇的保單不提供申請變更聯絡資料!!');
Insert into ESERVICE.dbo.TRANS_RULES (TRANS_TYPE,TRANS_NAME,POLICY_TYPE,TEXT1,TEXT2,TEXT3,TEXT4,DENY_MSG) values ('BENEFICIARY','受益人','UP','身故、滿期','LIPM_ST=14,身故',null,null,'您選擇的保單不提供申請變更受益人!!');
Insert into ESERVICE.dbo.TRANS_RULES (TRANS_TYPE,TRANS_NAME,POLICY_TYPE,TEXT1,TEXT2,TEXT3,TEXT4,DENY_MSG) values ('BENEFICIARY','受益人','UQ','身故、滿期','LIPM_ST=14,身故',null,null,'您選擇的保單不提供申請變更受益人!!');
Insert into ESERVICE.dbo.TRANS_RULES (TRANS_TYPE,TRANS_NAME,POLICY_TYPE,TEXT1,TEXT2,TEXT3,TEXT4,DENY_MSG) values ('BENEFICIARY','受益人','UR','身故、滿期','LIPM_ST=14,身故',null,null,'您選擇的保單不提供申請變更受益人!!');
Insert into ESERVICE.dbo.TRANS_RULES (TRANS_TYPE,TRANS_NAME,POLICY_TYPE,TEXT1,TEXT2,TEXT3,TEXT4,DENY_MSG) values ('ANNUITY_METHOD','年金給付方式','UP','T、S、A','LIPROD/PROD_ANNUITY_TYPE ≠ 空值',null,null,'您選擇的保單不提供申請變更年金給付方式!!');
Insert into ESERVICE.dbo.TRANS_RULES (TRANS_TYPE,TRANS_NAME,POLICY_TYPE,TEXT1,TEXT2,TEXT3,TEXT4,DENY_MSG) values ('ANNUITY_METHOD','年金給付方式','UQ','T、S、A','LIPROD/PROD_ANNUITY_TYPE ≠ 空值',null,null,'您選擇的保單不提供申請變更年金給付方式!!');
Insert into ESERVICE.dbo.TRANS_RULES (TRANS_TYPE,TRANS_NAME,POLICY_TYPE,TEXT1,TEXT2,TEXT3,TEXT4,DENY_MSG) values ('ANNUITY_METHOD','年金給付方式','UR','T、S、A','LIPROD/PROD_ANNUITY_TYPE ≠ 空值',null,null,'您選擇的保單不提供申請變更年金給付方式!!');
GO

--update ESERVICE.TRANS_RULES
update ESERVICE.dbo.TRANS_RULES set TEXT1='T、A' where TRANS_TYPE='ANNUITY_METHOD' and POLICY_TYPE in ('UP','UQ','UR');
GO

--alert ESERVICE.TRANS_ANNUITY_METHOD
alter table ESERVICE.dbo.TRANS_ANNUITY_METHOD 
add 
	GUARANTEE_PERIOD     varchar(5) default '',
	GUARANTEE_PERIOD_OLD varchar(5) default ''
;
GO

--insert ESERVICE_ADM.PARAMETER_CATEGORY
insert into ESERVICE_ADM.dbo.PARAMETER_CATEGORY (PARAMETER_CATEGORY_ID, SYSTEM_ID, CATEGORY_CODE, CATEGORY_NAME, REMARK, STATUS, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
values ((select max(PARAMETER_CATEGORY_ID)+1 from ESERVICE_ADM.dbo.PARAMETER_CATEGORY), 'eservice', 'ANNUITY_METHOD_GUARANTEE_PERIOD', '年金給付保證期間', null, 1, getdate(), 'system', null, null);
GO

--insert TRANS_RULES 分期給付保證期間為10,15,20年
insert into ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
values ((select max(PARAMETER_ID)+1 from ESERVICE_ADM.dbo.PARAMETER), 'eservice', 'AG', '分期給付保證期間', '10,15,20', (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='ANNUITY_METHOD_GUARANTEE_PERIOD'), null, null, 1, null, null, getdate(), 'system', null, null);

insert into ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
values ((select max(PARAMETER_ID)+1 from ESERVICE_ADM.dbo.PARAMETER), 'eservice', 'BC', '分期給付保證期間', '10,15,20', (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='ANNUITY_METHOD_GUARANTEE_PERIOD'), null, null, 1, null, null, getdate(), 'system', null, null);

insert into ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
values ((select max(PARAMETER_ID)+1 from ESERVICE_ADM.dbo.PARAMETER), 'eservice', 'UD', '分期給付保證期間', '10,15,20', (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='ANNUITY_METHOD_GUARANTEE_PERIOD'), null, null, 1, null, null, getdate(), 'system', null, null);

insert into ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
values ((select max(PARAMETER_ID)+1 from ESERVICE_ADM.dbo.PARAMETER), 'eservice', 'UJ', '分期給付保證期間', '10,15,20', (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='ANNUITY_METHOD_GUARANTEE_PERIOD'), null, null, 1, null, null, getdate(), 'system', null, null);

insert into ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
values ((select max(PARAMETER_ID)+1 from ESERVICE_ADM.dbo.PARAMETER), 'eservice', 'UL', '分期給付保證期間', '10,15,20', (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='ANNUITY_METHOD_GUARANTEE_PERIOD'), null, null, 1, null, null, getdate(), 'system', null, null);

--insert TRANS_RULES 分期給付保證期間為20年
insert into ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
values ((select max(PARAMETER_ID)+1 from ESERVICE_ADM.dbo.PARAMETER), 'eservice', 'UP', '分期給付保證期間', '20', (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='ANNUITY_METHOD_GUARANTEE_PERIOD'), null, null, 1, null, null, getdate(), 'system', null, null);

insert into ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
values ((select max(PARAMETER_ID)+1 from ESERVICE_ADM.dbo.PARAMETER), 'eservice', 'UQ', '分期給付保證期間', '20', (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='ANNUITY_METHOD_GUARANTEE_PERIOD'), null, null, 1, null, null, getdate(), 'system', null, null);

insert into ESERVICE_ADM.dbo.PARAMETER (PARAMETER_ID, SYSTEM_ID, PARAMETER_CODE, PARAMETER_NAME, PARAMETER_VALUE, PARAMETER_CATEGORY_ID, SORT_NO, REMARK, STATUS, ENCRYPT_TYPE, PARENT_PARAMETER_ID, CREATE_DATE, CREATE_USER, UPDATE_DATE, UPDATE_USER)
values ((select max(PARAMETER_ID)+1 from ESERVICE_ADM.dbo.PARAMETER), 'eservice', 'UR', '分期給付保證期間', '20', (select PARAMETER_CATEGORY_ID from ESERVICE_ADM.dbo.PARAMETER_CATEGORY where CATEGORY_CODE='ANNUITY_METHOD_GUARANTEE_PERIOD'), null, null, 1, null, null, getdate(), 'system', null, null);

GO




